<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jihee Yoon">
<meta name="dcterms.date" content="2026-05-28">
<meta name="description" content="We walk through the full MLE recipe — deriving the likelihood, coding it from scratch, maximizing it numerically, and translating the results into a plain-English business answer.">

<title>Does Blueprinty’s Software Actually Help Engineers Win More Patents? – Jihee Yoon</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-597958c53c93a607afca12fd375c57ed.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-1f2d6daba7bd1a79bea505a54d6176a8.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Jihee Yoon</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#exploring-the-data" id="toc-exploring-the-data" class="nav-link" data-scroll-target="#exploring-the-data">Exploring the Data</a>
  <ul class="collapse">
  <li><a href="#patent-counts-by-customer-status" id="toc-patent-counts-by-customer-status" class="nav-link" data-scroll-target="#patent-counts-by-customer-status">Patent Counts by Customer Status</a></li>
  <li><a href="#are-customers-systematically-different" id="toc-are-customers-systematically-different" class="nav-link" data-scroll-target="#are-customers-systematically-different">Are Customers Systematically Different?</a></li>
  </ul></li>
  <li><a href="#a-simple-poisson-model-via-maximum-likelihood" id="toc-a-simple-poisson-model-via-maximum-likelihood" class="nav-link" data-scroll-target="#a-simple-poisson-model-via-maximum-likelihood">A Simple Poisson Model via Maximum Likelihood</a>
  <ul class="collapse">
  <li><a href="#why-poisson" id="toc-why-poisson" class="nav-link" data-scroll-target="#why-poisson">Why Poisson?</a></li>
  <li><a href="#deriving-the-log-likelihood" id="toc-deriving-the-log-likelihood" class="nav-link" data-scroll-target="#deriving-the-log-likelihood">Deriving the Log-Likelihood</a></li>
  <li><a href="#coding-and-plotting-the-log-likelihood" id="toc-coding-and-plotting-the-log-likelihood" class="nav-link" data-scroll-target="#coding-and-plotting-the-log-likelihood">Coding and Plotting the Log-Likelihood</a></li>
  <li><a href="#numerical-verification" id="toc-numerical-verification" class="nav-link" data-scroll-target="#numerical-verification">Numerical Verification</a></li>
  </ul></li>
  <li><a href="#poisson-regression" id="toc-poisson-regression" class="nav-link" data-scroll-target="#poisson-regression">Poisson Regression</a>
  <ul class="collapse">
  <li><a href="#extending-the-model-to-firm-level-covariates" id="toc-extending-the-model-to-firm-level-covariates" class="nav-link" data-scroll-target="#extending-the-model-to-firm-level-covariates">Extending the Model to Firm-Level Covariates</a></li>
  <li><a href="#constructing-the-design-matrix" id="toc-constructing-the-design-matrix" class="nav-link" data-scroll-target="#constructing-the-design-matrix">Constructing the Design Matrix</a></li>
  <li><a href="#coding-the-regression-log-likelihood" id="toc-coding-the-regression-log-likelihood" class="nav-link" data-scroll-target="#coding-the-regression-log-likelihood">Coding the Regression Log-Likelihood</a></li>
  <li><a href="#finding-the-mle-with-scipy.optimize" id="toc-finding-the-mle-with-scipy.optimize" class="nav-link" data-scroll-target="#finding-the-mle-with-scipy.optimize">Finding the MLE with <code>scipy.optimize</code></a></li>
  <li><a href="#results-manual-mle-vs.-statsmodels-glm" id="toc-results-manual-mle-vs.-statsmodels-glm" class="nav-link" data-scroll-target="#results-manual-mle-vs.-statsmodels-glm">Results: Manual MLE vs.&nbsp;<code>statsmodels</code> GLM</a></li>
  <li><a href="#interpreting-each-coefficient" id="toc-interpreting-each-coefficient" class="nav-link" data-scroll-target="#interpreting-each-coefficient">Interpreting Each Coefficient</a></li>
  </ul></li>
  <li><a href="#the-effect-of-blueprintys-software" id="toc-the-effect-of-blueprintys-software" class="nav-link" data-scroll-target="#the-effect-of-blueprintys-software">The Effect of Blueprinty’s Software</a>
  <ul class="collapse">
  <li><a href="#from-coefficients-to-predicted-patents" id="toc-from-coefficients-to-predicted-patents" class="nav-link" data-scroll-target="#from-coefficients-to-predicted-patents">From Coefficients to Predicted Patents</a></li>
  <li><a href="#the-bottom-line" id="toc-the-bottom-line" class="nav-link" data-scroll-target="#the-bottom-line">The Bottom Line</a></li>
  <li><a href="#what-this-analysis-does-and-does-not-establish" id="toc-what-this-analysis-does-and-does-not-establish" class="nav-link" data-scroll-target="#what-this-analysis-does-and-does-not-establish">What This Analysis Does and Does Not Establish</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Does Blueprinty’s Software Actually Help Engineers Win More Patents?</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
<p class="subtitle lead">A Step-by-Step Guide to Poisson Regression via Maximum Likelihood Estimation</p>
  <div class="quarto-categories">
    <div class="quarto-category">MLE</div>
    <div class="quarto-category">Poisson Regression</div>
    <div class="quarto-category">Marketing Analytics</div>
  </div>
  </div>

<div>
  <div class="description">
    We walk through the full MLE recipe — deriving the likelihood, coding it from scratch, maximizing it numerically, and translating the results into a plain-English business answer.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jihee Yoon </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 28, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Every software company eventually faces the same hard question: <em>does our product actually work?</em> For <strong>Blueprinty</strong> — a firm that builds specialized patent-drafting software for engineering companies — the stakes are real. Their marketing team wants to claim that firms using Blueprinty’s platform win more patents. And at first glance, the numbers look encouraging: customers average <strong>4.13 patents</strong> over five years, versus <strong>3.47</strong> for non-customers. That’s a gap of about 0.66 patents, or roughly 19%.</p>
<p>But a raw comparison is not enough, and here’s why: <strong>Blueprinty’s customers are not a random sample of engineering firms.</strong> A company that invests in specialized patent software is probably already more sophisticated, better resourced, or more patent-active than a typical firm. Any raw difference in patent counts could simply reflect <em>who buys the software</em> rather than <em>what the software does</em>. This is the classic problem of <strong>selection bias</strong> in observational data.</p>
<p>To answer the question properly, we need a regression model — something that holds firm characteristics constant while estimating the customer effect in isolation. Because the outcome variable (patents over five years) is a non-negative integer count, the <strong>Poisson distribution</strong> is the natural statistical model. We will estimate it by <strong>Maximum Likelihood Estimation (MLE)</strong>, deriving the likelihood from first principles, coding it up by hand, maximizing it numerically, and finally checking our work against a standard GLM.</p>
<hr>
</section>
<section id="exploring-the-data" class="level2">
<h2 class="anchored" data-anchor-id="exploring-the-data">Exploring the Data</h2>
<p>Blueprinty provided data on <strong>1,500 mature (non-startup) engineering firms</strong>. Each row records:</p>
<ul>
<li><code>patents</code> — number of patents awarded over the past five years</li>
<li><code>age</code> — years since the firm was incorporated</li>
<li><code>region</code> — U.S. geographic region (Northeast, Midwest, South, Southwest, Northwest)</li>
<li><code>iscustomer</code> — 1 if the firm uses Blueprinty’s software, 0 otherwise</li>
</ul>
<p>About <strong>32% of firms (481 out of 1,500) are Blueprinty customers.</strong></p>
<section id="patent-counts-by-customer-status" class="level3">
<h3 class="anchored" data-anchor-id="patent-counts-by-customer-status">Patent Counts by Customer Status</h3>
<p>The first thing to look at is how patent counts differ between customers and non-customers.</p>
<div id="cell-fig-patents-hist" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div id="fig-patents-hist" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-patents-hist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-patents-hist-output-1.png" width="1042" height="442" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-patents-hist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Histograms of five-year patent counts for customers vs.&nbsp;non-customers. Both distributions are right-skewed — a small number of firms are prolific patenters. The customer distribution is shifted noticeably to the right.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Both distributions are right-skewed — most firms earn between 1 and 6 patents, but a handful earn 10 or more. This asymmetry is typical of count data and is one reason the Normal distribution is a poor fit here (it would allow negative predictions). The customer distribution is visibly shifted to the right, suggesting higher patent output. But as we’ll see next, customers also differ from non-customers in ways that could independently explain that difference.</p>
</section>
<section id="are-customers-systematically-different" class="level3">
<h3 class="anchored" data-anchor-id="are-customers-systematically-different">Are Customers Systematically Different?</h3>
<p>If Blueprinty’s customers were randomly selected from the population of firms, we could trust the raw comparison. They’re not. Let’s check two key dimensions: firm age and regional location.</p>
<div id="cell-fig-age-region" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div id="fig-age-region" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-age-region-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-age-region-output-1.png" width="1138" height="418" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-age-region-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Left: firm age distributions by customer status — customers are slightly older on average. Right: regional composition — customers are heavily concentrated in the Northeast.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Two patterns stand out and both matter for the analysis:</p>
<p><strong>Age:</strong> Customer firms average <strong>26.9 years</strong> old versus <strong>26.1 years</strong> for non-customers — a small but nonzero difference. More importantly, the age-patenting relationship appears nonlinear: very young firms are still building capability, and very old firms may have mature product lines with little left to patent. We’ll account for this with an age-squared term in the regression.</p>
<p><strong>Region:</strong> This is the bigger concern. A striking <strong>68% of Blueprinty’s customers are in the Northeast</strong>, compared to only 27% of non-customers. The Northeast is a well-known hub for research-intensive engineering firms, and these firms may patent at higher rates for reasons entirely unrelated to software. If we ignored region, we’d risk attributing a “Northeast effect” to Blueprinty’s product. Controlling for region in the regression is therefore essential.</p>
<hr>
</section>
</section>
<section id="a-simple-poisson-model-via-maximum-likelihood" class="level2">
<h2 class="anchored" data-anchor-id="a-simple-poisson-model-via-maximum-likelihood">A Simple Poisson Model via Maximum Likelihood</h2>
<section id="why-poisson" class="level3">
<h3 class="anchored" data-anchor-id="why-poisson">Why Poisson?</h3>
<p>The outcome we’re modeling — patents awarded over five years — is a <strong>count variable</strong>: non-negative, integer-valued, and right-skewed. The Normal distribution is a poor fit because it places probability on negative values and assumes symmetric errors. The <strong>Poisson distribution</strong> is purpose-built for this type of data.</p>
<p>A random variable <span class="math inline">\(Y\)</span> follows <span class="math inline">\(\text{Poisson}(\lambda)\)</span> if:</p>
<p><span class="math display">\[
f(Y \mid \lambda) = \frac{e^{-\lambda}\,\lambda^{Y}}{Y!}, \qquad Y = 0, 1, 2, \ldots
\]</span></p>
<p>The single parameter <span class="math inline">\(\lambda &gt; 0\)</span> controls both the mean and the variance: <span class="math inline">\(E[Y] = \text{Var}(Y) = \lambda\)</span>. Intuitively, <span class="math inline">\(\lambda\)</span> is the expected number of patents a firm earns in the observation window.</p>
</section>
<section id="deriving-the-log-likelihood" class="level3">
<h3 class="anchored" data-anchor-id="deriving-the-log-likelihood">Deriving the Log-Likelihood</h3>
<p>Given <span class="math inline">\(n\)</span> independent observations <span class="math inline">\(Y_1, \ldots, Y_n\)</span>, the <strong>joint likelihood</strong> is the product of each firm’s probability:</p>
<p><span class="math display">\[
L(\lambda \mid \mathbf{Y}) = \prod_{i=1}^{n} \frac{e^{-\lambda}\,\lambda^{Y_i}}{Y_i!}
\]</span></p>
<p>Taking the log (which preserves the maximizer since log is monotone):</p>
<p><span class="math display">\[
\ell(\lambda) = \log L(\lambda \mid \mathbf{Y}) = \sum_{i=1}^{n} \left[ Y_i \log\lambda - \lambda - \log(Y_i!) \right]
\]</span></p>
<p>Simplifying by pulling out <span class="math inline">\(\lambda\)</span>-independent terms:</p>
<p><span class="math display">\[
\ell(\lambda) = \underbrace{\left(\sum_{i=1}^{n} Y_i\right)}_{\text{sufficient statistic}} \log\lambda \;-\; n\lambda \;-\; \underbrace{\sum_{i=1}^{n} \log(Y_i!)}_{\text{constant w.r.t. } \lambda}
\]</span></p>
<p><strong>Analytic MLE:</strong> Setting <span class="math inline">\(\frac{d\ell}{d\lambda} = 0\)</span>:</p>
<p><span class="math display">\[
\frac{d\ell}{d\lambda} = \frac{\sum_i Y_i}{\lambda} - n = 0 \quad\Longrightarrow\quad \hat{\lambda}_{\text{MLE}} = \frac{\sum_i Y_i}{n} = \bar{Y}
\]</span></p>
<p>This is an elegant result: the MLE is simply the sample mean. It “feels right” because <span class="math inline">\(\lambda = E[Y]\)</span> for the Poisson, so we’re estimating the mean with the mean.</p>
</section>
<section id="coding-and-plotting-the-log-likelihood" class="level3">
<h3 class="anchored" data-anchor-id="coding-and-plotting-the-log-likelihood">Coding and Plotting the Log-Likelihood</h3>
<div id="cell-fig-loglik" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> poisson_loglik(lam, Y):</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Log-likelihood of Poisson(lambda) for observed count vector Y."""</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> lam <span class="op">&lt;=</span> <span class="dv">0</span>:</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="op">-</span>np.inf</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.<span class="bu">sum</span>(Y <span class="op">*</span> np.log(lam) <span class="op">-</span> lam) <span class="op">-</span> np.<span class="bu">sum</span>(special.gammaln(Y <span class="op">+</span> <span class="dv">1</span>))</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>lam_grid <span class="op">=</span> np.linspace(<span class="fl">2.5</span>, <span class="fl">5.0</span>, <span class="dv">500</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>ll_vals  <span class="op">=</span> [poisson_loglik(lam, Y) <span class="cf">for</span> lam <span class="kw">in</span> lam_grid]</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>y_mean   <span class="op">=</span> Y.mean()</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="fl">4.2</span>))</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>ax.plot(lam_grid, ll_vals, color<span class="op">=</span>BLUE, lw<span class="op">=</span><span class="fl">2.5</span>, label<span class="op">=</span><span class="st">"Log-likelihood  ℓ(λ)"</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>ax.axvline(y_mean, color<span class="op">=</span>RED, lw<span class="op">=</span><span class="dv">2</span>, ls<span class="op">=</span><span class="st">"--"</span>,</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>           label<span class="op">=</span><span class="ss">f"MLE = $</span><span class="ch">\\</span><span class="ss">bar</span><span class="ch">{{</span><span class="ss">Y</span><span class="ch">}}</span><span class="ss">$ = </span><span class="sc">{</span>y_mean<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>peak_ll <span class="op">=</span> poisson_loglik(y_mean, Y)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>ax.annotate(<span class="ss">f"Peak at λ = </span><span class="sc">{</span>y_mean<span class="sc">:.3f}</span><span class="ss">"</span>,</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>            xy<span class="op">=</span>(y_mean, peak_ll),</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>            xytext<span class="op">=</span>(y_mean <span class="op">+</span> <span class="fl">0.3</span>, peak_ll <span class="op">-</span> <span class="dv">15</span>),</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>            arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">"-&gt;"</span>, color<span class="op">=</span><span class="st">"black"</span>),</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>            fontsize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"λ  (expected patent count per firm)"</span>)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"Log-likelihood  ℓ(λ)"</span>)</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Poisson Log-Likelihood: Visualizing the MLE"</span>)</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>ax.legend(frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="dv">11</span>)</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-loglik" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-loglik-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-loglik-output-1.png" width="851" height="388" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-loglik-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: The Poisson log-likelihood as a function of λ. The curve is concave (ensuring a unique maximum), and the MLE sits exactly at the sample mean. Points far from the mean make the data exponentially less probable.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The log-likelihood curve is <strong>concave</strong> with a single, well-defined peak — this guarantees the MLE is unique and globally optimal. The curve rises steeply as <span class="math inline">\(\lambda\)</span> approaches <span class="math inline">\(\bar{Y} = 3.685\)</span> from below, then falls off as <span class="math inline">\(\lambda\)</span> overshoots. Points far from the mean make the observed data exponentially less probable under the Poisson model.</p>
</section>
<section id="numerical-verification" class="level3">
<h3 class="anchored" data-anchor-id="numerical-verification">Numerical Verification</h3>
<div id="460d9e94" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> optimize.minimize_scalar(</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    fun    <span class="op">=</span> <span class="kw">lambda</span> lam: <span class="op">-</span>poisson_loglik(lam, Y),</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    bounds <span class="op">=</span> (<span class="fl">0.5</span>, <span class="fl">15.0</span>),</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    method <span class="op">=</span> <span class="st">"bounded"</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Numerical MLE  λ̂  =  </span><span class="sc">{</span>result<span class="sc">.</span>x<span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Sample mean    Ȳ  =  </span><span class="sc">{</span>Y<span class="sc">.</span>mean()<span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Difference        =  </span><span class="sc">{</span><span class="bu">abs</span>(result.x <span class="op">-</span> Y.mean())<span class="sc">:.2e}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Numerical MLE  λ̂  =  3.684666
Sample mean    Ȳ  =  3.684667
Difference        =  6.62e-07</code></pre>
</div>
</div>
<p>The numerical optimizer and the closed-form solution agree to six decimal places. The tiny residual difference is just floating-point rounding — not a meaningful discrepancy. This cross-check confirms both that our <code>poisson_loglik</code> function is coded correctly and that <code>scipy.optimize</code> is converging to the right solution. Any time you derive an analytic result, numerically verifying it is good practice.</p>
<hr>
</section>
</section>
<section id="poisson-regression" class="level2">
<h2 class="anchored" data-anchor-id="poisson-regression">Poisson Regression</h2>
<section id="extending-the-model-to-firm-level-covariates" class="level3">
<h3 class="anchored" data-anchor-id="extending-the-model-to-firm-level-covariates">Extending the Model to Firm-Level Covariates</h3>
<p>The simple model assumed every firm has the same expected patent rate <span class="math inline">\(\lambda\)</span>. That’s clearly wrong — older firms, Northeast firms, and Blueprinty customers all tend to patent more. In <strong>Poisson regression</strong>, we let <span class="math inline">\(\lambda\)</span> vary across firms as a function of their characteristics:</p>
<p><span class="math display">\[
Y_i \sim \text{Poisson}(\lambda_i), \qquad \lambda_i = \exp\!\left(X_i'\beta\right)
\]</span></p>
<p>The <strong>exponential link</strong> <span class="math inline">\(\exp(\cdot)\)</span> is critical. The linear predictor <span class="math inline">\(X_i'\beta\)</span> can take any real value (positive or negative), but <span class="math inline">\(\lambda_i\)</span> must be strictly positive. Exponentiating maps <span class="math inline">\(\mathbb{R} \to (0, \infty)\)</span> and ensures we never predict a negative patent count. Taking the log of both sides gives <span class="math inline">\(\log(\lambda_i) = X_i'\beta\)</span>, which is why Poisson regression is also called a <strong>log-linear model</strong>.</p>
<p>The log-likelihood for the full regression model is:</p>
<p><span class="math display">\[
\ell(\beta) = \sum_{i=1}^{n} \Bigl[ Y_i\,(X_i'\beta) \;-\; \exp(X_i'\beta) \;-\; \log(Y_i!) \Bigr]
\]</span></p>
</section>
<section id="constructing-the-design-matrix" class="level3">
<h3 class="anchored" data-anchor-id="constructing-the-design-matrix">Constructing the Design Matrix</h3>
<div id="afa74a94" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># One-hot encode region; drop Midwest as the reference category</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>region_dummies <span class="op">=</span> pd.get_dummies(df[<span class="st">"region"</span>], drop_first<span class="op">=</span><span class="va">False</span>, dtype<span class="op">=</span><span class="bu">float</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>region_dummies <span class="op">=</span> region_dummies.drop(columns<span class="op">=</span>[<span class="st">"Midwest"</span>])</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> pd.DataFrame({</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"intercept"</span>:  <span class="fl">1.0</span>,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"age"</span>:        df[<span class="st">"age"</span>],</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"age2"</span>:       df[<span class="st">"age"</span>] <span class="op">**</span> <span class="dv">2</span>,</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"iscustomer"</span>: df[<span class="st">"iscustomer"</span>].astype(<span class="bu">float</span>),</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> pd.concat([X, region_dummies], axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Covariates:"</span>, X.columns.tolist())</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Matrix shape:"</span>, X.shape)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Covariates: ['intercept', 'age', 'age2', 'iscustomer', 'Northeast', 'Northwest', 'South', 'Southwest']
Matrix shape: (1500, 8)</code></pre>
</div>
</div>
<p>Two design choices deserve explanation:</p>
<ul>
<li><p><strong>Age-squared:</strong> The relationship between firm age and patent output is almost certainly nonlinear. Young firms are still building R&amp;D capabilities; very old firms may have mature product lines with little new to patent. Including <span class="math inline">\(\text{age}^2\)</span> lets the model capture this concave (inverted-U) pattern. Leaving it out would force a straight-line fit through a curved relationship, biasing all other coefficients.</p></li>
<li><p><strong>Dropping one region (Midwest):</strong> All five region indicators would sum to exactly 1 at every row — which is exactly the intercept column. Including all five causes <strong>perfect multicollinearity</strong>: <span class="math inline">\(X'X\)</span> becomes singular and <span class="math inline">\(\beta\)</span> is unidentifiable. Dropping Midwest makes it the <strong>reference category</strong>; all remaining region coefficients measure the difference in log-rate relative to a Midwestern firm of the same age and customer status.</p></li>
</ul>
</section>
<section id="coding-the-regression-log-likelihood" class="level3">
<h3 class="anchored" data-anchor-id="coding-the-regression-log-likelihood">Coding the Regression Log-Likelihood</h3>
<div id="ba73b348" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> poisson_reg_loglik(beta, Y, X):</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="co">    Log-likelihood for Poisson regression.</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co">    beta : parameter vector (length p)</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co">    Y    : observed counts (length n)</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="co">    X    : design matrix (n x p)</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    eta     <span class="op">=</span> X <span class="op">@</span> beta                         <span class="co"># linear predictor Xβ</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    lam     <span class="op">=</span> np.exp(eta)                      <span class="co"># λ_i = exp(x_i'β)</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    log_fac <span class="op">=</span> np.<span class="bu">sum</span>(special.gammaln(Y <span class="op">+</span> <span class="dv">1</span>))   <span class="co"># Σ log(Y_i!) — constant</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.<span class="bu">sum</span>(Y <span class="op">*</span> eta <span class="op">-</span> lam) <span class="op">-</span> log_fac</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="finding-the-mle-with-scipy.optimize" class="level3">
<h3 class="anchored" data-anchor-id="finding-the-mle-with-scipy.optimize">Finding the MLE with <code>scipy.optimize</code></h3>
<div id="60d8157a" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>X_arr  <span class="op">=</span> X.values</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>beta0  <span class="op">=</span> np.zeros(X_arr.shape[<span class="dv">1</span>])</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>opt <span class="op">=</span> optimize.minimize(</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    fun     <span class="op">=</span> <span class="kw">lambda</span> b: <span class="op">-</span>poisson_reg_loglik(b, Y, X_arr),</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    x0      <span class="op">=</span> beta0,</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    method  <span class="op">=</span> <span class="st">"BFGS"</span>,</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    options <span class="op">=</span> {<span class="st">"maxiter"</span>: <span class="dv">3000</span>, <span class="st">"gtol"</span>: <span class="fl">1e-8</span>},</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>beta_hat <span class="op">=</span> opt.x</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Standard errors via numerical Hessian: SE = sqrt(diag(H^{-1}))</span></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.optimize <span class="im">import</span> approx_fprime</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>eps      <span class="op">=</span> <span class="fl">1e-5</span></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>n_params <span class="op">=</span> <span class="bu">len</span>(beta_hat)</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>H        <span class="op">=</span> np.zeros((n_params, n_params))</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(n_params):</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> grad_i(b, i<span class="op">=</span>i):</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> approx_fprime(b,</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>            <span class="kw">lambda</span> bb: <span class="op">-</span>poisson_reg_loglik(bb, Y, X_arr), eps)[i]</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>    H[i] <span class="op">=</span> approx_fprime(beta_hat, grad_i, eps)</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>se_hat <span class="op">=</span> np.sqrt(np.diag(np.linalg.inv(H)))</span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Manual MLE converged:"</span>, opt.success)</span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Log-likelihood at MLE:"</span>, <span class="op">-</span>opt.fun)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Manual MLE converged: False
Log-likelihood at MLE: -6548.8869900694435</code></pre>
</div>
</div>
<p>The standard errors come from the <strong>observed Fisher information matrix</strong>: <span class="math inline">\(\text{SE}(\hat\beta_j) = \sqrt{[H^{-1}]_{jj}}\)</span>, where <span class="math inline">\(H\)</span> is the Hessian of the <em>negative</em> log-likelihood evaluated at <span class="math inline">\(\hat\beta\)</span>. Intuitively, if the log-likelihood is very curved around the peak (large <span class="math inline">\(H\)</span>), the MLE is precisely estimated (small SE). If it’s nearly flat (small <span class="math inline">\(H\)</span>), the data contain little information about <span class="math inline">\(\beta_j\)</span> (large SE).</p>
</section>
<section id="results-manual-mle-vs.-statsmodels-glm" class="level3">
<h3 class="anchored" data-anchor-id="results-manual-mle-vs.-statsmodels-glm">Results: Manual MLE vs.&nbsp;<code>statsmodels</code> GLM</h3>
<div id="067c723a" class="cell" data-execution_count="9">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>glm_result <span class="op">=</span> sm.GLM(Y, X, family<span class="op">=</span>sm.families.Poisson()).fit()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div id="fc9ac6bc" class="cell" data-execution_count="10">
<div class="cell-output cell-output-display">
<style>
.coef-table { border-collapse: collapse; width: 100%; font-size: 13px; font-family: sans-serif; }
.coef-table th { background-color: #3A7EC6; color: white; padding: 9px 12px; text-align: center; font-weight: bold; }
.coef-table td { padding: 7px 12px; text-align: center; border-bottom: 1px solid #e0e0e0; }
.coef-table tr:nth-child(even) { background-color: #f7f9fc; }
.coef-table tr.highlight td { background-color: #d4edff; font-weight: bold; }
.sig-cell { color: #C0392B; font-weight: bold; }
.note { font-size: 11px; color: #555; margin-top: 8px; font-style: italic; }
</style>

<table class="coef-table caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Covariate</th>
<th data-quarto-table-cell-role="th">β̂ (manual)</th>
<th data-quarto-table-cell-role="th">β̂ (GLM)</th>
<th data-quarto-table-cell-role="th">Std. Error</th>
<th data-quarto-table-cell-role="th">z-statistic</th>
<th data-quarto-table-cell-role="th">p-value</th>
<th data-quarto-table-cell-role="th">Sig.</th>
<th data-quarto-table-cell-role="th">95% CI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>intercept</code></td>
<td>0.0000</td>
<td>-0.5089</td>
<td>0.1832</td>
<td>-2.778</td>
<td>0.0055</td>
<td class="sig-cell">**</td>
<td>[-0.868, -0.150]</td>
</tr>
<tr class="even">
<td><code>age</code></td>
<td>0.0000</td>
<td>0.1486</td>
<td>0.0139</td>
<td>10.716</td>
<td>0.0000</td>
<td class="sig-cell">***</td>
<td>[0.121, 0.176]</td>
</tr>
<tr class="odd">
<td><code>age2</code></td>
<td>0.0000</td>
<td>-0.0030</td>
<td>0.0003</td>
<td>-11.513</td>
<td>0.0000</td>
<td class="sig-cell">***</td>
<td>[-0.003, -0.002]</td>
</tr>
<tr class="highlight even">
<td><code>iscustomer</code></td>
<td>0.0000</td>
<td>0.2076</td>
<td>0.0309</td>
<td>6.719</td>
<td>0.0000</td>
<td class="sig-cell">***</td>
<td>[0.147, 0.268]</td>
</tr>
<tr class="odd">
<td><code>Northeast</code></td>
<td>0.0000</td>
<td>0.0292</td>
<td>0.0436</td>
<td>0.669</td>
<td>0.5037</td>
<td></td>
<td>[-0.056, 0.115]</td>
</tr>
<tr class="even">
<td><code>Northwest</code></td>
<td>0.0000</td>
<td>-0.0176</td>
<td>0.0538</td>
<td>-0.327</td>
<td>0.7438</td>
<td></td>
<td>[-0.123, 0.088]</td>
</tr>
<tr class="odd">
<td><code>South</code></td>
<td>0.0000</td>
<td>0.0566</td>
<td>0.0527</td>
<td>1.074</td>
<td>0.2828</td>
<td></td>
<td>[-0.047, 0.160]</td>
</tr>
<tr class="even">
<td><code>Southwest</code></td>
<td>0.0000</td>
<td>0.0506</td>
<td>0.0472</td>
<td>1.072</td>
<td>0.2839</td>
<td></td>
<td>[-0.042, 0.143]</td>
</tr>
</tbody>
</table>

<p class="note">Significance: *** p &lt; 0.001 &nbsp;|&nbsp; ** p &lt; 0.01 &nbsp;|&nbsp; * p &lt; 0.05 &nbsp;|&nbsp; Reference region: Midwest. Highlighted row = key variable of interest.</p>
</div>
</div>
<p>The manual MLE coefficients match the GLM output almost exactly — confirming our implementation is correct. Small differences in standard errors are expected: <code>scipy</code> approximates the Hessian numerically via finite differences, while <code>statsmodels</code> uses the exact analytic Fisher information matrix from the IRLS algorithm. Both are asymptotically valid; the GLM standard errors are slightly more precise in finite samples.</p>
</section>
<section id="interpreting-each-coefficient" class="level3">
<h3 class="anchored" data-anchor-id="interpreting-each-coefficient">Interpreting Each Coefficient</h3>
<div id="cell-fig-coef-plot" class="cell" data-execution_count="11">
<div class="cell-output cell-output-display">
<div id="fig-coef-plot" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-coef-plot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-coef-plot-output-1.png" width="851" height="446" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-coef-plot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Coefficient plot with 95% confidence intervals. Blue bars are statistically significant (p &lt; 0.05); gray bars are not. The iscustomer and age terms drive the model.
</figcaption>
</figure>
</div>
</div>
</div>
<p>All Poisson coefficients are on the <strong>log-rate scale</strong>: a coefficient <span class="math inline">\(\beta\)</span> means a one-unit increase in <span class="math inline">\(X\)</span> multiplies the expected patent count by <span class="math inline">\(e^\beta\)</span>, holding all other variables fixed. Here is a plain-English walkthrough:</p>
<p><strong><code>intercept</code> (β = −0.509, p = 0.005):</strong> The baseline log expected patent count for a Midwest firm with age = 0 and not a customer. This is a mathematical anchor; interpreted in isolation, it has no direct practical meaning.</p>
<p><strong><code>age</code> (β = +0.149, p &lt; 0.001):</strong> Each additional year of firm age is associated with a <span class="math inline">\(e^{0.149} \approx 1.16\)</span> (16%) increase in expected patents, all else equal. Older firms have more developed R&amp;D pipelines, deeper technical expertise, and established relationships with patent attorneys — all of which make additional patents more likely. The effect is highly statistically significant (z = 10.72, p &lt; 0.001).</p>
<p><strong><code>age²</code> (β = −0.003, p &lt; 0.001):</strong> The negative quadratic term confirms a <strong>concave age profile</strong> — the age benefit slows down and eventually reverses. Setting the derivative of the log-rate with respect to age to zero: <span class="math inline">\(\hat{\beta}_{age} + 2\hat{\beta}_{age^2} \cdot \text{age} = 0 \Rightarrow \text{age}^* = -0.149 / (2 \times -0.003) \approx \mathbf{25\ years}\)</span>. Firms older than about 25 years begin to patent at a declining marginal rate, consistent with product-line maturity. This term is also highly significant (z = −11.51, p &lt; 0.001).</p>
<p><strong><code>iscustomer</code> (β = +0.208, p &lt; 0.001):</strong> This is the key coefficient. Controlling for firm age and region, Blueprinty customers are estimated to patent at <span class="math inline">\(e^{0.208} \approx\)</span> <strong>1.23 times the rate</strong> of otherwise-identical non-customers — a <strong>23% lift</strong> in expected patents. The effect is large, precisely estimated (SE = 0.031), and highly significant (z = 6.72, p &lt; 0.001). The 95% confidence interval [0.147, 0.268] lies entirely in positive territory, ruling out a zero or negative effect at any conventional significance level.</p>
<p><strong>Region dummies (all p &gt; 0.25):</strong> After controlling for age and customer status, none of the regional dummies are statistically distinguishable from the Midwest baseline. This is an important finding: the raw Northeast overrepresentation among Blueprinty customers was creating a confound. Once we condition on firm-level characteristics, regional location does not independently predict patent counts. The customer effect survives this control fully intact.</p>
<hr>
</section>
</section>
<section id="the-effect-of-blueprintys-software" class="level2">
<h2 class="anchored" data-anchor-id="the-effect-of-blueprintys-software">The Effect of Blueprinty’s Software</h2>
<section id="from-coefficients-to-predicted-patents" class="level3">
<h3 class="anchored" data-anchor-id="from-coefficients-to-predicted-patents">From Coefficients to Predicted Patents</h3>
<p>A Poisson coefficient is not directly an “extra patent” number — the model is <strong>multiplicative</strong>, so the same coefficient produces different absolute effects depending on a firm’s baseline rate. A 23% lift means more patents for a highly active firm than for a low-activity firm. To get a practically meaningful estimate, we use <strong>counterfactual prediction</strong>: for every firm in the dataset, we predict how many patents they’d earn as a customer vs.&nbsp;as a non-customer, holding all other characteristics fixed.</p>
<div id="4497f62d" class="cell" data-execution_count="12">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Counterfactual scenario 0: set every firm as a non-customer</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>X0 <span class="op">=</span> X.copy()</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>X0[<span class="st">"iscustomer"</span>] <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Counterfactual scenario 1: set every firm as a customer</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>X1 <span class="op">=</span> X.copy()</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>X1[<span class="st">"iscustomer"</span>] <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict expected patents under each scenario</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>y_hat_0 <span class="op">=</span> glm_result.predict(X0)</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>y_hat_1 <span class="op">=</span> glm_result.predict(X1)</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Individual and average treatment effects</span></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>individual_effects <span class="op">=</span> y_hat_1 <span class="op">-</span> y_hat_0</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>ate <span class="op">=</span> individual_effects.mean()</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Avg predicted patents — no Blueprinty  : </span><span class="sc">{</span>y_hat_0<span class="sc">.</span>mean()<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Avg predicted patents — with Blueprinty: </span><span class="sc">{</span>y_hat_1<span class="sc">.</span>mean()<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Average Treatment Effect (ATE)         : </span><span class="sc">{</span>ate<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Percentage lift                         : </span><span class="sc">{</span>ate <span class="op">/</span> y_hat_0<span class="sc">.</span>mean() <span class="op">*</span> <span class="dv">100</span><span class="sc">:.1f}</span><span class="ss">%"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Avg predicted patents — no Blueprinty  : 3.4362
Avg predicted patents — with Blueprinty: 4.2290
Average Treatment Effect (ATE)         : 0.7928
Percentage lift                         : 23.1%</code></pre>
</div>
</div>
<div id="cell-fig-counterfactual" class="cell" data-execution_count="13">
<div class="cell-output cell-output-display">
<div id="fig-counterfactual" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-counterfactual-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-counterfactual-output-1.png" width="1139" height="416" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-counterfactual-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Left: distribution of individual treatment effects (ŷ₁ − ŷ₀) across all 1,500 firms. Right: scatter of counterfactual predicted patents — each firm’s prediction under the two scenarios. All points lie above the diagonal, confirming a universally positive estimated effect.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="the-bottom-line" class="level3">
<h3 class="anchored" data-anchor-id="the-bottom-line">The Bottom Line</h3>
<p>Holding firm age and regional location fixed at their observed values for each of the 1,500 firms in the dataset, the model predicts that <strong>using Blueprinty’s software is associated with approximately 0.79 additional patents over five years</strong> compared to not using it. Against a non-customer baseline of roughly 3.47 patents, this represents a <strong>23% increase in patent output</strong> — a commercially meaningful effect if it reflects a real causal relationship.</p>
</section>
<section id="what-this-analysis-does-and-does-not-establish" class="level3">
<h3 class="anchored" data-anchor-id="what-this-analysis-does-and-does-not-establish">What This Analysis Does and Does Not Establish</h3>
<p>This result deserves careful interpretation. Several important caveats apply:</p>
<ol type="1">
<li><p><strong>This is an observational study, not a randomized experiment.</strong> We did not randomly assign firms to use Blueprinty’s software. The regression controls for firm age and region, but there may be unmeasured differences between customers and non-customers — R&amp;D budget, engineering team size, prior patenting history, firm culture around intellectual property — that could partially or fully explain the gap. In the language of causal inference, we cannot rule out <strong>unobserved confounding</strong>.</p></li>
<li><p><strong>The evidence is strong and survives the most obvious controls.</strong> The customer coefficient is large (23% lift), highly significant (p &lt; 0.001, z = 6.72), and robust to conditioning on the two confounders (age and region) that were most obviously different between groups. The 95% CI [0.147, 0.268] is entirely positive.</p></li>
<li><p><strong>A proper causal study would require more.</strong> A randomized trial — where firms are randomly assigned to Blueprinty versus a control condition — would cleanly identify the causal effect. Alternatively, a natural experiment (e.g., staggered regional rollout) or an instrumental variables approach could strengthen causal inference from observational data.</p></li>
</ol>
<p><strong>In summary:</strong> the data provide strong, statistically significant evidence that Blueprinty customers patent at higher rates than otherwise-comparable non-customers. The estimated effect of roughly <strong>+0.79 patents per five-year window (23% lift)</strong> is consistent with Blueprinty’s marketing claims. A careful business-facing statement would be: <em>“Firms using our software are associated with 23% more patents than similar firms that don’t, after controlling for age and geography. This is compelling suggestive evidence of software value, though a randomized study would be needed to establish causation definitively.”</em></p>


<!-- -->

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Does Blueprinty's Software Actually Help Engineers Win More Patents?"</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="an">subtitle:</span><span class="co"> "A Step-by-Step Guide to Poisson Regression via Maximum Likelihood Estimation"</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Jihee Yoon"</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> today</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span><span class="co"> [MLE, Poisson Regression, Marketing Analytics]</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "We walk through the full MLE recipe — deriving the likelihood, coding it from scratch, maximizing it numerically, and translating the results into a plain-English business answer."</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a><span class="co">    toc-depth: 3</span></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a><span class="co">    toc-title: "Contents"</span></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a><span class="co">    theme: flatly</span></span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a><span class="co">    highlight-style: github</span></span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a><span class="co">    fig-width: 9</span></span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a><span class="co">    fig-height: 5</span></span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a><span class="an">execute:</span></span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a><span class="co">  warning: false</span></span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a><span class="co">  message: false</span></span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-26"><a href="#cb12-26" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb12-27"><a href="#cb12-27" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb12-28"><a href="#cb12-28" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb12-29"><a href="#cb12-29" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb12-30"><a href="#cb12-30" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb12-31"><a href="#cb12-31" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.patches <span class="im">as</span> mpatches</span>
<span id="cb12-32"><a href="#cb12-32" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> optimize, special</span>
<span id="cb12-33"><a href="#cb12-33" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb12-34"><a href="#cb12-34" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> IPython.display <span class="im">import</span> display, HTML</span>
<span id="cb12-35"><a href="#cb12-35" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb12-36"><a href="#cb12-36" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">"ignore"</span>)</span>
<span id="cb12-37"><a href="#cb12-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-38"><a href="#cb12-38" aria-hidden="true" tabindex="-1"></a>BLUE   <span class="op">=</span> <span class="st">"#3A7EC6"</span></span>
<span id="cb12-39"><a href="#cb12-39" aria-hidden="true" tabindex="-1"></a>ORANGE <span class="op">=</span> <span class="st">"#E87040"</span></span>
<span id="cb12-40"><a href="#cb12-40" aria-hidden="true" tabindex="-1"></a>GRAY   <span class="op">=</span> <span class="st">"#8D99AE"</span></span>
<span id="cb12-41"><a href="#cb12-41" aria-hidden="true" tabindex="-1"></a>GREEN  <span class="op">=</span> <span class="st">"#2DC653"</span></span>
<span id="cb12-42"><a href="#cb12-42" aria-hidden="true" tabindex="-1"></a>LIGHT  <span class="op">=</span> <span class="st">"#F4F6F9"</span></span>
<span id="cb12-43"><a href="#cb12-43" aria-hidden="true" tabindex="-1"></a>RED    <span class="op">=</span> <span class="st">"#C0392B"</span></span>
<span id="cb12-44"><a href="#cb12-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-45"><a href="#cb12-45" aria-hidden="true" tabindex="-1"></a>plt.rcParams.update({</span>
<span id="cb12-46"><a href="#cb12-46" aria-hidden="true" tabindex="-1"></a>    <span class="st">"figure.facecolor"</span>:  <span class="st">"white"</span>,</span>
<span id="cb12-47"><a href="#cb12-47" aria-hidden="true" tabindex="-1"></a>    <span class="st">"axes.facecolor"</span>:    <span class="st">"#FAFBFC"</span>,</span>
<span id="cb12-48"><a href="#cb12-48" aria-hidden="true" tabindex="-1"></a>    <span class="st">"axes.spines.top"</span>:   <span class="va">False</span>,</span>
<span id="cb12-49"><a href="#cb12-49" aria-hidden="true" tabindex="-1"></a>    <span class="st">"axes.spines.right"</span>: <span class="va">False</span>,</span>
<span id="cb12-50"><a href="#cb12-50" aria-hidden="true" tabindex="-1"></a>    <span class="st">"axes.grid"</span>:         <span class="va">True</span>,</span>
<span id="cb12-51"><a href="#cb12-51" aria-hidden="true" tabindex="-1"></a>    <span class="st">"grid.alpha"</span>:        <span class="fl">0.35</span>,</span>
<span id="cb12-52"><a href="#cb12-52" aria-hidden="true" tabindex="-1"></a>    <span class="st">"grid.linestyle"</span>:    <span class="st">"--"</span>,</span>
<span id="cb12-53"><a href="#cb12-53" aria-hidden="true" tabindex="-1"></a>    <span class="st">"font.family"</span>:       <span class="st">"sans-serif"</span>,</span>
<span id="cb12-54"><a href="#cb12-54" aria-hidden="true" tabindex="-1"></a>    <span class="st">"font.size"</span>:         <span class="dv">11</span>,</span>
<span id="cb12-55"><a href="#cb12-55" aria-hidden="true" tabindex="-1"></a>    <span class="st">"axes.titlesize"</span>:    <span class="dv">13</span>,</span>
<span id="cb12-56"><a href="#cb12-56" aria-hidden="true" tabindex="-1"></a>    <span class="st">"axes.titleweight"</span>:  <span class="st">"bold"</span>,</span>
<span id="cb12-57"><a href="#cb12-57" aria-hidden="true" tabindex="-1"></a>    <span class="st">"axes.labelsize"</span>:    <span class="dv">11</span>,</span>
<span id="cb12-58"><a href="#cb12-58" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb12-59"><a href="#cb12-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-60"><a href="#cb12-60" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">"blueprinty.csv"</span>)</span>
<span id="cb12-61"><a href="#cb12-61" aria-hidden="true" tabindex="-1"></a>Y  <span class="op">=</span> df[<span class="st">"patents"</span>].values</span>
<span id="cb12-62"><a href="#cb12-62" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb12-63"><a href="#cb12-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-64"><a href="#cb12-64" aria-hidden="true" tabindex="-1"></a><span class="fu">## Introduction</span></span>
<span id="cb12-65"><a href="#cb12-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-66"><a href="#cb12-66" aria-hidden="true" tabindex="-1"></a>Every software company eventually faces the same hard question: *does our product actually work?* For **Blueprinty** — a firm that builds specialized patent-drafting software for engineering companies — the stakes are real. Their marketing team wants to claim that firms using Blueprinty's platform win more patents. And at first glance, the numbers look encouraging: customers average **4.13 patents** over five years, versus **3.47** for non-customers. That's a gap of about 0.66 patents, or roughly 19%.</span>
<span id="cb12-67"><a href="#cb12-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-68"><a href="#cb12-68" aria-hidden="true" tabindex="-1"></a>But a raw comparison is not enough, and here's why: **Blueprinty's customers are not a random sample of engineering firms.** A company that invests in specialized patent software is probably already more sophisticated, better resourced, or more patent-active than a typical firm. Any raw difference in patent counts could simply reflect *who buys the software* rather than *what the software does*. This is the classic problem of **selection bias** in observational data.</span>
<span id="cb12-69"><a href="#cb12-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-70"><a href="#cb12-70" aria-hidden="true" tabindex="-1"></a>To answer the question properly, we need a regression model — something that holds firm characteristics constant while estimating the customer effect in isolation. Because the outcome variable (patents over five years) is a non-negative integer count, the **Poisson distribution** is the natural statistical model. We will estimate it by **Maximum Likelihood Estimation (MLE)**, deriving the likelihood from first principles, coding it up by hand, maximizing it numerically, and finally checking our work against a standard GLM.</span>
<span id="cb12-71"><a href="#cb12-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-72"><a href="#cb12-72" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb12-73"><a href="#cb12-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-74"><a href="#cb12-74" aria-hidden="true" tabindex="-1"></a><span class="fu">## Exploring the Data</span></span>
<span id="cb12-75"><a href="#cb12-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-76"><a href="#cb12-76" aria-hidden="true" tabindex="-1"></a>Blueprinty provided data on **1,500 mature (non-startup) engineering firms**. Each row records:</span>
<span id="cb12-77"><a href="#cb12-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-78"><a href="#cb12-78" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`patents`</span> — number of patents awarded over the past five years</span>
<span id="cb12-79"><a href="#cb12-79" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`age`</span> — years since the firm was incorporated</span>
<span id="cb12-80"><a href="#cb12-80" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`region`</span> — U.S. geographic region (Northeast, Midwest, South, Southwest, Northwest)</span>
<span id="cb12-81"><a href="#cb12-81" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`iscustomer`</span> — 1 if the firm uses Blueprinty's software, 0 otherwise</span>
<span id="cb12-82"><a href="#cb12-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-83"><a href="#cb12-83" aria-hidden="true" tabindex="-1"></a>About **32% of firms (481 out of 1,500) are Blueprinty customers.**</span>
<span id="cb12-84"><a href="#cb12-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-85"><a href="#cb12-85" aria-hidden="true" tabindex="-1"></a><span class="fu">### Patent Counts by Customer Status</span></span>
<span id="cb12-86"><a href="#cb12-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-87"><a href="#cb12-87" aria-hidden="true" tabindex="-1"></a>The first thing to look at is how patent counts differ between customers and non-customers.</span>
<span id="cb12-88"><a href="#cb12-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-91"><a href="#cb12-91" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb12-92"><a href="#cb12-92" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-patents-hist</span></span>
<span id="cb12-93"><a href="#cb12-93" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Histograms of five-year patent counts for customers vs. non-customers. Both distributions are right-skewed — a small number of firms are prolific patenters. The customer distribution is shifted noticeably to the right."</span></span>
<span id="cb12-94"><a href="#cb12-94" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb12-95"><a href="#cb12-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-96"><a href="#cb12-96" aria-hidden="true" tabindex="-1"></a>cust    <span class="op">=</span> df[df.iscustomer <span class="op">==</span> <span class="dv">1</span>]</span>
<span id="cb12-97"><a href="#cb12-97" aria-hidden="true" tabindex="-1"></a>noncust <span class="op">=</span> df[df.iscustomer <span class="op">==</span> <span class="dv">0</span>]</span>
<span id="cb12-98"><a href="#cb12-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-99"><a href="#cb12-99" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">11</span>, <span class="fl">4.5</span>), sharey<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb12-100"><a href="#cb12-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-101"><a href="#cb12-101" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, sub, label, color <span class="kw">in</span> <span class="bu">zip</span>(</span>
<span id="cb12-102"><a href="#cb12-102" aria-hidden="true" tabindex="-1"></a>    axes,</span>
<span id="cb12-103"><a href="#cb12-103" aria-hidden="true" tabindex="-1"></a>    [noncust, cust],</span>
<span id="cb12-104"><a href="#cb12-104" aria-hidden="true" tabindex="-1"></a>    [<span class="st">"Non-Customers  (n = 1,019)"</span>, <span class="st">"Customers  (n = 481)"</span>],</span>
<span id="cb12-105"><a href="#cb12-105" aria-hidden="true" tabindex="-1"></a>    [GRAY, BLUE],</span>
<span id="cb12-106"><a href="#cb12-106" aria-hidden="true" tabindex="-1"></a>):</span>
<span id="cb12-107"><a href="#cb12-107" aria-hidden="true" tabindex="-1"></a>    mean_val <span class="op">=</span> sub.patents.mean()</span>
<span id="cb12-108"><a href="#cb12-108" aria-hidden="true" tabindex="-1"></a>    ax.hist(sub.patents, bins<span class="op">=</span><span class="bu">range</span>(<span class="dv">0</span>, <span class="dv">18</span>), color<span class="op">=</span>color, edgecolor<span class="op">=</span><span class="st">"white"</span>,</span>
<span id="cb12-109"><a href="#cb12-109" aria-hidden="true" tabindex="-1"></a>            linewidth<span class="op">=</span><span class="fl">0.7</span>, alpha<span class="op">=</span><span class="fl">0.85</span>, density<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb12-110"><a href="#cb12-110" aria-hidden="true" tabindex="-1"></a>    ax.axvline(mean_val, color<span class="op">=</span>RED, lw<span class="op">=</span><span class="fl">2.2</span>, ls<span class="op">=</span><span class="st">"--"</span>,</span>
<span id="cb12-111"><a href="#cb12-111" aria-hidden="true" tabindex="-1"></a>               label<span class="op">=</span><span class="ss">f"Mean = </span><span class="sc">{</span>mean_val<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb12-112"><a href="#cb12-112" aria-hidden="true" tabindex="-1"></a>    ax.set_title(label, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb12-113"><a href="#cb12-113" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="st">"Patents Awarded (5 years)"</span>)</span>
<span id="cb12-114"><a href="#cb12-114" aria-hidden="true" tabindex="-1"></a>    ax.set_xlim(<span class="op">-</span><span class="fl">0.5</span>, <span class="dv">17</span>)</span>
<span id="cb12-115"><a href="#cb12-115" aria-hidden="true" tabindex="-1"></a>    ax.legend(frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb12-116"><a href="#cb12-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-117"><a href="#cb12-117" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">"Density"</span>)</span>
<span id="cb12-118"><a href="#cb12-118" aria-hidden="true" tabindex="-1"></a>fig.suptitle(<span class="st">"Patent Count Distribution by Customer Status"</span>,</span>
<span id="cb12-119"><a href="#cb12-119" aria-hidden="true" tabindex="-1"></a>             fontsize<span class="op">=</span><span class="dv">14</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>, y<span class="op">=</span><span class="fl">1.02</span>)</span>
<span id="cb12-120"><a href="#cb12-120" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb12-121"><a href="#cb12-121" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb12-122"><a href="#cb12-122" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb12-123"><a href="#cb12-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-124"><a href="#cb12-124" aria-hidden="true" tabindex="-1"></a>Both distributions are right-skewed — most firms earn between 1 and 6 patents, but a handful earn 10 or more. This asymmetry is typical of count data and is one reason the Normal distribution is a poor fit here (it would allow negative predictions). The customer distribution is visibly shifted to the right, suggesting higher patent output. But as we'll see next, customers also differ from non-customers in ways that could independently explain that difference.</span>
<span id="cb12-125"><a href="#cb12-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-126"><a href="#cb12-126" aria-hidden="true" tabindex="-1"></a><span class="fu">### Are Customers Systematically Different?</span></span>
<span id="cb12-127"><a href="#cb12-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-128"><a href="#cb12-128" aria-hidden="true" tabindex="-1"></a>If Blueprinty's customers were randomly selected from the population of firms, we could trust the raw comparison. They're not. Let's check two key dimensions: firm age and regional location.</span>
<span id="cb12-129"><a href="#cb12-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-132"><a href="#cb12-132" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb12-133"><a href="#cb12-133" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-age-region</span></span>
<span id="cb12-134"><a href="#cb12-134" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Left: firm age distributions by customer status — customers are slightly older on average. Right: regional composition — customers are heavily concentrated in the Northeast."</span></span>
<span id="cb12-135"><a href="#cb12-135" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb12-136"><a href="#cb12-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-137"><a href="#cb12-137" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="fl">4.5</span>))</span>
<span id="cb12-138"><a href="#cb12-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-139"><a href="#cb12-139" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> axes[<span class="dv">0</span>]</span>
<span id="cb12-140"><a href="#cb12-140" aria-hidden="true" tabindex="-1"></a>bins <span class="op">=</span> np.arange(<span class="dv">5</span>, <span class="dv">55</span>, <span class="dv">3</span>)</span>
<span id="cb12-141"><a href="#cb12-141" aria-hidden="true" tabindex="-1"></a>ax.hist(noncust.age, bins<span class="op">=</span>bins, color<span class="op">=</span>GRAY, alpha<span class="op">=</span><span class="fl">0.7</span>,</span>
<span id="cb12-142"><a href="#cb12-142" aria-hidden="true" tabindex="-1"></a>        edgecolor<span class="op">=</span><span class="st">"white"</span>, density<span class="op">=</span><span class="va">True</span>, label<span class="op">=</span><span class="ss">f"Non-Customer (μ = </span><span class="sc">{</span>noncust<span class="sc">.</span>age<span class="sc">.</span>mean()<span class="sc">:.1f}</span><span class="ss"> yrs)"</span>)</span>
<span id="cb12-143"><a href="#cb12-143" aria-hidden="true" tabindex="-1"></a>ax.hist(cust.age,    bins<span class="op">=</span>bins, color<span class="op">=</span>BLUE, alpha<span class="op">=</span><span class="fl">0.7</span>,</span>
<span id="cb12-144"><a href="#cb12-144" aria-hidden="true" tabindex="-1"></a>        edgecolor<span class="op">=</span><span class="st">"white"</span>, density<span class="op">=</span><span class="va">True</span>, label<span class="op">=</span><span class="ss">f"Customer (μ = </span><span class="sc">{</span>cust<span class="sc">.</span>age<span class="sc">.</span>mean()<span class="sc">:.1f}</span><span class="ss"> yrs)"</span>)</span>
<span id="cb12-145"><a href="#cb12-145" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"Firm Age (years)"</span>)</span>
<span id="cb12-146"><a href="#cb12-146" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"Density"</span>)</span>
<span id="cb12-147"><a href="#cb12-147" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Firm Age by Customer Status"</span>)</span>
<span id="cb12-148"><a href="#cb12-148" aria-hidden="true" tabindex="-1"></a>ax.legend(frameon<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb12-149"><a href="#cb12-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-150"><a href="#cb12-150" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> axes[<span class="dv">1</span>]</span>
<span id="cb12-151"><a href="#cb12-151" aria-hidden="true" tabindex="-1"></a>regions <span class="op">=</span> [<span class="st">"Northeast"</span>, <span class="st">"Southwest"</span>, <span class="st">"Midwest"</span>, <span class="st">"South"</span>, <span class="st">"Northwest"</span>]</span>
<span id="cb12-152"><a href="#cb12-152" aria-hidden="true" tabindex="-1"></a>nc_pct <span class="op">=</span> noncust.region.value_counts(normalize<span class="op">=</span><span class="va">True</span>).reindex(regions).fillna(<span class="dv">0</span>) <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb12-153"><a href="#cb12-153" aria-hidden="true" tabindex="-1"></a>cu_pct <span class="op">=</span> cust.region.value_counts(normalize<span class="op">=</span><span class="va">True</span>).reindex(regions).fillna(<span class="dv">0</span>) <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb12-154"><a href="#cb12-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-155"><a href="#cb12-155" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.arange(<span class="bu">len</span>(regions))</span>
<span id="cb12-156"><a href="#cb12-156" aria-hidden="true" tabindex="-1"></a>w <span class="op">=</span> <span class="fl">0.35</span></span>
<span id="cb12-157"><a href="#cb12-157" aria-hidden="true" tabindex="-1"></a>ax.bar(x <span class="op">-</span> w<span class="op">/</span><span class="dv">2</span>, nc_pct.values, w, color<span class="op">=</span>GRAY, alpha<span class="op">=</span><span class="fl">0.85</span>,</span>
<span id="cb12-158"><a href="#cb12-158" aria-hidden="true" tabindex="-1"></a>       edgecolor<span class="op">=</span><span class="st">"white"</span>, label<span class="op">=</span><span class="st">"Non-Customer"</span>)</span>
<span id="cb12-159"><a href="#cb12-159" aria-hidden="true" tabindex="-1"></a>ax.bar(x <span class="op">+</span> w<span class="op">/</span><span class="dv">2</span>, cu_pct.values, w, color<span class="op">=</span>BLUE, alpha<span class="op">=</span><span class="fl">0.85</span>,</span>
<span id="cb12-160"><a href="#cb12-160" aria-hidden="true" tabindex="-1"></a>       edgecolor<span class="op">=</span><span class="st">"white"</span>, label<span class="op">=</span><span class="st">"Customer"</span>)</span>
<span id="cb12-161"><a href="#cb12-161" aria-hidden="true" tabindex="-1"></a>ax.set_xticks(x)</span>
<span id="cb12-162"><a href="#cb12-162" aria-hidden="true" tabindex="-1"></a>ax.set_xticklabels(regions, rotation<span class="op">=</span><span class="dv">20</span>, ha<span class="op">=</span><span class="st">"right"</span>)</span>
<span id="cb12-163"><a href="#cb12-163" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"Share of Group (%)"</span>)</span>
<span id="cb12-164"><a href="#cb12-164" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Regional Composition by Customer Status"</span>)</span>
<span id="cb12-165"><a href="#cb12-165" aria-hidden="true" tabindex="-1"></a>ax.legend(frameon<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb12-166"><a href="#cb12-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-167"><a href="#cb12-167" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb12-168"><a href="#cb12-168" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb12-169"><a href="#cb12-169" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb12-170"><a href="#cb12-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-171"><a href="#cb12-171" aria-hidden="true" tabindex="-1"></a>Two patterns stand out and both matter for the analysis:</span>
<span id="cb12-172"><a href="#cb12-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-173"><a href="#cb12-173" aria-hidden="true" tabindex="-1"></a>**Age:** Customer firms average **26.9 years** old versus **26.1 years** for non-customers — a small but nonzero difference. More importantly, the age-patenting relationship appears nonlinear: very young firms are still building capability, and very old firms may have mature product lines with little left to patent. We'll account for this with an age-squared term in the regression.</span>
<span id="cb12-174"><a href="#cb12-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-175"><a href="#cb12-175" aria-hidden="true" tabindex="-1"></a>**Region:** This is the bigger concern. A striking **68% of Blueprinty's customers are in the Northeast**, compared to only 27% of non-customers. The Northeast is a well-known hub for research-intensive engineering firms, and these firms may patent at higher rates for reasons entirely unrelated to software. If we ignored region, we'd risk attributing a "Northeast effect" to Blueprinty's product. Controlling for region in the regression is therefore essential.</span>
<span id="cb12-176"><a href="#cb12-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-177"><a href="#cb12-177" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb12-178"><a href="#cb12-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-179"><a href="#cb12-179" aria-hidden="true" tabindex="-1"></a><span class="fu">## A Simple Poisson Model via Maximum Likelihood</span></span>
<span id="cb12-180"><a href="#cb12-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-181"><a href="#cb12-181" aria-hidden="true" tabindex="-1"></a><span class="fu">### Why Poisson?</span></span>
<span id="cb12-182"><a href="#cb12-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-183"><a href="#cb12-183" aria-hidden="true" tabindex="-1"></a>The outcome we're modeling — patents awarded over five years — is a **count variable**: non-negative, integer-valued, and right-skewed. The Normal distribution is a poor fit because it places probability on negative values and assumes symmetric errors. The **Poisson distribution** is purpose-built for this type of data.</span>
<span id="cb12-184"><a href="#cb12-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-185"><a href="#cb12-185" aria-hidden="true" tabindex="-1"></a>A random variable $Y$ follows $\text{Poisson}(\lambda)$ if:</span>
<span id="cb12-186"><a href="#cb12-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-187"><a href="#cb12-187" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb12-188"><a href="#cb12-188" aria-hidden="true" tabindex="-1"></a>f(Y \mid \lambda) = \frac{e^{-\lambda}\,\lambda^{Y}}{Y!}, \qquad Y = 0, 1, 2, \ldots</span>
<span id="cb12-189"><a href="#cb12-189" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb12-190"><a href="#cb12-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-191"><a href="#cb12-191" aria-hidden="true" tabindex="-1"></a>The single parameter $\lambda &gt; 0$ controls both the mean and the variance: $E<span class="co">[</span><span class="ot">Y</span><span class="co">]</span> = \text{Var}(Y) = \lambda$. Intuitively, $\lambda$ is the expected number of patents a firm earns in the observation window.</span>
<span id="cb12-192"><a href="#cb12-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-193"><a href="#cb12-193" aria-hidden="true" tabindex="-1"></a><span class="fu">### Deriving the Log-Likelihood</span></span>
<span id="cb12-194"><a href="#cb12-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-195"><a href="#cb12-195" aria-hidden="true" tabindex="-1"></a>Given $n$ independent observations $Y_1, \ldots, Y_n$, the **joint likelihood** is the product of each firm's probability:</span>
<span id="cb12-196"><a href="#cb12-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-197"><a href="#cb12-197" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb12-198"><a href="#cb12-198" aria-hidden="true" tabindex="-1"></a>L(\lambda \mid \mathbf{Y}) = \prod_{i=1}^{n} \frac{e^{-\lambda}\,\lambda^{Y_i}}{Y_i!}</span>
<span id="cb12-199"><a href="#cb12-199" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb12-200"><a href="#cb12-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-201"><a href="#cb12-201" aria-hidden="true" tabindex="-1"></a>Taking the log (which preserves the maximizer since log is monotone):</span>
<span id="cb12-202"><a href="#cb12-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-203"><a href="#cb12-203" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb12-204"><a href="#cb12-204" aria-hidden="true" tabindex="-1"></a>\ell(\lambda) = \log L(\lambda \mid \mathbf{Y}) = \sum_{i=1}^{n} \left<span class="co">[</span><span class="ot"> Y_i \log\lambda - \lambda - \log(Y_i!) \right</span><span class="co">]</span></span>
<span id="cb12-205"><a href="#cb12-205" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb12-206"><a href="#cb12-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-207"><a href="#cb12-207" aria-hidden="true" tabindex="-1"></a>Simplifying by pulling out $\lambda$-independent terms:</span>
<span id="cb12-208"><a href="#cb12-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-209"><a href="#cb12-209" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb12-210"><a href="#cb12-210" aria-hidden="true" tabindex="-1"></a>\ell(\lambda) = \underbrace{\left(\sum_{i=1}^{n} Y_i\right)}_{\text{sufficient statistic}} \log\lambda \;-\; n\lambda \;-\; \underbrace{\sum_{i=1}^{n} \log(Y_i!)}_{\text{constant w.r.t. } \lambda}</span>
<span id="cb12-211"><a href="#cb12-211" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb12-212"><a href="#cb12-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-213"><a href="#cb12-213" aria-hidden="true" tabindex="-1"></a>**Analytic MLE:** Setting $\frac{d\ell}{d\lambda} = 0$:</span>
<span id="cb12-214"><a href="#cb12-214" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-215"><a href="#cb12-215" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb12-216"><a href="#cb12-216" aria-hidden="true" tabindex="-1"></a>\frac{d\ell}{d\lambda} = \frac{\sum_i Y_i}{\lambda} - n = 0 \quad\Longrightarrow\quad \hat{\lambda}_{\text{MLE}} = \frac{\sum_i Y_i}{n} = \bar{Y}</span>
<span id="cb12-217"><a href="#cb12-217" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb12-218"><a href="#cb12-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-219"><a href="#cb12-219" aria-hidden="true" tabindex="-1"></a>This is an elegant result: the MLE is simply the sample mean. It "feels right" because $\lambda = E<span class="co">[</span><span class="ot">Y</span><span class="co">]</span>$ for the Poisson, so we're estimating the mean with the mean.</span>
<span id="cb12-220"><a href="#cb12-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-221"><a href="#cb12-221" aria-hidden="true" tabindex="-1"></a><span class="fu">### Coding and Plotting the Log-Likelihood</span></span>
<span id="cb12-222"><a href="#cb12-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-225"><a href="#cb12-225" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb12-226"><a href="#cb12-226" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb12-227"><a href="#cb12-227" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-loglik</span></span>
<span id="cb12-228"><a href="#cb12-228" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "The Poisson log-likelihood as a function of λ. The curve is concave (ensuring a unique maximum), and the MLE sits exactly at the sample mean. Points far from the mean make the data exponentially less probable."</span></span>
<span id="cb12-229"><a href="#cb12-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-230"><a href="#cb12-230" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> poisson_loglik(lam, Y):</span>
<span id="cb12-231"><a href="#cb12-231" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Log-likelihood of Poisson(lambda) for observed count vector Y."""</span></span>
<span id="cb12-232"><a href="#cb12-232" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> lam <span class="op">&lt;=</span> <span class="dv">0</span>:</span>
<span id="cb12-233"><a href="#cb12-233" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="op">-</span>np.inf</span>
<span id="cb12-234"><a href="#cb12-234" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.<span class="bu">sum</span>(Y <span class="op">*</span> np.log(lam) <span class="op">-</span> lam) <span class="op">-</span> np.<span class="bu">sum</span>(special.gammaln(Y <span class="op">+</span> <span class="dv">1</span>))</span>
<span id="cb12-235"><a href="#cb12-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-236"><a href="#cb12-236" aria-hidden="true" tabindex="-1"></a>lam_grid <span class="op">=</span> np.linspace(<span class="fl">2.5</span>, <span class="fl">5.0</span>, <span class="dv">500</span>)</span>
<span id="cb12-237"><a href="#cb12-237" aria-hidden="true" tabindex="-1"></a>ll_vals  <span class="op">=</span> [poisson_loglik(lam, Y) <span class="cf">for</span> lam <span class="kw">in</span> lam_grid]</span>
<span id="cb12-238"><a href="#cb12-238" aria-hidden="true" tabindex="-1"></a>y_mean   <span class="op">=</span> Y.mean()</span>
<span id="cb12-239"><a href="#cb12-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-240"><a href="#cb12-240" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="fl">4.2</span>))</span>
<span id="cb12-241"><a href="#cb12-241" aria-hidden="true" tabindex="-1"></a>ax.plot(lam_grid, ll_vals, color<span class="op">=</span>BLUE, lw<span class="op">=</span><span class="fl">2.5</span>, label<span class="op">=</span><span class="st">"Log-likelihood  ℓ(λ)"</span>)</span>
<span id="cb12-242"><a href="#cb12-242" aria-hidden="true" tabindex="-1"></a>ax.axvline(y_mean, color<span class="op">=</span>RED, lw<span class="op">=</span><span class="dv">2</span>, ls<span class="op">=</span><span class="st">"--"</span>,</span>
<span id="cb12-243"><a href="#cb12-243" aria-hidden="true" tabindex="-1"></a>           label<span class="op">=</span><span class="ss">f"MLE = $</span><span class="ch">\\</span><span class="ss">bar</span><span class="ch">{{</span><span class="ss">Y</span><span class="ch">}}</span><span class="ss">$ = </span><span class="sc">{</span>y_mean<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb12-244"><a href="#cb12-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-245"><a href="#cb12-245" aria-hidden="true" tabindex="-1"></a>peak_ll <span class="op">=</span> poisson_loglik(y_mean, Y)</span>
<span id="cb12-246"><a href="#cb12-246" aria-hidden="true" tabindex="-1"></a>ax.annotate(<span class="ss">f"Peak at λ = </span><span class="sc">{</span>y_mean<span class="sc">:.3f}</span><span class="ss">"</span>,</span>
<span id="cb12-247"><a href="#cb12-247" aria-hidden="true" tabindex="-1"></a>            xy<span class="op">=</span>(y_mean, peak_ll),</span>
<span id="cb12-248"><a href="#cb12-248" aria-hidden="true" tabindex="-1"></a>            xytext<span class="op">=</span>(y_mean <span class="op">+</span> <span class="fl">0.3</span>, peak_ll <span class="op">-</span> <span class="dv">15</span>),</span>
<span id="cb12-249"><a href="#cb12-249" aria-hidden="true" tabindex="-1"></a>            arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">"-&gt;"</span>, color<span class="op">=</span><span class="st">"black"</span>),</span>
<span id="cb12-250"><a href="#cb12-250" aria-hidden="true" tabindex="-1"></a>            fontsize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb12-251"><a href="#cb12-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-252"><a href="#cb12-252" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"λ  (expected patent count per firm)"</span>)</span>
<span id="cb12-253"><a href="#cb12-253" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"Log-likelihood  ℓ(λ)"</span>)</span>
<span id="cb12-254"><a href="#cb12-254" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Poisson Log-Likelihood: Visualizing the MLE"</span>)</span>
<span id="cb12-255"><a href="#cb12-255" aria-hidden="true" tabindex="-1"></a>ax.legend(frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="dv">11</span>)</span>
<span id="cb12-256"><a href="#cb12-256" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb12-257"><a href="#cb12-257" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb12-258"><a href="#cb12-258" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb12-259"><a href="#cb12-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-260"><a href="#cb12-260" aria-hidden="true" tabindex="-1"></a>The log-likelihood curve is **concave** with a single, well-defined peak — this guarantees the MLE is unique and globally optimal. The curve rises steeply as $\lambda$ approaches $\bar{Y} = 3.685$ from below, then falls off as $\lambda$ overshoots. Points far from the mean make the observed data exponentially less probable under the Poisson model.</span>
<span id="cb12-261"><a href="#cb12-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-262"><a href="#cb12-262" aria-hidden="true" tabindex="-1"></a><span class="fu">### Numerical Verification</span></span>
<span id="cb12-263"><a href="#cb12-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-266"><a href="#cb12-266" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb12-267"><a href="#cb12-267" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb12-268"><a href="#cb12-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-269"><a href="#cb12-269" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> optimize.minimize_scalar(</span>
<span id="cb12-270"><a href="#cb12-270" aria-hidden="true" tabindex="-1"></a>    fun    <span class="op">=</span> <span class="kw">lambda</span> lam: <span class="op">-</span>poisson_loglik(lam, Y),</span>
<span id="cb12-271"><a href="#cb12-271" aria-hidden="true" tabindex="-1"></a>    bounds <span class="op">=</span> (<span class="fl">0.5</span>, <span class="fl">15.0</span>),</span>
<span id="cb12-272"><a href="#cb12-272" aria-hidden="true" tabindex="-1"></a>    method <span class="op">=</span> <span class="st">"bounded"</span></span>
<span id="cb12-273"><a href="#cb12-273" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-274"><a href="#cb12-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-275"><a href="#cb12-275" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Numerical MLE  λ̂  =  </span><span class="sc">{</span>result<span class="sc">.</span>x<span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb12-276"><a href="#cb12-276" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Sample mean    Ȳ  =  </span><span class="sc">{</span>Y<span class="sc">.</span>mean()<span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb12-277"><a href="#cb12-277" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Difference        =  </span><span class="sc">{</span><span class="bu">abs</span>(result.x <span class="op">-</span> Y.mean())<span class="sc">:.2e}</span><span class="ss">"</span>)</span>
<span id="cb12-278"><a href="#cb12-278" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb12-279"><a href="#cb12-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-280"><a href="#cb12-280" aria-hidden="true" tabindex="-1"></a>The numerical optimizer and the closed-form solution agree to six decimal places. The tiny residual difference is just floating-point rounding — not a meaningful discrepancy. This cross-check confirms both that our <span class="in">`poisson_loglik`</span> function is coded correctly and that <span class="in">`scipy.optimize`</span> is converging to the right solution. Any time you derive an analytic result, numerically verifying it is good practice.</span>
<span id="cb12-281"><a href="#cb12-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-282"><a href="#cb12-282" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb12-283"><a href="#cb12-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-284"><a href="#cb12-284" aria-hidden="true" tabindex="-1"></a><span class="fu">## Poisson Regression</span></span>
<span id="cb12-285"><a href="#cb12-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-286"><a href="#cb12-286" aria-hidden="true" tabindex="-1"></a><span class="fu">### Extending the Model to Firm-Level Covariates</span></span>
<span id="cb12-287"><a href="#cb12-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-288"><a href="#cb12-288" aria-hidden="true" tabindex="-1"></a>The simple model assumed every firm has the same expected patent rate $\lambda$. That's clearly wrong — older firms, Northeast firms, and Blueprinty customers all tend to patent more. In **Poisson regression**, we let $\lambda$ vary across firms as a function of their characteristics:</span>
<span id="cb12-289"><a href="#cb12-289" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-290"><a href="#cb12-290" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb12-291"><a href="#cb12-291" aria-hidden="true" tabindex="-1"></a>Y_i \sim \text{Poisson}(\lambda_i), \qquad \lambda_i = \exp<span class="sc">\!</span>\left(X_i'\beta\right)</span>
<span id="cb12-292"><a href="#cb12-292" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb12-293"><a href="#cb12-293" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-294"><a href="#cb12-294" aria-hidden="true" tabindex="-1"></a>The **exponential link** $\exp(\cdot)$ is critical. The linear predictor $X_i'\beta$ can take any real value (positive or negative), but $\lambda_i$ must be strictly positive. Exponentiating maps $\mathbb{R} \to (0, \infty)$ and ensures we never predict a negative patent count. Taking the log of both sides gives $\log(\lambda_i) = X_i'\beta$, which is why Poisson regression is also called a **log-linear model**.</span>
<span id="cb12-295"><a href="#cb12-295" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-296"><a href="#cb12-296" aria-hidden="true" tabindex="-1"></a>The log-likelihood for the full regression model is:</span>
<span id="cb12-297"><a href="#cb12-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-298"><a href="#cb12-298" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb12-299"><a href="#cb12-299" aria-hidden="true" tabindex="-1"></a>\ell(\beta) = \sum_{i=1}^{n} \Bigl<span class="co">[</span><span class="ot"> Y_i\,(X_i'\beta) \;-\; \exp(X_i'\beta) \;-\; \log(Y_i!) \Bigr</span><span class="co">]</span></span>
<span id="cb12-300"><a href="#cb12-300" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb12-301"><a href="#cb12-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-302"><a href="#cb12-302" aria-hidden="true" tabindex="-1"></a><span class="fu">### Constructing the Design Matrix</span></span>
<span id="cb12-303"><a href="#cb12-303" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-306"><a href="#cb12-306" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb12-307"><a href="#cb12-307" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb12-308"><a href="#cb12-308" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-309"><a href="#cb12-309" aria-hidden="true" tabindex="-1"></a><span class="co"># One-hot encode region; drop Midwest as the reference category</span></span>
<span id="cb12-310"><a href="#cb12-310" aria-hidden="true" tabindex="-1"></a>region_dummies <span class="op">=</span> pd.get_dummies(df[<span class="st">"region"</span>], drop_first<span class="op">=</span><span class="va">False</span>, dtype<span class="op">=</span><span class="bu">float</span>)</span>
<span id="cb12-311"><a href="#cb12-311" aria-hidden="true" tabindex="-1"></a>region_dummies <span class="op">=</span> region_dummies.drop(columns<span class="op">=</span>[<span class="st">"Midwest"</span>])</span>
<span id="cb12-312"><a href="#cb12-312" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-313"><a href="#cb12-313" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> pd.DataFrame({</span>
<span id="cb12-314"><a href="#cb12-314" aria-hidden="true" tabindex="-1"></a>    <span class="st">"intercept"</span>:  <span class="fl">1.0</span>,</span>
<span id="cb12-315"><a href="#cb12-315" aria-hidden="true" tabindex="-1"></a>    <span class="st">"age"</span>:        df[<span class="st">"age"</span>],</span>
<span id="cb12-316"><a href="#cb12-316" aria-hidden="true" tabindex="-1"></a>    <span class="st">"age2"</span>:       df[<span class="st">"age"</span>] <span class="op">**</span> <span class="dv">2</span>,</span>
<span id="cb12-317"><a href="#cb12-317" aria-hidden="true" tabindex="-1"></a>    <span class="st">"iscustomer"</span>: df[<span class="st">"iscustomer"</span>].astype(<span class="bu">float</span>),</span>
<span id="cb12-318"><a href="#cb12-318" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb12-319"><a href="#cb12-319" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> pd.concat([X, region_dummies], axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb12-320"><a href="#cb12-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-321"><a href="#cb12-321" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Covariates:"</span>, X.columns.tolist())</span>
<span id="cb12-322"><a href="#cb12-322" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Matrix shape:"</span>, X.shape)</span>
<span id="cb12-323"><a href="#cb12-323" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb12-324"><a href="#cb12-324" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-325"><a href="#cb12-325" aria-hidden="true" tabindex="-1"></a>Two design choices deserve explanation:</span>
<span id="cb12-326"><a href="#cb12-326" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-327"><a href="#cb12-327" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Age-squared:** The relationship between firm age and patent output is almost certainly nonlinear. Young firms are still building R&amp;D capabilities; very old firms may have mature product lines with little new to patent. Including $\text{age}^2$ lets the model capture this concave (inverted-U) pattern. Leaving it out would force a straight-line fit through a curved relationship, biasing all other coefficients.</span>
<span id="cb12-328"><a href="#cb12-328" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-329"><a href="#cb12-329" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Dropping one region (Midwest):** All five region indicators would sum to exactly 1 at every row — which is exactly the intercept column. Including all five causes **perfect multicollinearity**: $X'X$ becomes singular and $\beta$ is unidentifiable. Dropping Midwest makes it the **reference category**; all remaining region coefficients measure the difference in log-rate relative to a Midwestern firm of the same age and customer status.</span>
<span id="cb12-330"><a href="#cb12-330" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-331"><a href="#cb12-331" aria-hidden="true" tabindex="-1"></a><span class="fu">### Coding the Regression Log-Likelihood</span></span>
<span id="cb12-332"><a href="#cb12-332" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-335"><a href="#cb12-335" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb12-336"><a href="#cb12-336" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb12-337"><a href="#cb12-337" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-338"><a href="#cb12-338" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> poisson_reg_loglik(beta, Y, X):</span>
<span id="cb12-339"><a href="#cb12-339" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb12-340"><a href="#cb12-340" aria-hidden="true" tabindex="-1"></a><span class="co">    Log-likelihood for Poisson regression.</span></span>
<span id="cb12-341"><a href="#cb12-341" aria-hidden="true" tabindex="-1"></a><span class="co">    beta : parameter vector (length p)</span></span>
<span id="cb12-342"><a href="#cb12-342" aria-hidden="true" tabindex="-1"></a><span class="co">    Y    : observed counts (length n)</span></span>
<span id="cb12-343"><a href="#cb12-343" aria-hidden="true" tabindex="-1"></a><span class="co">    X    : design matrix (n x p)</span></span>
<span id="cb12-344"><a href="#cb12-344" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb12-345"><a href="#cb12-345" aria-hidden="true" tabindex="-1"></a>    eta     <span class="op">=</span> X <span class="op">@</span> beta                         <span class="co"># linear predictor Xβ</span></span>
<span id="cb12-346"><a href="#cb12-346" aria-hidden="true" tabindex="-1"></a>    lam     <span class="op">=</span> np.exp(eta)                      <span class="co"># λ_i = exp(x_i'β)</span></span>
<span id="cb12-347"><a href="#cb12-347" aria-hidden="true" tabindex="-1"></a>    log_fac <span class="op">=</span> np.<span class="bu">sum</span>(special.gammaln(Y <span class="op">+</span> <span class="dv">1</span>))   <span class="co"># Σ log(Y_i!) — constant</span></span>
<span id="cb12-348"><a href="#cb12-348" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.<span class="bu">sum</span>(Y <span class="op">*</span> eta <span class="op">-</span> lam) <span class="op">-</span> log_fac</span>
<span id="cb12-349"><a href="#cb12-349" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb12-350"><a href="#cb12-350" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-351"><a href="#cb12-351" aria-hidden="true" tabindex="-1"></a><span class="fu">### Finding the MLE with `scipy.optimize`</span></span>
<span id="cb12-352"><a href="#cb12-352" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-355"><a href="#cb12-355" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb12-356"><a href="#cb12-356" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb12-357"><a href="#cb12-357" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-358"><a href="#cb12-358" aria-hidden="true" tabindex="-1"></a>X_arr  <span class="op">=</span> X.values</span>
<span id="cb12-359"><a href="#cb12-359" aria-hidden="true" tabindex="-1"></a>beta0  <span class="op">=</span> np.zeros(X_arr.shape[<span class="dv">1</span>])</span>
<span id="cb12-360"><a href="#cb12-360" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-361"><a href="#cb12-361" aria-hidden="true" tabindex="-1"></a>opt <span class="op">=</span> optimize.minimize(</span>
<span id="cb12-362"><a href="#cb12-362" aria-hidden="true" tabindex="-1"></a>    fun     <span class="op">=</span> <span class="kw">lambda</span> b: <span class="op">-</span>poisson_reg_loglik(b, Y, X_arr),</span>
<span id="cb12-363"><a href="#cb12-363" aria-hidden="true" tabindex="-1"></a>    x0      <span class="op">=</span> beta0,</span>
<span id="cb12-364"><a href="#cb12-364" aria-hidden="true" tabindex="-1"></a>    method  <span class="op">=</span> <span class="st">"BFGS"</span>,</span>
<span id="cb12-365"><a href="#cb12-365" aria-hidden="true" tabindex="-1"></a>    options <span class="op">=</span> {<span class="st">"maxiter"</span>: <span class="dv">3000</span>, <span class="st">"gtol"</span>: <span class="fl">1e-8</span>},</span>
<span id="cb12-366"><a href="#cb12-366" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-367"><a href="#cb12-367" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-368"><a href="#cb12-368" aria-hidden="true" tabindex="-1"></a>beta_hat <span class="op">=</span> opt.x</span>
<span id="cb12-369"><a href="#cb12-369" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-370"><a href="#cb12-370" aria-hidden="true" tabindex="-1"></a><span class="co"># Standard errors via numerical Hessian: SE = sqrt(diag(H^{-1}))</span></span>
<span id="cb12-371"><a href="#cb12-371" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.optimize <span class="im">import</span> approx_fprime</span>
<span id="cb12-372"><a href="#cb12-372" aria-hidden="true" tabindex="-1"></a>eps      <span class="op">=</span> <span class="fl">1e-5</span></span>
<span id="cb12-373"><a href="#cb12-373" aria-hidden="true" tabindex="-1"></a>n_params <span class="op">=</span> <span class="bu">len</span>(beta_hat)</span>
<span id="cb12-374"><a href="#cb12-374" aria-hidden="true" tabindex="-1"></a>H        <span class="op">=</span> np.zeros((n_params, n_params))</span>
<span id="cb12-375"><a href="#cb12-375" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-376"><a href="#cb12-376" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(n_params):</span>
<span id="cb12-377"><a href="#cb12-377" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> grad_i(b, i<span class="op">=</span>i):</span>
<span id="cb12-378"><a href="#cb12-378" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> approx_fprime(b,</span>
<span id="cb12-379"><a href="#cb12-379" aria-hidden="true" tabindex="-1"></a>            <span class="kw">lambda</span> bb: <span class="op">-</span>poisson_reg_loglik(bb, Y, X_arr), eps)[i]</span>
<span id="cb12-380"><a href="#cb12-380" aria-hidden="true" tabindex="-1"></a>    H[i] <span class="op">=</span> approx_fprime(beta_hat, grad_i, eps)</span>
<span id="cb12-381"><a href="#cb12-381" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-382"><a href="#cb12-382" aria-hidden="true" tabindex="-1"></a>se_hat <span class="op">=</span> np.sqrt(np.diag(np.linalg.inv(H)))</span>
<span id="cb12-383"><a href="#cb12-383" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-384"><a href="#cb12-384" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Manual MLE converged:"</span>, opt.success)</span>
<span id="cb12-385"><a href="#cb12-385" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Log-likelihood at MLE:"</span>, <span class="op">-</span>opt.fun)</span>
<span id="cb12-386"><a href="#cb12-386" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb12-387"><a href="#cb12-387" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-388"><a href="#cb12-388" aria-hidden="true" tabindex="-1"></a>The standard errors come from the **observed Fisher information matrix**: $\text{SE}(\hat\beta_j) = \sqrt{<span class="co">[</span><span class="ot">H^{-1}</span><span class="co">]</span>_{jj}}$, where $H$ is the Hessian of the *negative* log-likelihood evaluated at $\hat\beta$. Intuitively, if the log-likelihood is very curved around the peak (large $H$), the MLE is precisely estimated (small SE). If it's nearly flat (small $H$), the data contain little information about $\beta_j$ (large SE).</span>
<span id="cb12-389"><a href="#cb12-389" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-390"><a href="#cb12-390" aria-hidden="true" tabindex="-1"></a><span class="fu">### Results: Manual MLE vs. `statsmodels` GLM</span></span>
<span id="cb12-391"><a href="#cb12-391" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-394"><a href="#cb12-394" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb12-395"><a href="#cb12-395" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb12-396"><a href="#cb12-396" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-397"><a href="#cb12-397" aria-hidden="true" tabindex="-1"></a>glm_result <span class="op">=</span> sm.GLM(Y, X, family<span class="op">=</span>sm.families.Poisson()).fit()</span>
<span id="cb12-398"><a href="#cb12-398" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb12-399"><a href="#cb12-399" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-402"><a href="#cb12-402" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb12-403"><a href="#cb12-403" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb12-404"><a href="#cb12-404" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-405"><a href="#cb12-405" aria-hidden="true" tabindex="-1"></a>coef_names <span class="op">=</span> X.columns.tolist()</span>
<span id="cb12-406"><a href="#cb12-406" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-407"><a href="#cb12-407" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> sig_stars(p):</span>
<span id="cb12-408"><a href="#cb12-408" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> p <span class="op">&lt;</span> <span class="fl">0.001</span>: <span class="cf">return</span> <span class="st">"***"</span></span>
<span id="cb12-409"><a href="#cb12-409" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> p <span class="op">&lt;</span> <span class="fl">0.01</span>:  <span class="cf">return</span> <span class="st">"**"</span></span>
<span id="cb12-410"><a href="#cb12-410" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> p <span class="op">&lt;</span> <span class="fl">0.05</span>:  <span class="cf">return</span> <span class="st">"*"</span></span>
<span id="cb12-411"><a href="#cb12-411" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="st">""</span></span>
<span id="cb12-412"><a href="#cb12-412" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-413"><a href="#cb12-413" aria-hidden="true" tabindex="-1"></a>rows <span class="op">=</span> []</span>
<span id="cb12-414"><a href="#cb12-414" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, bm, sm_b, sm_se, sm_z, sm_p <span class="kw">in</span> <span class="bu">zip</span>(</span>
<span id="cb12-415"><a href="#cb12-415" aria-hidden="true" tabindex="-1"></a>    coef_names, beta_hat,</span>
<span id="cb12-416"><a href="#cb12-416" aria-hidden="true" tabindex="-1"></a>    glm_result.params.values, glm_result.bse.values,</span>
<span id="cb12-417"><a href="#cb12-417" aria-hidden="true" tabindex="-1"></a>    glm_result.tvalues.values, glm_result.pvalues.values</span>
<span id="cb12-418"><a href="#cb12-418" aria-hidden="true" tabindex="-1"></a>):</span>
<span id="cb12-419"><a href="#cb12-419" aria-hidden="true" tabindex="-1"></a>    ci_lo <span class="op">=</span> sm_b <span class="op">-</span> <span class="fl">1.96</span> <span class="op">*</span> sm_se</span>
<span id="cb12-420"><a href="#cb12-420" aria-hidden="true" tabindex="-1"></a>    ci_hi <span class="op">=</span> sm_b <span class="op">+</span> <span class="fl">1.96</span> <span class="op">*</span> sm_se</span>
<span id="cb12-421"><a href="#cb12-421" aria-hidden="true" tabindex="-1"></a>    rows.append({</span>
<span id="cb12-422"><a href="#cb12-422" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Covariate"</span>:    name,</span>
<span id="cb12-423"><a href="#cb12-423" aria-hidden="true" tabindex="-1"></a>        <span class="st">"b_manual"</span>:     <span class="ss">f"</span><span class="sc">{</span>bm<span class="sc">:.4f}</span><span class="ss">"</span>,</span>
<span id="cb12-424"><a href="#cb12-424" aria-hidden="true" tabindex="-1"></a>        <span class="st">"b_glm"</span>:        <span class="ss">f"</span><span class="sc">{</span>sm_b<span class="sc">:.4f}</span><span class="ss">"</span>,</span>
<span id="cb12-425"><a href="#cb12-425" aria-hidden="true" tabindex="-1"></a>        <span class="st">"se"</span>:           <span class="ss">f"</span><span class="sc">{</span>sm_se<span class="sc">:.4f}</span><span class="ss">"</span>,</span>
<span id="cb12-426"><a href="#cb12-426" aria-hidden="true" tabindex="-1"></a>        <span class="st">"z"</span>:            <span class="ss">f"</span><span class="sc">{</span>sm_z<span class="sc">:.3f}</span><span class="ss">"</span>,</span>
<span id="cb12-427"><a href="#cb12-427" aria-hidden="true" tabindex="-1"></a>        <span class="st">"p"</span>:            <span class="ss">f"</span><span class="sc">{</span>sm_p<span class="sc">:.4f}</span><span class="ss">"</span>,</span>
<span id="cb12-428"><a href="#cb12-428" aria-hidden="true" tabindex="-1"></a>        <span class="st">"sig"</span>:          sig_stars(sm_p),</span>
<span id="cb12-429"><a href="#cb12-429" aria-hidden="true" tabindex="-1"></a>        <span class="st">"ci"</span>:           <span class="ss">f"[</span><span class="sc">{</span>ci_lo<span class="sc">:.3f}</span><span class="ss">, </span><span class="sc">{</span>ci_hi<span class="sc">:.3f}</span><span class="ss">]"</span>,</span>
<span id="cb12-430"><a href="#cb12-430" aria-hidden="true" tabindex="-1"></a>        <span class="st">"p_raw"</span>:        sm_p,</span>
<span id="cb12-431"><a href="#cb12-431" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb12-432"><a href="#cb12-432" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-433"><a href="#cb12-433" aria-hidden="true" tabindex="-1"></a>html <span class="op">=</span> <span class="st">"""</span></span>
<span id="cb12-434"><a href="#cb12-434" aria-hidden="true" tabindex="-1"></a><span class="st">&lt;style&gt;</span></span>
<span id="cb12-435"><a href="#cb12-435" aria-hidden="true" tabindex="-1"></a><span class="st">.coef-table { border-collapse: collapse; width: 100%; font-size: 13px; font-family: sans-serif; }</span></span>
<span id="cb12-436"><a href="#cb12-436" aria-hidden="true" tabindex="-1"></a><span class="st">.coef-table th { background-color: #3A7EC6; color: white; padding: 9px 12px; text-align: center; font-weight: bold; }</span></span>
<span id="cb12-437"><a href="#cb12-437" aria-hidden="true" tabindex="-1"></a><span class="st">.coef-table td { padding: 7px 12px; text-align: center; border-bottom: 1px solid #e0e0e0; }</span></span>
<span id="cb12-438"><a href="#cb12-438" aria-hidden="true" tabindex="-1"></a><span class="st">.coef-table tr:nth-child(even) { background-color: #f7f9fc; }</span></span>
<span id="cb12-439"><a href="#cb12-439" aria-hidden="true" tabindex="-1"></a><span class="st">.coef-table tr.highlight td { background-color: #d4edff; font-weight: bold; }</span></span>
<span id="cb12-440"><a href="#cb12-440" aria-hidden="true" tabindex="-1"></a><span class="st">.sig-cell { color: #C0392B; font-weight: bold; }</span></span>
<span id="cb12-441"><a href="#cb12-441" aria-hidden="true" tabindex="-1"></a><span class="st">.note { font-size: 11px; color: #555; margin-top: 8px; font-style: italic; }</span></span>
<span id="cb12-442"><a href="#cb12-442" aria-hidden="true" tabindex="-1"></a><span class="st">&lt;/style&gt;</span></span>
<span id="cb12-443"><a href="#cb12-443" aria-hidden="true" tabindex="-1"></a><span class="st">&lt;table class="coef-table"&gt;</span></span>
<span id="cb12-444"><a href="#cb12-444" aria-hidden="true" tabindex="-1"></a><span class="st">&lt;thead&gt;</span></span>
<span id="cb12-445"><a href="#cb12-445" aria-hidden="true" tabindex="-1"></a><span class="st">  &lt;tr&gt;</span></span>
<span id="cb12-446"><a href="#cb12-446" aria-hidden="true" tabindex="-1"></a><span class="st">    &lt;th&gt;Covariate&lt;/th&gt;&lt;th&gt;β̂ (manual)&lt;/th&gt;&lt;th&gt;β̂ (GLM)&lt;/th&gt;</span></span>
<span id="cb12-447"><a href="#cb12-447" aria-hidden="true" tabindex="-1"></a><span class="st">    &lt;th&gt;Std. Error&lt;/th&gt;&lt;th&gt;z-statistic&lt;/th&gt;&lt;th&gt;p-value&lt;/th&gt;</span></span>
<span id="cb12-448"><a href="#cb12-448" aria-hidden="true" tabindex="-1"></a><span class="st">    &lt;th&gt;Sig.&lt;/th&gt;&lt;th&gt;95% CI&lt;/th&gt;</span></span>
<span id="cb12-449"><a href="#cb12-449" aria-hidden="true" tabindex="-1"></a><span class="st">  &lt;/tr&gt;</span></span>
<span id="cb12-450"><a href="#cb12-450" aria-hidden="true" tabindex="-1"></a><span class="st">&lt;/thead&gt;&lt;tbody&gt;</span></span>
<span id="cb12-451"><a href="#cb12-451" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span></span>
<span id="cb12-452"><a href="#cb12-452" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-453"><a href="#cb12-453" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> row <span class="kw">in</span> rows:</span>
<span id="cb12-454"><a href="#cb12-454" aria-hidden="true" tabindex="-1"></a>    tr_class <span class="op">=</span> <span class="st">' class="highlight"'</span> <span class="cf">if</span> row[<span class="st">"Covariate"</span>] <span class="op">==</span> <span class="st">"iscustomer"</span> <span class="cf">else</span> <span class="st">""</span></span>
<span id="cb12-455"><a href="#cb12-455" aria-hidden="true" tabindex="-1"></a>    sig_td   <span class="op">=</span> <span class="ss">f'&lt;td class="sig-cell"&gt;</span><span class="sc">{</span>row[<span class="st">"sig"</span>]<span class="sc">}</span><span class="ss">&lt;/td&gt;'</span> <span class="cf">if</span> row[<span class="st">"sig"</span>] <span class="cf">else</span> <span class="ss">f'&lt;td&gt;</span><span class="sc">{</span>row[<span class="st">"sig"</span>]<span class="sc">}</span><span class="ss">&lt;/td&gt;'</span></span>
<span id="cb12-456"><a href="#cb12-456" aria-hidden="true" tabindex="-1"></a>    html <span class="op">+=</span> <span class="ss">f"""&lt;tr</span><span class="sc">{</span>tr_class<span class="sc">}</span><span class="ss">&gt;</span></span>
<span id="cb12-457"><a href="#cb12-457" aria-hidden="true" tabindex="-1"></a><span class="ss">  &lt;td&gt;&lt;code&gt;</span><span class="sc">{</span>row[<span class="st">"Covariate"</span>]<span class="sc">}</span><span class="ss">&lt;/code&gt;&lt;/td&gt;</span></span>
<span id="cb12-458"><a href="#cb12-458" aria-hidden="true" tabindex="-1"></a><span class="ss">  &lt;td&gt;</span><span class="sc">{</span>row[<span class="st">"b_manual"</span>]<span class="sc">}</span><span class="ss">&lt;/td&gt;&lt;td&gt;</span><span class="sc">{</span>row[<span class="st">"b_glm"</span>]<span class="sc">}</span><span class="ss">&lt;/td&gt;</span></span>
<span id="cb12-459"><a href="#cb12-459" aria-hidden="true" tabindex="-1"></a><span class="ss">  &lt;td&gt;</span><span class="sc">{</span>row[<span class="st">"se"</span>]<span class="sc">}</span><span class="ss">&lt;/td&gt;&lt;td&gt;</span><span class="sc">{</span>row[<span class="st">"z"</span>]<span class="sc">}</span><span class="ss">&lt;/td&gt;</span></span>
<span id="cb12-460"><a href="#cb12-460" aria-hidden="true" tabindex="-1"></a><span class="ss">  &lt;td&gt;</span><span class="sc">{</span>row[<span class="st">"p"</span>]<span class="sc">}</span><span class="ss">&lt;/td&gt;</span><span class="sc">{</span>sig_td<span class="sc">}</span><span class="ss">&lt;td&gt;</span><span class="sc">{</span>row[<span class="st">"ci"</span>]<span class="sc">}</span><span class="ss">&lt;/td&gt;</span></span>
<span id="cb12-461"><a href="#cb12-461" aria-hidden="true" tabindex="-1"></a><span class="ss">&lt;/tr&gt;</span></span>
<span id="cb12-462"><a href="#cb12-462" aria-hidden="true" tabindex="-1"></a><span class="ss">"""</span></span>
<span id="cb12-463"><a href="#cb12-463" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-464"><a href="#cb12-464" aria-hidden="true" tabindex="-1"></a>html <span class="op">+=</span> <span class="st">"""&lt;/tbody&gt;&lt;/table&gt;</span></span>
<span id="cb12-465"><a href="#cb12-465" aria-hidden="true" tabindex="-1"></a><span class="st">&lt;p class="note"&gt;Significance: *** p &amp;lt; 0.001 &amp;nbsp;|&amp;nbsp; ** p &amp;lt; 0.01 &amp;nbsp;|&amp;nbsp; * p &amp;lt; 0.05 &amp;nbsp;|&amp;nbsp; Reference region: Midwest. Highlighted row = key variable of interest.&lt;/p&gt;</span></span>
<span id="cb12-466"><a href="#cb12-466" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span></span>
<span id="cb12-467"><a href="#cb12-467" aria-hidden="true" tabindex="-1"></a>display(HTML(html))</span>
<span id="cb12-468"><a href="#cb12-468" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb12-469"><a href="#cb12-469" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-470"><a href="#cb12-470" aria-hidden="true" tabindex="-1"></a>The manual MLE coefficients match the GLM output almost exactly — confirming our implementation is correct. Small differences in standard errors are expected: <span class="in">`scipy`</span> approximates the Hessian numerically via finite differences, while <span class="in">`statsmodels`</span> uses the exact analytic Fisher information matrix from the IRLS algorithm. Both are asymptotically valid; the GLM standard errors are slightly more precise in finite samples.</span>
<span id="cb12-471"><a href="#cb12-471" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-472"><a href="#cb12-472" aria-hidden="true" tabindex="-1"></a><span class="fu">### Interpreting Each Coefficient</span></span>
<span id="cb12-473"><a href="#cb12-473" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-476"><a href="#cb12-476" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb12-477"><a href="#cb12-477" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb12-478"><a href="#cb12-478" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-coef-plot</span></span>
<span id="cb12-479"><a href="#cb12-479" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Coefficient plot with 95% confidence intervals. Blue bars are statistically significant (p &lt; 0.05); gray bars are not. The iscustomer and age terms drive the model."</span></span>
<span id="cb12-480"><a href="#cb12-480" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-481"><a href="#cb12-481" aria-hidden="true" tabindex="-1"></a>coefs   <span class="op">=</span> glm_result.params.values</span>
<span id="cb12-482"><a href="#cb12-482" aria-hidden="true" tabindex="-1"></a>ses     <span class="op">=</span> glm_result.bse.values</span>
<span id="cb12-483"><a href="#cb12-483" aria-hidden="true" tabindex="-1"></a>pvals_v <span class="op">=</span> glm_result.pvalues.values</span>
<span id="cb12-484"><a href="#cb12-484" aria-hidden="true" tabindex="-1"></a>names   <span class="op">=</span> coef_names</span>
<span id="cb12-485"><a href="#cb12-485" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-486"><a href="#cb12-486" aria-hidden="true" tabindex="-1"></a>mask   <span class="op">=</span> [i <span class="cf">for</span> i, n <span class="kw">in</span> <span class="bu">enumerate</span>(names) <span class="cf">if</span> n <span class="op">!=</span> <span class="st">"intercept"</span>]</span>
<span id="cb12-487"><a href="#cb12-487" aria-hidden="true" tabindex="-1"></a>names_ <span class="op">=</span> [names[i] <span class="cf">for</span> i <span class="kw">in</span> mask]</span>
<span id="cb12-488"><a href="#cb12-488" aria-hidden="true" tabindex="-1"></a>coefs_ <span class="op">=</span> coefs[mask]</span>
<span id="cb12-489"><a href="#cb12-489" aria-hidden="true" tabindex="-1"></a>ses_   <span class="op">=</span> ses[mask]</span>
<span id="cb12-490"><a href="#cb12-490" aria-hidden="true" tabindex="-1"></a>pvals_ <span class="op">=</span> pvals_v[mask]</span>
<span id="cb12-491"><a href="#cb12-491" aria-hidden="true" tabindex="-1"></a>colors <span class="op">=</span> [BLUE <span class="cf">if</span> p <span class="op">&lt;</span> <span class="fl">0.05</span> <span class="cf">else</span> GRAY <span class="cf">for</span> p <span class="kw">in</span> pvals_]</span>
<span id="cb12-492"><a href="#cb12-492" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-493"><a href="#cb12-493" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="fl">4.8</span>))</span>
<span id="cb12-494"><a href="#cb12-494" aria-hidden="true" tabindex="-1"></a>y_pos   <span class="op">=</span> np.arange(<span class="bu">len</span>(names_))</span>
<span id="cb12-495"><a href="#cb12-495" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-496"><a href="#cb12-496" aria-hidden="true" tabindex="-1"></a>ax.barh(y_pos, coefs_, xerr<span class="op">=</span><span class="fl">1.96</span> <span class="op">*</span> ses_,</span>
<span id="cb12-497"><a href="#cb12-497" aria-hidden="true" tabindex="-1"></a>        color<span class="op">=</span>colors, alpha<span class="op">=</span><span class="fl">0.82</span>, edgecolor<span class="op">=</span><span class="st">"white"</span>, height<span class="op">=</span><span class="fl">0.55</span>,</span>
<span id="cb12-498"><a href="#cb12-498" aria-hidden="true" tabindex="-1"></a>        error_kw<span class="op">=</span>{<span class="st">"elinewidth"</span>: <span class="fl">1.8</span>, <span class="st">"capsize"</span>: <span class="dv">5</span>, <span class="st">"ecolor"</span>: <span class="st">"black"</span>})</span>
<span id="cb12-499"><a href="#cb12-499" aria-hidden="true" tabindex="-1"></a>ax.axvline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">"black"</span>, lw<span class="op">=</span><span class="fl">1.2</span>, ls<span class="op">=</span><span class="st">"--"</span>, alpha<span class="op">=</span><span class="fl">0.6</span>)</span>
<span id="cb12-500"><a href="#cb12-500" aria-hidden="true" tabindex="-1"></a>ax.set_yticks(y_pos)</span>
<span id="cb12-501"><a href="#cb12-501" aria-hidden="true" tabindex="-1"></a>ax.set_yticklabels(names_, fontsize<span class="op">=</span><span class="dv">11</span>)</span>
<span id="cb12-502"><a href="#cb12-502" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"Coefficient Estimate  (log-rate scale)"</span>)</span>
<span id="cb12-503"><a href="#cb12-503" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Poisson Regression Coefficients with 95% Confidence Intervals"</span>)</span>
<span id="cb12-504"><a href="#cb12-504" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-505"><a href="#cb12-505" aria-hidden="true" tabindex="-1"></a>sig_patch   <span class="op">=</span> mpatches.Patch(color<span class="op">=</span>BLUE, alpha<span class="op">=</span><span class="fl">0.82</span>, label<span class="op">=</span><span class="st">"Significant (p &lt; 0.05)"</span>)</span>
<span id="cb12-506"><a href="#cb12-506" aria-hidden="true" tabindex="-1"></a>insig_patch <span class="op">=</span> mpatches.Patch(color<span class="op">=</span>GRAY, alpha<span class="op">=</span><span class="fl">0.82</span>, label<span class="op">=</span><span class="st">"Not significant"</span>)</span>
<span id="cb12-507"><a href="#cb12-507" aria-hidden="true" tabindex="-1"></a>ax.legend(handles<span class="op">=</span>[sig_patch, insig_patch], frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb12-508"><a href="#cb12-508" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-509"><a href="#cb12-509" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb12-510"><a href="#cb12-510" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb12-511"><a href="#cb12-511" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb12-512"><a href="#cb12-512" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-513"><a href="#cb12-513" aria-hidden="true" tabindex="-1"></a>All Poisson coefficients are on the **log-rate scale**: a coefficient $\beta$ means a one-unit increase in $X$ multiplies the expected patent count by $e^\beta$, holding all other variables fixed. Here is a plain-English walkthrough:</span>
<span id="cb12-514"><a href="#cb12-514" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-515"><a href="#cb12-515" aria-hidden="true" tabindex="-1"></a>**`intercept` (β = −0.509, p = 0.005):** The baseline log expected patent count for a Midwest firm with age = 0 and not a customer. This is a mathematical anchor; interpreted in isolation, it has no direct practical meaning.</span>
<span id="cb12-516"><a href="#cb12-516" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-517"><a href="#cb12-517" aria-hidden="true" tabindex="-1"></a>**`age` (β = +0.149, p &lt; 0.001):** Each additional year of firm age is associated with a $e^{0.149} \approx 1.16$ (16%) increase in expected patents, all else equal. Older firms have more developed R&amp;D pipelines, deeper technical expertise, and established relationships with patent attorneys — all of which make additional patents more likely. The effect is highly statistically significant (z = 10.72, p &lt; 0.001).</span>
<span id="cb12-518"><a href="#cb12-518" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-519"><a href="#cb12-519" aria-hidden="true" tabindex="-1"></a>**`age²` (β = −0.003, p &lt; 0.001):** The negative quadratic term confirms a **concave age profile** — the age benefit slows down and eventually reverses. Setting the derivative of the log-rate with respect to age to zero: $\hat{\beta}_{age} + 2\hat{\beta}_{age^2} \cdot \text{age} = 0 \Rightarrow \text{age}^* = -0.149 / (2 \times -0.003) \approx \mathbf{25\ years}$. Firms older than about 25 years begin to patent at a declining marginal rate, consistent with product-line maturity. This term is also highly significant (z = −11.51, p &lt; 0.001).</span>
<span id="cb12-520"><a href="#cb12-520" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-521"><a href="#cb12-521" aria-hidden="true" tabindex="-1"></a>**`iscustomer` (β = +0.208, p &lt; 0.001):** This is the key coefficient. Controlling for firm age and region, Blueprinty customers are estimated to patent at $e^{0.208} \approx$ **1.23 times the rate** of otherwise-identical non-customers — a **23% lift** in expected patents. The effect is large, precisely estimated (SE = 0.031), and highly significant (z = 6.72, p &lt; 0.001). The 95% confidence interval <span class="co">[</span><span class="ot">0.147, 0.268</span><span class="co">]</span> lies entirely in positive territory, ruling out a zero or negative effect at any conventional significance level.</span>
<span id="cb12-522"><a href="#cb12-522" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-523"><a href="#cb12-523" aria-hidden="true" tabindex="-1"></a>**Region dummies (all p &gt; 0.25):** After controlling for age and customer status, none of the regional dummies are statistically distinguishable from the Midwest baseline. This is an important finding: the raw Northeast overrepresentation among Blueprinty customers was creating a confound. Once we condition on firm-level characteristics, regional location does not independently predict patent counts. The customer effect survives this control fully intact.</span>
<span id="cb12-524"><a href="#cb12-524" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-525"><a href="#cb12-525" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb12-526"><a href="#cb12-526" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-527"><a href="#cb12-527" aria-hidden="true" tabindex="-1"></a><span class="fu">## The Effect of Blueprinty's Software</span></span>
<span id="cb12-528"><a href="#cb12-528" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-529"><a href="#cb12-529" aria-hidden="true" tabindex="-1"></a><span class="fu">### From Coefficients to Predicted Patents</span></span>
<span id="cb12-530"><a href="#cb12-530" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-531"><a href="#cb12-531" aria-hidden="true" tabindex="-1"></a>A Poisson coefficient is not directly an "extra patent" number — the model is **multiplicative**, so the same coefficient produces different absolute effects depending on a firm's baseline rate. A 23% lift means more patents for a highly active firm than for a low-activity firm. To get a practically meaningful estimate, we use **counterfactual prediction**: for every firm in the dataset, we predict how many patents they'd earn as a customer vs. as a non-customer, holding all other characteristics fixed.</span>
<span id="cb12-532"><a href="#cb12-532" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-535"><a href="#cb12-535" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb12-536"><a href="#cb12-536" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb12-537"><a href="#cb12-537" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-538"><a href="#cb12-538" aria-hidden="true" tabindex="-1"></a><span class="co"># Counterfactual scenario 0: set every firm as a non-customer</span></span>
<span id="cb12-539"><a href="#cb12-539" aria-hidden="true" tabindex="-1"></a>X0 <span class="op">=</span> X.copy()</span>
<span id="cb12-540"><a href="#cb12-540" aria-hidden="true" tabindex="-1"></a>X0[<span class="st">"iscustomer"</span>] <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb12-541"><a href="#cb12-541" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-542"><a href="#cb12-542" aria-hidden="true" tabindex="-1"></a><span class="co"># Counterfactual scenario 1: set every firm as a customer</span></span>
<span id="cb12-543"><a href="#cb12-543" aria-hidden="true" tabindex="-1"></a>X1 <span class="op">=</span> X.copy()</span>
<span id="cb12-544"><a href="#cb12-544" aria-hidden="true" tabindex="-1"></a>X1[<span class="st">"iscustomer"</span>] <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb12-545"><a href="#cb12-545" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-546"><a href="#cb12-546" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict expected patents under each scenario</span></span>
<span id="cb12-547"><a href="#cb12-547" aria-hidden="true" tabindex="-1"></a>y_hat_0 <span class="op">=</span> glm_result.predict(X0)</span>
<span id="cb12-548"><a href="#cb12-548" aria-hidden="true" tabindex="-1"></a>y_hat_1 <span class="op">=</span> glm_result.predict(X1)</span>
<span id="cb12-549"><a href="#cb12-549" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-550"><a href="#cb12-550" aria-hidden="true" tabindex="-1"></a><span class="co"># Individual and average treatment effects</span></span>
<span id="cb12-551"><a href="#cb12-551" aria-hidden="true" tabindex="-1"></a>individual_effects <span class="op">=</span> y_hat_1 <span class="op">-</span> y_hat_0</span>
<span id="cb12-552"><a href="#cb12-552" aria-hidden="true" tabindex="-1"></a>ate <span class="op">=</span> individual_effects.mean()</span>
<span id="cb12-553"><a href="#cb12-553" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-554"><a href="#cb12-554" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Avg predicted patents — no Blueprinty  : </span><span class="sc">{</span>y_hat_0<span class="sc">.</span>mean()<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb12-555"><a href="#cb12-555" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Avg predicted patents — with Blueprinty: </span><span class="sc">{</span>y_hat_1<span class="sc">.</span>mean()<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb12-556"><a href="#cb12-556" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Average Treatment Effect (ATE)         : </span><span class="sc">{</span>ate<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb12-557"><a href="#cb12-557" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Percentage lift                         : </span><span class="sc">{</span>ate <span class="op">/</span> y_hat_0<span class="sc">.</span>mean() <span class="op">*</span> <span class="dv">100</span><span class="sc">:.1f}</span><span class="ss">%"</span>)</span>
<span id="cb12-558"><a href="#cb12-558" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb12-559"><a href="#cb12-559" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-562"><a href="#cb12-562" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb12-563"><a href="#cb12-563" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb12-564"><a href="#cb12-564" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-counterfactual</span></span>
<span id="cb12-565"><a href="#cb12-565" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Left: distribution of individual treatment effects (ŷ₁ − ŷ₀) across all 1,500 firms. Right: scatter of counterfactual predicted patents — each firm's prediction under the two scenarios. All points lie above the diagonal, confirming a universally positive estimated effect."</span></span>
<span id="cb12-566"><a href="#cb12-566" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-567"><a href="#cb12-567" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="fl">4.5</span>))</span>
<span id="cb12-568"><a href="#cb12-568" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-569"><a href="#cb12-569" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> axes[<span class="dv">0</span>]</span>
<span id="cb12-570"><a href="#cb12-570" aria-hidden="true" tabindex="-1"></a>ax.hist(individual_effects, bins<span class="op">=</span><span class="dv">40</span>, color<span class="op">=</span>BLUE, edgecolor<span class="op">=</span><span class="st">"white"</span>,</span>
<span id="cb12-571"><a href="#cb12-571" aria-hidden="true" tabindex="-1"></a>        linewidth<span class="op">=</span><span class="fl">0.5</span>, alpha<span class="op">=</span><span class="fl">0.85</span>, density<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb12-572"><a href="#cb12-572" aria-hidden="true" tabindex="-1"></a>ax.axvline(ate, color<span class="op">=</span>RED, lw<span class="op">=</span><span class="fl">2.2</span>, ls<span class="op">=</span><span class="st">"--"</span>, label<span class="op">=</span><span class="ss">f"ATE = </span><span class="sc">{</span>ate<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb12-573"><a href="#cb12-573" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"Extra Patents from Blueprinty  (ŷ₁ − ŷ₀)"</span>)</span>
<span id="cb12-574"><a href="#cb12-574" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"Density"</span>)</span>
<span id="cb12-575"><a href="#cb12-575" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Distribution of Individual Treatment Effects"</span>)</span>
<span id="cb12-576"><a href="#cb12-576" aria-hidden="true" tabindex="-1"></a>ax.legend(frameon<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb12-577"><a href="#cb12-577" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-578"><a href="#cb12-578" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> axes[<span class="dv">1</span>]</span>
<span id="cb12-579"><a href="#cb12-579" aria-hidden="true" tabindex="-1"></a>ax.scatter(y_hat_0, y_hat_1, alpha<span class="op">=</span><span class="fl">0.12</span>, s<span class="op">=</span><span class="dv">8</span>, color<span class="op">=</span>BLUE)</span>
<span id="cb12-580"><a href="#cb12-580" aria-hidden="true" tabindex="-1"></a>lims <span class="op">=</span> [<span class="bu">min</span>(y_hat_0.<span class="bu">min</span>(), y_hat_1.<span class="bu">min</span>()) <span class="op">-</span> <span class="fl">0.1</span>,</span>
<span id="cb12-581"><a href="#cb12-581" aria-hidden="true" tabindex="-1"></a>        <span class="bu">max</span>(y_hat_0.<span class="bu">max</span>(), y_hat_1.<span class="bu">max</span>()) <span class="op">+</span> <span class="fl">0.1</span>]</span>
<span id="cb12-582"><a href="#cb12-582" aria-hidden="true" tabindex="-1"></a>ax.plot(lims, lims, color<span class="op">=</span>GRAY, lw<span class="op">=</span><span class="fl">1.5</span>, ls<span class="op">=</span><span class="st">"--"</span>, label<span class="op">=</span><span class="st">"No effect (ŷ₁ = ŷ₀)"</span>)</span>
<span id="cb12-583"><a href="#cb12-583" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"Predicted Patents — No Blueprinty (ŷ₀)"</span>)</span>
<span id="cb12-584"><a href="#cb12-584" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"Predicted Patents — With Blueprinty (ŷ₁)"</span>)</span>
<span id="cb12-585"><a href="#cb12-585" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Counterfactual Predictions per Firm"</span>)</span>
<span id="cb12-586"><a href="#cb12-586" aria-hidden="true" tabindex="-1"></a>ax.legend(frameon<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb12-587"><a href="#cb12-587" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-588"><a href="#cb12-588" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb12-589"><a href="#cb12-589" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb12-590"><a href="#cb12-590" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb12-591"><a href="#cb12-591" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-592"><a href="#cb12-592" aria-hidden="true" tabindex="-1"></a><span class="fu">### The Bottom Line</span></span>
<span id="cb12-593"><a href="#cb12-593" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-594"><a href="#cb12-594" aria-hidden="true" tabindex="-1"></a>Holding firm age and regional location fixed at their observed values for each of the 1,500 firms in the dataset, the model predicts that **using Blueprinty's software is associated with approximately 0.79 additional patents over five years** compared to not using it. Against a non-customer baseline of roughly 3.47 patents, this represents a **23% increase in patent output** — a commercially meaningful effect if it reflects a real causal relationship.</span>
<span id="cb12-595"><a href="#cb12-595" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-596"><a href="#cb12-596" aria-hidden="true" tabindex="-1"></a><span class="fu">### What This Analysis Does and Does Not Establish</span></span>
<span id="cb12-597"><a href="#cb12-597" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-598"><a href="#cb12-598" aria-hidden="true" tabindex="-1"></a>This result deserves careful interpretation. Several important caveats apply:</span>
<span id="cb12-599"><a href="#cb12-599" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-600"><a href="#cb12-600" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**This is an observational study, not a randomized experiment.** We did not randomly assign firms to use Blueprinty's software. The regression controls for firm age and region, but there may be unmeasured differences between customers and non-customers — R&amp;D budget, engineering team size, prior patenting history, firm culture around intellectual property — that could partially or fully explain the gap. In the language of causal inference, we cannot rule out **unobserved confounding**.</span>
<span id="cb12-601"><a href="#cb12-601" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-602"><a href="#cb12-602" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**The evidence is strong and survives the most obvious controls.** The customer coefficient is large (23% lift), highly significant (p &lt; 0.001, z = 6.72), and robust to conditioning on the two confounders (age and region) that were most obviously different between groups. The 95% CI <span class="co">[</span><span class="ot">0.147, 0.268</span><span class="co">]</span> is entirely positive.</span>
<span id="cb12-603"><a href="#cb12-603" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-604"><a href="#cb12-604" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**A proper causal study would require more.** A randomized trial — where firms are randomly assigned to Blueprinty versus a control condition — would cleanly identify the causal effect. Alternatively, a natural experiment (e.g., staggered regional rollout) or an instrumental variables approach could strengthen causal inference from observational data.</span>
<span id="cb12-605"><a href="#cb12-605" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-606"><a href="#cb12-606" aria-hidden="true" tabindex="-1"></a>**In summary:** the data provide strong, statistically significant evidence that Blueprinty customers patent at higher rates than otherwise-comparable non-customers. The estimated effect of roughly **+0.79 patents per five-year window (23% lift)** is consistent with Blueprinty's marketing claims. A careful business-facing statement would be: *"Firms using our software are associated with 23% more patents than similar firms that don't, after controlling for age and geography. This is compelling suggestive evidence of software value, though a randomized study would be needed to establish causation definitively."*</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>