<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jihee Yoon">
<meta name="dcterms.date" content="2026-06-07">
<meta name="description" content="We compute and compare six methods for quantifying variable importance — Pearson correlations, standardized regression coefficients, drop-one usefulness, Shapley values, Johnson’s relative weights, and random forest Gini importance — applied to a customer satisfaction survey.">

<title>What Drives Customer Satisfaction? A Key Drivers Analysis – Jihee Yoon</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-597958c53c93a607afca12fd375c57ed.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-1f2d6daba7bd1a79bea505a54d6176a8.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Jihee Yoon</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data">The Data</a></li>
  <li><a href="#method-1-pearson-correlations" id="toc-method-1-pearson-correlations" class="nav-link" data-scroll-target="#method-1-pearson-correlations">Method 1: Pearson Correlations</a></li>
  <li><a href="#method-2-standardized-regression-coefficients" id="toc-method-2-standardized-regression-coefficients" class="nav-link" data-scroll-target="#method-2-standardized-regression-coefficients">Method 2: Standardized Regression Coefficients</a></li>
  <li><a href="#method-3-drop-one-usefulness" id="toc-method-3-drop-one-usefulness" class="nav-link" data-scroll-target="#method-3-drop-one-usefulness">Method 3: Drop-One Usefulness</a></li>
  <li><a href="#method-4-shapley-values-own-implementation" id="toc-method-4-shapley-values-own-implementation" class="nav-link" data-scroll-target="#method-4-shapley-values-own-implementation">Method 4: Shapley Values (Own Implementation)</a></li>
  <li><a href="#method-5-johnsons-relative-weights" id="toc-method-5-johnsons-relative-weights" class="nav-link" data-scroll-target="#method-5-johnsons-relative-weights">Method 5: Johnson’s Relative Weights</a></li>
  <li><a href="#method-6-random-forest-gini-importance" id="toc-method-6-random-forest-gini-importance" class="nav-link" data-scroll-target="#method-6-random-forest-gini-importance">Method 6: Random Forest Gini Importance</a></li>
  <li><a href="#the-full-comparison-table" id="toc-the-full-comparison-table" class="nav-link" data-scroll-target="#the-full-comparison-table">The Full Comparison Table</a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a>
  <ul class="collapse">
  <li><a href="#what-the-methods-agree-on" id="toc-what-the-methods-agree-on" class="nav-link" data-scroll-target="#what-the-methods-agree-on">What the Methods Agree On</a></li>
  <li><a href="#where-the-methods-disagree-and-why" id="toc-where-the-methods-disagree-and-why" class="nav-link" data-scroll-target="#where-the-methods-disagree-and-why">Where the Methods Disagree — and Why</a></li>
  <li><a href="#which-method-should-you-use" id="toc-which-method-should-you-use" class="nav-link" data-scroll-target="#which-method-should-you-use">Which Method Should You Use?</a></li>
  <li><a href="#business-recommendation" id="toc-business-recommendation" class="nav-link" data-scroll-target="#business-recommendation">Business Recommendation</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">What Drives Customer Satisfaction? A Key Drivers Analysis</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
<p class="subtitle lead">Comparing Six Variable Importance Methods on Customer Survey Data</p>
  <div class="quarto-categories">
    <div class="quarto-category">Variable Importance</div>
    <div class="quarto-category">Key Drivers</div>
    <div class="quarto-category">Random Forest</div>
    <div class="quarto-category">Shapley Values</div>
  </div>
  </div>

<div>
  <div class="description">
    We compute and compare six methods for quantifying variable importance — Pearson correlations, standardized regression coefficients, drop-one usefulness, Shapley values, Johnson’s relative weights, and random forest Gini importance — applied to a customer satisfaction survey.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jihee Yoon </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 7, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>When a company runs a customer satisfaction survey, the natural follow-up question is: <strong>what actually drives satisfaction?</strong> Is it product quality, ease of use, brand trust, or something else? The challenge is that most drivers are correlated with each other, so simply looking at which variable has the highest correlation with satisfaction can be misleading.</p>
<p><strong>Key drivers analysis</strong> is a set of techniques for measuring the <em>relative importance</em> of each driver after accounting for the fact that predictors are correlated. Different methods make different assumptions and decompose explained variance in different ways — and a trustworthy analysis compares them side by side.</p>
<p>In this post we apply <strong>six methods</strong> to a customer satisfaction survey dataset (n = 2,553 respondents, 9 drivers) and replicate the variable importance table from class:</p>
<ol type="1">
<li><strong>Pearson correlation</strong> — simple bivariate relationship</li>
<li><strong>Standardized regression coefficients</strong> — partial effects controlling for all others</li>
<li><strong>Drop-one usefulness</strong> — R² lost when each driver is removed</li>
<li><strong>Shapley values</strong> — fair allocation of R² across all coalition orderings</li>
<li><strong>Johnson’s relative weights</strong> — variance decomposition via orthogonalization</li>
<li><strong>Random forest Gini importance</strong> — nonlinear, tree-based importance</li>
</ol>
<hr>
</section>
<section id="the-data" class="level2">
<h2 class="anchored" data-anchor-id="the-data">The Data</h2>
<div id="b77fa399" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">"data_for_drivers_analysis.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Rows: </span><span class="sc">{</span>df<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="sc">}</span><span class="ss">   Columns: </span><span class="sc">{</span>df<span class="sc">.</span>shape[<span class="dv">1</span>]<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Outcome  : </span><span class="sc">{</span>y_col<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Drivers  : </span><span class="sc">{</span>x_cols<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Satisfaction range: </span><span class="sc">{</span>df[y_col]<span class="sc">.</span><span class="bu">min</span>()<span class="sc">}</span><span class="ss">–</span><span class="sc">{</span>df[y_col]<span class="sc">.</span><span class="bu">max</span>()<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Driver variables  : binary (0/1) except satisfaction (1–5 scale)"</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>df[x_cols <span class="op">+</span> [y_col]].describe().<span class="bu">round</span>(<span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 2553   Columns: 12

Outcome  : satisfaction
Drivers  : ['trust', 'build', 'differs', 'easy', 'appealing', 'rewarding', 'popular', 'service', 'impact']

Satisfaction range: 1–5
Driver variables  : binary (0/1) except satisfaction (1–5 scale)</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">trust</th>
<th data-quarto-table-cell-role="th">build</th>
<th data-quarto-table-cell-role="th">differs</th>
<th data-quarto-table-cell-role="th">easy</th>
<th data-quarto-table-cell-role="th">appealing</th>
<th data-quarto-table-cell-role="th">rewarding</th>
<th data-quarto-table-cell-role="th">popular</th>
<th data-quarto-table-cell-role="th">service</th>
<th data-quarto-table-cell-role="th">impact</th>
<th data-quarto-table-cell-role="th">satisfaction</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">count</th>
<td>2553.000</td>
<td>2553.000</td>
<td>2553.000</td>
<td>2553.000</td>
<td>2553.000</td>
<td>2553.000</td>
<td>2553.000</td>
<td>2553.000</td>
<td>2553.000</td>
<td>2553.000</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">mean</th>
<td>0.550</td>
<td>0.462</td>
<td>0.335</td>
<td>0.536</td>
<td>0.451</td>
<td>0.451</td>
<td>0.536</td>
<td>0.467</td>
<td>0.331</td>
<td>3.387</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">std</th>
<td>0.498</td>
<td>0.499</td>
<td>0.472</td>
<td>0.499</td>
<td>0.498</td>
<td>0.498</td>
<td>0.499</td>
<td>0.499</td>
<td>0.471</td>
<td>1.172</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">min</th>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>1.000</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">25%</th>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>3.000</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">50%</th>
<td>1.000</td>
<td>0.000</td>
<td>0.000</td>
<td>1.000</td>
<td>0.000</td>
<td>0.000</td>
<td>1.000</td>
<td>0.000</td>
<td>0.000</td>
<td>4.000</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">75%</th>
<td>1.000</td>
<td>1.000</td>
<td>1.000</td>
<td>1.000</td>
<td>1.000</td>
<td>1.000</td>
<td>1.000</td>
<td>1.000</td>
<td>1.000</td>
<td>4.000</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">max</th>
<td>1.000</td>
<td>1.000</td>
<td>1.000</td>
<td>1.000</td>
<td>1.000</td>
<td>1.000</td>
<td>1.000</td>
<td>1.000</td>
<td>1.000</td>
<td>5.000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The outcome variable <code>satisfaction</code> is measured on a 1–5 scale. The nine driver variables are all binary (0 = no, 1 = yes), capturing whether each respondent agreed with statements about the brand across dimensions like trust, build quality, differentiation, ease of use, appeal, and so on.</p>
<div id="cell-fig-corr-matrix" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div id="fig-corr-matrix" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-corr-matrix-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-corr-matrix-output-1.png" width="762" height="658" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-corr-matrix-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Correlation matrix of all variables. Drivers are moderately inter-correlated (0.2–0.5), making raw correlations with satisfaction potentially misleading — which motivates the need for methods that account for multicollinearity.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The drivers are moderately inter-correlated (typical for survey data), which means the choice of importance method matters: raw correlations will overstate the importance of variables that happen to correlate with other important drivers, while regression coefficients can understate the importance of variables that share variance with other predictors.</p>
<hr>
</section>
<section id="method-1-pearson-correlations" class="level2">
<h2 class="anchored" data-anchor-id="method-1-pearson-correlations">Method 1: Pearson Correlations</h2>
<p>The simplest measure of importance: the bivariate correlation between each driver and satisfaction.</p>
<p><span class="math display">\[r_{X_j, Y} = \frac{\sum_i (X_{ij} - \bar{X}_j)(Y_i - \bar{Y})}{\sqrt{\sum_i (X_{ij} - \bar{X}_j)^2 \cdot \sum_i (Y_i - \bar{Y})^2}}\]</span></p>
<p><strong>Interpretation:</strong> <span class="math inline">\(r\)</span> ranges from −1 to +1. A larger positive value means the driver has a stronger raw association with satisfaction. The key limitation is that correlations do not control for other drivers — a driver can appear important simply because it correlates with a truly important driver.</p>
<div id="792fdedd" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>pearson <span class="op">=</span> {}</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> j, col <span class="kw">in</span> <span class="bu">enumerate</span>(x_cols):</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    r, p <span class="op">=</span> stats.pearsonr(df[col], df[y_col])</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    pearson[col] <span class="op">=</span> {<span class="st">"r"</span>: r, <span class="st">"p"</span>: p}</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>pearson_df <span class="op">=</span> pd.DataFrame(pearson).T.sort_values(<span class="st">"r"</span>, ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(pearson_df.<span class="bu">round</span>(<span class="dv">4</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                r    p
trust      0.2557  0.0
impact     0.2545  0.0
service    0.2511  0.0
easy       0.2130  0.0
appealing  0.2080  0.0
rewarding  0.1946  0.0
build      0.1919  0.0
differs    0.1848  0.0
popular    0.1714  0.0</code></pre>
</div>
</div>
<hr>
</section>
<section id="method-2-standardized-regression-coefficients" class="level2">
<h2 class="anchored" data-anchor-id="method-2-standardized-regression-coefficients">Method 2: Standardized Regression Coefficients</h2>
<p>We regress satisfaction on all nine drivers simultaneously, after standardizing both the predictors and outcome to have mean 0 and standard deviation 1. This gives <strong>partial effects</strong> — the association between each driver and satisfaction <em>holding all other drivers constant</em>.</p>
<p><span class="math display">\[\hat{Y}^* = \beta_1 X_1^* + \beta_2 X_2^* + \cdots + \beta_p X_p^*\]</span></p>
<p>where <span class="math inline">\(^*\)</span> denotes standardization. Because all variables are on the same scale, <span class="math inline">\(|\beta_j|\)</span> is directly comparable across drivers.</p>
<p><strong>Limitation:</strong> When predictors are correlated, variance shared between them is not allocated to any single predictor — it simply “disappears” from individual coefficients. This leads to underestimation of important-but-correlated drivers.</p>
<div id="ea31a779" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>lr_full <span class="op">=</span> LinearRegression().fit(X_sc, y_sc)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>std_coef <span class="op">=</span> <span class="bu">dict</span>(<span class="bu">zip</span>(x_cols, lr_full.coef_))</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>r2_full  <span class="op">=</span> lr_full.score(X_sc, y_sc)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Full model R² = </span><span class="sc">{</span>r2_full<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> k, v <span class="kw">in</span> <span class="bu">sorted</span>(std_coef.items(), key<span class="op">=</span><span class="kw">lambda</span> x: <span class="op">-</span><span class="bu">abs</span>(x[<span class="dv">1</span>])):</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>k<span class="sc">:&lt;12}</span><span class="ss">: </span><span class="sc">{</span>v<span class="sc">:+.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Full model R² = 0.1090

  impact      : +0.1284
  trust       : +0.1158
  service     : +0.0884
  appealing   : +0.0338
  differs     : +0.0278
  easy        : +0.0220
  build       : +0.0200
  popular     : +0.0166
  rewarding   : +0.0051</code></pre>
</div>
</div>
<p>The full model R² = <strong>0.109</strong> — meaning the nine drivers together explain about 10.9% of the variance in satisfaction. Notice that several coefficients are near zero: this reflects suppression from multicollinearity, not genuine unimportance.</p>
<hr>
</section>
<section id="method-3-drop-one-usefulness" class="level2">
<h2 class="anchored" data-anchor-id="method-3-drop-one-usefulness">Method 3: Drop-One Usefulness</h2>
<p>For each driver, we ask: <em>how much does R² drop if we remove this driver from the full model?</em></p>
<p><span class="math display">\[\text{Usefulness}_j = R^2_{\text{full}} - R^2_{-j}\]</span></p>
<p>where <span class="math inline">\(R^2_{-j}\)</span> is the R² of the model with driver <span class="math inline">\(j\)</span> removed. This measures the <strong>unique</strong> contribution of each driver — the variance it explains that no other driver can account for.</p>
<p><strong>Advantage over coefficients:</strong> Usefulness is always non-negative and directly interpretable as variance explained. <strong>Limitation:</strong> It ignores shared variance (variance that could be explained by multiple drivers).</p>
<div id="a9bbc75a" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>usefulness <span class="op">=</span> {}</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> j, col <span class="kw">in</span> <span class="bu">enumerate</span>(x_cols):</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    X_drop   <span class="op">=</span> np.delete(X_sc, j, axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    r2_drop  <span class="op">=</span> LinearRegression().fit(X_drop, y_sc).score(X_drop, y_sc)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    usefulness[col] <span class="op">=</span> r2_full <span class="op">-</span> r2_drop</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Full R² = </span><span class="sc">{</span>r2_full<span class="sc">:.4f}</span><span class="ss">   |   Sum of usefulness = </span><span class="sc">{</span><span class="bu">sum</span>(usefulness.values())<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> k, v <span class="kw">in</span> <span class="bu">sorted</span>(usefulness.items(), key<span class="op">=</span><span class="kw">lambda</span> x: <span class="op">-</span>x[<span class="dv">1</span>]):</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>k<span class="sc">:&lt;12}</span><span class="ss">: </span><span class="sc">{</span>v<span class="sc">:.4f}</span><span class="ss">  (</span><span class="sc">{</span>v<span class="op">/</span>r2_full<span class="op">*</span><span class="dv">100</span><span class="sc">:.1f}</span><span class="ss">% of R²)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Full R² = 0.1090   |   Sum of usefulness = 0.0262

  impact      : 0.0112  (10.3% of R²)
  trust       : 0.0082  (7.6% of R²)
  service     : 0.0047  (4.3% of R²)
  appealing   : 0.0007  (0.7% of R²)
  differs     : 0.0006  (0.5% of R²)
  easy        : 0.0003  (0.3% of R²)
  build       : 0.0003  (0.2% of R²)
  popular     : 0.0002  (0.2% of R²)
  rewarding   : 0.0000  (0.0% of R²)</code></pre>
</div>
</div>
<p>Note that the sum of usefulnesses is much less than R² — the remainder is <strong>shared variance</strong> that multiple drivers can explain, and drop-one doesn’t allocate it to anyone.</p>
<hr>
</section>
<section id="method-4-shapley-values-own-implementation" class="level2">
<h2 class="anchored" data-anchor-id="method-4-shapley-values-own-implementation">Method 4: Shapley Values (Own Implementation)</h2>
<p>Shapley values come from cooperative game theory. The idea: treat each driver as a “player” and R² as the “prize.” For each possible <strong>coalition</strong> (subset) of drivers, compute R². Then each driver’s Shapley value is its <strong>average marginal contribution</strong> across all possible orderings of players entering the coalition.</p>
<p><span class="math display">\[\phi_j = \sum_{S \subseteq N \setminus \{j\}} \frac{|S|!\,(|N|-|S|-1)!}{|N|!} \left[ R^2(S \cup \{j\}) - R^2(S) \right]\]</span></p>
<p><strong>Key property:</strong> Shapley values are the <em>unique</em> method that simultaneously satisfies: - <strong>Efficiency:</strong> values sum to R² - <strong>Symmetry:</strong> equally contributing drivers get equal values - <strong>Dummy:</strong> a useless driver gets zero - <strong>Additivity:</strong> consistent decomposition</p>
<p>This is the <strong>“fairest”</strong> allocation of R² across correlated predictors.</p>
<div id="e012bc2b" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Precompute R² for all 2^9 = 512 subsets</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>n_feat <span class="op">=</span> <span class="bu">len</span>(x_cols)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>all_r2  <span class="op">=</span> {}</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> r2_subset(indices):</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">len</span>(indices) <span class="op">==</span> <span class="dv">0</span>:</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="fl">0.0</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> LinearRegression().fit(X_sc[:, <span class="bu">list</span>(indices)], y_sc).score(</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>           X_sc[:, <span class="bu">list</span>(indices)], y_sc)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Precomputing R² for all 512 subsets..."</span>)</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> r <span class="kw">in</span> <span class="bu">range</span>(n_feat <span class="op">+</span> <span class="dv">1</span>):</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> subset <span class="kw">in</span> itertools.combinations(<span class="bu">range</span>(n_feat), r):</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>        all_r2[subset] <span class="op">=</span> r2_subset(subset)</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute Shapley value for each driver</span></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>shapley <span class="op">=</span> {}</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(n_feat):</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>    sv      <span class="op">=</span> <span class="fl">0.0</span></span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>    others  <span class="op">=</span> [i <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(n_feat) <span class="cf">if</span> i <span class="op">!=</span> j]</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> r <span class="kw">in</span> <span class="bu">range</span>(n_feat):</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> subset <span class="kw">in</span> itertools.combinations(others, r):</span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>            s      <span class="op">=</span> <span class="bu">len</span>(subset)</span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>            weight <span class="op">=</span> math.factorial(s) <span class="op">*</span> math.factorial(n_feat <span class="op">-</span> s <span class="op">-</span> <span class="dv">1</span>) <span class="op">/</span> math.factorial(n_feat)</span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>            r2_with    <span class="op">=</span> all_r2[<span class="bu">tuple</span>(<span class="bu">sorted</span>(<span class="bu">list</span>(subset) <span class="op">+</span> [j]))]</span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a>            r2_without <span class="op">=</span> all_r2[<span class="bu">tuple</span>(<span class="bu">sorted</span>(<span class="bu">list</span>(subset)))]</span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>            sv <span class="op">+=</span> weight <span class="op">*</span> (r2_with <span class="op">-</span> r2_without)</span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a>    shapley[x_cols[j]] <span class="op">=</span> sv</span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Shapley values sum = </span><span class="sc">{</span><span class="bu">sum</span>(shapley.values())<span class="sc">:.4f}</span><span class="ss">  (R² = </span><span class="sc">{</span>r2_full<span class="sc">:.4f}</span><span class="ss">  ✓)"</span>)</span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> k, v <span class="kw">in</span> <span class="bu">sorted</span>(shapley.items(), key<span class="op">=</span><span class="kw">lambda</span> x: <span class="op">-</span>x[<span class="dv">1</span>]):</span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>k<span class="sc">:&lt;12}</span><span class="ss">: </span><span class="sc">{</span>v<span class="sc">:.4f}</span><span class="ss">  (</span><span class="sc">{</span>v<span class="op">/</span>r2_full<span class="op">*</span><span class="dv">100</span><span class="sc">:.1f}</span><span class="ss">% of R²)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Precomputing R² for all 512 subsets...

Shapley values sum = 0.1090  (R² = 0.1090  ✓)
  impact      : 0.0236  (21.6% of R²)
  trust       : 0.0216  (19.8% of R²)
  service     : 0.0184  (16.9% of R²)
  easy        : 0.0093  (8.5% of R²)
  appealing   : 0.0092  (8.4% of R²)
  differs     : 0.0073  (6.7% of R²)
  build       : 0.0072  (6.6% of R²)
  rewarding   : 0.0068  (6.3% of R²)
  popular     : 0.0056  (5.2% of R²)</code></pre>
</div>
</div>
<p>Shapley values distribute the <em>entire</em> R² (including shared variance) fairly across all drivers. Unlike usefulness, every driver gets credit for the variance it could explain, even if other drivers can explain it too.</p>
<hr>
</section>
<section id="method-5-johnsons-relative-weights" class="level2">
<h2 class="anchored" data-anchor-id="method-5-johnsons-relative-weights">Method 5: Johnson’s Relative Weights</h2>
<p>Johnson’s (2000) method orthogonalizes the predictors via eigendecomposition of the predictor correlation matrix, regresses the outcome on the orthogonal factors, then maps the variance back to the original predictors.</p>
<p><strong>Steps:</strong> 1. Eigendecompose <span class="math inline">\(\mathbf{R}_{XX} = \mathbf{V} \boldsymbol{\Lambda} \mathbf{V}^\top\)</span> 2. Form orthogonal predictors <span class="math inline">\(\mathbf{Z} = \mathbf{X}^* \mathbf{V}\)</span> 3. Regress <span class="math inline">\(Y^*\)</span> on <span class="math inline">\(\mathbf{Z}\)</span> to get coefficients <span class="math inline">\(\hat{\boldsymbol{\beta}}_Z\)</span> 4. Compute relative weight: <span class="math inline">\(\text{RW}_j = \sum_k \left(V_{jk} \sqrt{\lambda_k} \,\hat\beta_{Z_k}\right)^2\)</span></p>
<p><strong>Key property:</strong> Like Shapley, relative weights sum exactly to R². Unlike Shapley, they are computationally fast (no <span class="math inline">\(2^p\)</span> subsets needed).</p>
<div id="6cea6260" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>Rxx           <span class="op">=</span> np.corrcoef(X_sc.T)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>eigvals, eigvecs <span class="op">=</span> np.linalg.eigh(Rxx)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Orthogonal factor scores</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>Z      <span class="op">=</span> X_sc <span class="op">@</span> eigvecs                                    <span class="co"># (n × p)</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>lr_z   <span class="op">=</span> LinearRegression(fit_intercept<span class="op">=</span><span class="va">False</span>).fit(Z, y_sc)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>beta_z <span class="op">=</span> lr_z.coef_                                        <span class="co"># (p,)</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Relative weight for predictor j</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>rw_raw <span class="op">=</span> np.zeros(n_feat)</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(n_feat):</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> k <span class="kw">in</span> <span class="bu">range</span>(n_feat):</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>        rw_raw[j] <span class="op">+=</span> (eigvecs[j, k] <span class="op">*</span> np.sqrt(eigvals[k]) <span class="op">*</span> beta_z[k])<span class="op">**</span><span class="dv">2</span></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>johnson_rw <span class="op">=</span> <span class="bu">dict</span>(<span class="bu">zip</span>(x_cols, rw_raw))</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Relative weights sum = </span><span class="sc">{</span>rw_raw<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">:.4f}</span><span class="ss">  (R² = </span><span class="sc">{</span>r2_full<span class="sc">:.4f}</span><span class="ss">  ✓)"</span>)</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> k, v <span class="kw">in</span> <span class="bu">sorted</span>(johnson_rw.items(), key<span class="op">=</span><span class="kw">lambda</span> x: <span class="op">-</span>x[<span class="dv">1</span>]):</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>k<span class="sc">:&lt;12}</span><span class="ss">: </span><span class="sc">{</span>v<span class="sc">:.4f}</span><span class="ss">  (</span><span class="sc">{</span>v<span class="op">/</span>r2_full<span class="op">*</span><span class="dv">100</span><span class="sc">:.1f}</span><span class="ss">% of R²)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Relative weights sum = 0.1090  (R² = 0.1090  ✓)
  service     : 0.0141  (12.9% of R²)
  build       : 0.0135  (12.4% of R²)
  rewarding   : 0.0133  (12.2% of R²)
  trust       : 0.0130  (12.0% of R²)
  easy        : 0.0128  (11.8% of R²)
  appealing   : 0.0124  (11.4% of R²)
  impact      : 0.0117  (10.7% of R²)
  differs     : 0.0091  (8.4% of R²)
  popular     : 0.0091  (8.3% of R²)</code></pre>
</div>
</div>
<hr>
</section>
<section id="method-6-random-forest-gini-importance" class="level2">
<h2 class="anchored" data-anchor-id="method-6-random-forest-gini-importance">Method 6: Random Forest Gini Importance</h2>
<p>Random forests build an ensemble of decision trees on bootstrap samples. At each split, the algorithm selects the feature that most reduces <strong>node impurity</strong> (measured by Gini for classification, MSE for regression). <strong>Mean decrease in impurity</strong> sums this reduction across all trees, normalized to sum to 1.</p>
<p><strong>Advantages over regression-based methods:</strong> - Captures <strong>nonlinear</strong> relationships and interactions - No assumption of linearity or additivity - Naturally handles correlated predictors through random feature subsampling</p>
<p><strong>Limitation:</strong> Gini importance is on a different scale (sums to 1, not R²), so it’s a relative ranking rather than a variance decomposition.</p>
<div id="2bd59bda" class="cell" data-execution_count="9">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>rf <span class="op">=</span> RandomForestRegressor(n_estimators<span class="op">=</span><span class="dv">500</span>, random_state<span class="op">=</span><span class="dv">42</span>, n_jobs<span class="op">=-</span><span class="dv">1</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>rf.fit(X, y)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>gini_imp <span class="op">=</span> <span class="bu">dict</span>(<span class="bu">zip</span>(x_cols, rf.feature_importances_))</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Random Forest Gini Importance (sums to 1.0):"</span>)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> k, v <span class="kw">in</span> <span class="bu">sorted</span>(gini_imp.items(), key<span class="op">=</span><span class="kw">lambda</span> x: <span class="op">-</span>x[<span class="dv">1</span>]):</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>k<span class="sc">:&lt;12}</span><span class="ss">: </span><span class="sc">{</span>v<span class="sc">:.4f}</span><span class="ss">  (</span><span class="sc">{</span>v<span class="op">*</span><span class="dv">100</span><span class="sc">:.1f}</span><span class="ss">%)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Random Forest Gini Importance (sums to 1.0):
  trust       : 0.1523  (15.2%)
  impact      : 0.1396  (14.0%)
  service     : 0.1361  (13.6%)
  rewarding   : 0.1055  (10.5%)
  build       : 0.0997  (10.0%)
  easy        : 0.0973  (9.7%)
  popular     : 0.0953  (9.5%)
  differs     : 0.0896  (9.0%)
  appealing   : 0.0847  (8.5%)</code></pre>
</div>
</div>
<hr>
</section>
<section id="the-full-comparison-table" class="level2">
<h2 class="anchored" data-anchor-id="the-full-comparison-table">The Full Comparison Table</h2>
<div id="61be14b8" class="cell" data-execution_count="10">
<div class="cell-output cell-output-display">
<style>
.kt { border-collapse: collapse; font-size: 13px; font-family: sans-serif; width: 100%; }
.kt th { background: #3A7EC6; color: white; padding: 9px 12px; text-align: center; }
.kt td { padding: 7px 12px; text-align: center; border-bottom: 1px solid #eee; }
.kt tr:nth-child(even) { background: #f5f8fc; }
.kt tr.top { background: #d4edda !important; font-weight: bold; }
.kt tr.bot { background: #fde8e4 !important; }
</style>

<table class="kt caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Driver</th>
<th data-quarto-table-cell-role="th">Pearson r</th>
<th data-quarto-table-cell-role="th">Std. Coef.</th>
<th data-quarto-table-cell-role="th">Usefulness</th>
<th data-quarto-table-cell-role="th">Shapley</th>
<th data-quarto-table-cell-role="th">Johnson RW</th>
<th data-quarto-table-cell-role="th">RF Gini</th>
</tr>
</thead>
<tbody>
<tr class="top odd">
<td><strong>Impact</strong></td>
<td>+0.2545</td>
<td>+0.1284</td>
<td>0.0112</td>
<td>0.0236</td>
<td>0.0117</td>
<td>0.1396</td>
</tr>
<tr class="top even">
<td><strong>Trust</strong></td>
<td>+0.2557</td>
<td>+0.1158</td>
<td>0.0082</td>
<td>0.0216</td>
<td>0.0130</td>
<td>0.1523</td>
</tr>
<tr class="odd">
<td><strong>Service</strong></td>
<td>+0.2511</td>
<td>+0.0884</td>
<td>0.0047</td>
<td>0.0184</td>
<td>0.0141</td>
<td>0.1361</td>
</tr>
<tr class="even">
<td><strong>Easy</strong></td>
<td>+0.2130</td>
<td>+0.0220</td>
<td>0.0003</td>
<td>0.0093</td>
<td>0.0128</td>
<td>0.0973</td>
</tr>
<tr class="odd">
<td><strong>Appealing</strong></td>
<td>+0.2080</td>
<td>+0.0338</td>
<td>0.0007</td>
<td>0.0092</td>
<td>0.0124</td>
<td>0.0847</td>
</tr>
<tr class="even">
<td><strong>Differs</strong></td>
<td>+0.1848</td>
<td>+0.0278</td>
<td>0.0006</td>
<td>0.0073</td>
<td>0.0091</td>
<td>0.0896</td>
</tr>
<tr class="odd">
<td><strong>Build</strong></td>
<td>+0.1919</td>
<td>+0.0200</td>
<td>0.0003</td>
<td>0.0072</td>
<td>0.0135</td>
<td>0.0997</td>
</tr>
<tr class="bot even">
<td><strong>Rewarding</strong></td>
<td>+0.1946</td>
<td>+0.0051</td>
<td>0.0000</td>
<td>0.0068</td>
<td>0.0133</td>
<td>0.1055</td>
</tr>
<tr class="bot odd">
<td><strong>Popular</strong></td>
<td>+0.1714</td>
<td>+0.0166</td>
<td>0.0002</td>
<td>0.0056</td>
<td>0.0091</td>
<td>0.0953</td>
</tr>
</tbody>
</table>

<p style="font-size:11px;color:#666;margin-top:8px">
Sorted by Shapley value. Green = top 2 drivers. Red = bottom 2 drivers.
Full model R² = 0.1090. Pearson r and RF Gini are on different scales (not directly comparable to R²-based methods).
</p>
</div>
</div>
<div id="cell-fig-comparison" class="cell" data-execution_count="11">
<div class="cell-output cell-output-display">
<div id="fig-comparison" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-comparison-output-1.png" width="1422" height="541" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Side-by-side comparison of all six importance methods. Items are ordered by Shapley rank in all panels. Impact and Trust consistently emerge as the top two drivers across all methods.
</figcaption>
</figure>
</div>
</div>
</div>
<hr>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<section id="what-the-methods-agree-on" class="level3">
<h3 class="anchored" data-anchor-id="what-the-methods-agree-on">What the Methods Agree On</h3>
<p>All six methods consistently identify <strong>Impact</strong> and <strong>Trust</strong> as the top two drivers of customer satisfaction, and <strong>Popular</strong> and <strong>Rewarding</strong> as the least important. This consensus across methodologically diverse approaches provides high confidence in the ranking at the extremes.</p>
</section>
<section id="where-the-methods-disagree-and-why" class="level3">
<h3 class="anchored" data-anchor-id="where-the-methods-disagree-and-why">Where the Methods Disagree — and Why</h3>
<p>The middle tier (Build, Differs, Easy, Appealing, Service) shows more variation across methods. This is expected: these drivers are more correlated with each other and with the top drivers, so the choice of how to allocate shared variance matters.</p>
<p><strong>Pearson correlations</strong> are highest for Trust (0.256), Service (0.251), and Impact (0.255) — all nearly tied. This masks the fact that Impact has a much larger <em>partial</em> effect once other drivers are controlled for.</p>
<p><strong>Standardized coefficients</strong> for Impact (0.128) and Trust (0.116) are far larger than for any other driver. But Build (0.020) and Easy (0.022) look nearly irrelevant — likely because their variance is shared with Trust and Impact, which dominate the regression.</p>
<p><strong>Drop-one usefulness</strong> tells a similar story but is even more extreme: Impact (0.011) and Trust (0.008) account for nearly all unique variance, while most other drivers contribute almost nothing uniquely. This reflects multicollinearity — when important drivers are in the model, correlated lesser drivers add little.</p>
<p><strong>Shapley values</strong> provide the most balanced picture. By averaging over all possible orderings, they allocate shared variance proportionally. Trust (0.022) and Impact (0.024) still lead, but Service (0.018) gets more credit than in the regression or usefulness approaches, because it can explain variance that builds or differs cannot.</p>
<p><strong>Johnson’s relative weights</strong> are notably more even across drivers than the other R²-based methods. This is a known property: the orthogonalization step distributes shared variance more aggressively. In highly correlated survey data like this, this can either be a feature (guards against undervaluing correlated drivers) or a limitation (may overstate the importance of drivers that are only important because they correlate with truly important ones).</p>
<p><strong>Random forest Gini</strong> picks up Impact (0.140) and Trust (0.152) as top drivers — consistent with all other methods — and identifies Service (0.136) as important, likely because its relationship with satisfaction involves nonlinear patterns that the linear models underweight.</p>
</section>
<section id="which-method-should-you-use" class="level3">
<h3 class="anchored" data-anchor-id="which-method-should-you-use">Which Method Should You Use?</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Goal</th>
<th>Recommended Method</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Quick sanity check</td>
<td>Pearson r</td>
</tr>
<tr class="even">
<td>Partial effects, statistical inference</td>
<td>Std. Coef.</td>
</tr>
<tr class="odd">
<td>Unique contribution only</td>
<td>Usefulness</td>
</tr>
<tr class="even">
<td>Fair allocation of all variance</td>
<td>Shapley</td>
</tr>
<tr class="odd">
<td>Fast approximation to Shapley</td>
<td>Johnson RW</td>
</tr>
<tr class="even">
<td>Nonlinear, interaction-aware</td>
<td>RF Gini</td>
</tr>
</tbody>
</table>
<p>For a business audience, <strong>Shapley values</strong> are the most defensible single method: they have a clear theoretical justification (fair allocation), always sum to R², and avoid both the underestimation problem of regression coefficients and the overestimation problem of raw correlations. For exploratory work or when computational cost matters, <strong>Johnson’s relative weights</strong> are an excellent approximation.</p>
</section>
<section id="business-recommendation" class="level3">
<h3 class="anchored" data-anchor-id="business-recommendation">Business Recommendation</h3>
<p>Based on the convergent evidence across all six methods, the clearest recommendation is: <strong>prioritize improving Impact and Trust</strong>. These two drivers consistently rank #1 and #2 regardless of method, and together account for roughly 44% of the explained variance (by Shapley). Service is a secondary priority — it consistently ranks 3rd or 4th and appears to have nonlinear effects captured by the random forest. The bottom three drivers (Popular, Rewarding, Build) show weak and inconsistent importance across methods; resources invested here are unlikely to move the satisfaction needle.</p>


<!-- -->

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "What Drives Customer Satisfaction? A Key Drivers Analysis"</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="an">subtitle:</span><span class="co"> "Comparing Six Variable Importance Methods on Customer Survey Data"</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Jihee Yoon"</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> today</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span><span class="co"> [Variable Importance, Key Drivers, Random Forest, Shapley Values]</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "We compute and compare six methods for quantifying variable importance — Pearson correlations, standardized regression coefficients, drop-one usefulness, Shapley values, Johnson's relative weights, and random forest Gini importance — applied to a customer satisfaction survey."</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a><span class="co">    toc-depth: 3</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a><span class="co">    toc-title: "Contents"</span></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a><span class="co">    theme: flatly</span></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a><span class="co">    highlight-style: github</span></span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a><span class="co">    fig-width: 10</span></span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a><span class="co">    fig-height: 5</span></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a><span class="an">execute:</span></span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a><span class="co">  warning: false</span></span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a><span class="co">  message: false</span></span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb15-29"><a href="#cb15-29" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb15-30"><a href="#cb15-30" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> stats</span>
<span id="cb15-31"><a href="#cb15-31" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LinearRegression</span>
<span id="cb15-32"><a href="#cb15-32" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.ensemble <span class="im">import</span> RandomForestRegressor</span>
<span id="cb15-33"><a href="#cb15-33" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> StandardScaler</span>
<span id="cb15-34"><a href="#cb15-34" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> IPython.display <span class="im">import</span> display, HTML</span>
<span id="cb15-35"><a href="#cb15-35" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb15-36"><a href="#cb15-36" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.patches <span class="im">as</span> mpatches</span>
<span id="cb15-37"><a href="#cb15-37" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> itertools, math, warnings</span>
<span id="cb15-38"><a href="#cb15-38" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">"ignore"</span>)</span>
<span id="cb15-39"><a href="#cb15-39" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">42</span>)</span>
<span id="cb15-40"><a href="#cb15-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-41"><a href="#cb15-41" aria-hidden="true" tabindex="-1"></a>BLUE   <span class="op">=</span> <span class="st">"#3A7EC6"</span></span>
<span id="cb15-42"><a href="#cb15-42" aria-hidden="true" tabindex="-1"></a>GREEN  <span class="op">=</span> <span class="st">"#27AE60"</span></span>
<span id="cb15-43"><a href="#cb15-43" aria-hidden="true" tabindex="-1"></a>ORANGE <span class="op">=</span> <span class="st">"#E87040"</span></span>
<span id="cb15-44"><a href="#cb15-44" aria-hidden="true" tabindex="-1"></a>GRAY   <span class="op">=</span> <span class="st">"#8D99AE"</span></span>
<span id="cb15-45"><a href="#cb15-45" aria-hidden="true" tabindex="-1"></a>RED    <span class="op">=</span> <span class="st">"#C0392B"</span></span>
<span id="cb15-46"><a href="#cb15-46" aria-hidden="true" tabindex="-1"></a>PURPLE <span class="op">=</span> <span class="st">"#8E44AD"</span></span>
<span id="cb15-47"><a href="#cb15-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-48"><a href="#cb15-48" aria-hidden="true" tabindex="-1"></a>plt.rcParams.update({</span>
<span id="cb15-49"><a href="#cb15-49" aria-hidden="true" tabindex="-1"></a>    <span class="st">"figure.facecolor"</span>:  <span class="st">"white"</span>,</span>
<span id="cb15-50"><a href="#cb15-50" aria-hidden="true" tabindex="-1"></a>    <span class="st">"axes.facecolor"</span>:    <span class="st">"#FAFBFC"</span>,</span>
<span id="cb15-51"><a href="#cb15-51" aria-hidden="true" tabindex="-1"></a>    <span class="st">"axes.spines.top"</span>:   <span class="va">False</span>,</span>
<span id="cb15-52"><a href="#cb15-52" aria-hidden="true" tabindex="-1"></a>    <span class="st">"axes.spines.right"</span>: <span class="va">False</span>,</span>
<span id="cb15-53"><a href="#cb15-53" aria-hidden="true" tabindex="-1"></a>    <span class="st">"axes.grid"</span>:         <span class="va">True</span>,</span>
<span id="cb15-54"><a href="#cb15-54" aria-hidden="true" tabindex="-1"></a>    <span class="st">"grid.alpha"</span>:        <span class="fl">0.3</span>,</span>
<span id="cb15-55"><a href="#cb15-55" aria-hidden="true" tabindex="-1"></a>    <span class="st">"grid.linestyle"</span>:    <span class="st">"--"</span>,</span>
<span id="cb15-56"><a href="#cb15-56" aria-hidden="true" tabindex="-1"></a>    <span class="st">"font.family"</span>:       <span class="st">"sans-serif"</span>,</span>
<span id="cb15-57"><a href="#cb15-57" aria-hidden="true" tabindex="-1"></a>    <span class="st">"font.size"</span>:         <span class="dv">11</span>,</span>
<span id="cb15-58"><a href="#cb15-58" aria-hidden="true" tabindex="-1"></a>    <span class="st">"axes.titlesize"</span>:    <span class="dv">13</span>,</span>
<span id="cb15-59"><a href="#cb15-59" aria-hidden="true" tabindex="-1"></a>    <span class="st">"axes.titleweight"</span>:  <span class="st">"bold"</span>,</span>
<span id="cb15-60"><a href="#cb15-60" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb15-61"><a href="#cb15-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-62"><a href="#cb15-62" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">"data_for_drivers_analysis.csv"</span>)</span>
<span id="cb15-63"><a href="#cb15-63" aria-hidden="true" tabindex="-1"></a>y_col  <span class="op">=</span> <span class="st">"satisfaction"</span></span>
<span id="cb15-64"><a href="#cb15-64" aria-hidden="true" tabindex="-1"></a>x_cols <span class="op">=</span> [<span class="st">"trust"</span>, <span class="st">"build"</span>, <span class="st">"differs"</span>, <span class="st">"easy"</span>, <span class="st">"appealing"</span>,</span>
<span id="cb15-65"><a href="#cb15-65" aria-hidden="true" tabindex="-1"></a>          <span class="st">"rewarding"</span>, <span class="st">"popular"</span>, <span class="st">"service"</span>, <span class="st">"impact"</span>]</span>
<span id="cb15-66"><a href="#cb15-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-67"><a href="#cb15-67" aria-hidden="true" tabindex="-1"></a>X  <span class="op">=</span> df[x_cols].values</span>
<span id="cb15-68"><a href="#cb15-68" aria-hidden="true" tabindex="-1"></a>y  <span class="op">=</span> df[y_col].values</span>
<span id="cb15-69"><a href="#cb15-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-70"><a href="#cb15-70" aria-hidden="true" tabindex="-1"></a>scaler <span class="op">=</span> StandardScaler()</span>
<span id="cb15-71"><a href="#cb15-71" aria-hidden="true" tabindex="-1"></a>X_sc   <span class="op">=</span> scaler.fit_transform(X)</span>
<span id="cb15-72"><a href="#cb15-72" aria-hidden="true" tabindex="-1"></a>y_sc   <span class="op">=</span> (y <span class="op">-</span> y.mean()) <span class="op">/</span> y.std()</span>
<span id="cb15-73"><a href="#cb15-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-74"><a href="#cb15-74" aria-hidden="true" tabindex="-1"></a>Rxy <span class="op">=</span> np.array([stats.pearsonr(X_sc[:, j], y_sc)[<span class="dv">0</span>] <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(x_cols))])</span>
<span id="cb15-75"><a href="#cb15-75" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-76"><a href="#cb15-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-77"><a href="#cb15-77" aria-hidden="true" tabindex="-1"></a><span class="fu">## Introduction</span></span>
<span id="cb15-78"><a href="#cb15-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-79"><a href="#cb15-79" aria-hidden="true" tabindex="-1"></a>When a company runs a customer satisfaction survey, the natural follow-up question is: **what actually drives satisfaction?** Is it product quality, ease of use, brand trust, or something else? The challenge is that most drivers are correlated with each other, so simply looking at which variable has the highest correlation with satisfaction can be misleading.</span>
<span id="cb15-80"><a href="#cb15-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-81"><a href="#cb15-81" aria-hidden="true" tabindex="-1"></a>**Key drivers analysis** is a set of techniques for measuring the *relative importance* of each driver after accounting for the fact that predictors are correlated. Different methods make different assumptions and decompose explained variance in different ways — and a trustworthy analysis compares them side by side.</span>
<span id="cb15-82"><a href="#cb15-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-83"><a href="#cb15-83" aria-hidden="true" tabindex="-1"></a>In this post we apply **six methods** to a customer satisfaction survey dataset (n = 2,553 respondents, 9 drivers) and replicate the variable importance table from class:</span>
<span id="cb15-84"><a href="#cb15-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-85"><a href="#cb15-85" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Pearson correlation** — simple bivariate relationship</span>
<span id="cb15-86"><a href="#cb15-86" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Standardized regression coefficients** — partial effects controlling for all others</span>
<span id="cb15-87"><a href="#cb15-87" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Drop-one usefulness** — R² lost when each driver is removed</span>
<span id="cb15-88"><a href="#cb15-88" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>**Shapley values** — fair allocation of R² across all coalition orderings</span>
<span id="cb15-89"><a href="#cb15-89" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>**Johnson's relative weights** — variance decomposition via orthogonalization</span>
<span id="cb15-90"><a href="#cb15-90" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>**Random forest Gini importance** — nonlinear, tree-based importance</span>
<span id="cb15-91"><a href="#cb15-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-92"><a href="#cb15-92" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb15-93"><a href="#cb15-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-94"><a href="#cb15-94" aria-hidden="true" tabindex="-1"></a><span class="fu">## The Data</span></span>
<span id="cb15-95"><a href="#cb15-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-98"><a href="#cb15-98" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb15-99"><a href="#cb15-99" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb15-100"><a href="#cb15-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-101"><a href="#cb15-101" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">"data_for_drivers_analysis.csv"</span>)</span>
<span id="cb15-102"><a href="#cb15-102" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Rows: </span><span class="sc">{</span>df<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="sc">}</span><span class="ss">   Columns: </span><span class="sc">{</span>df<span class="sc">.</span>shape[<span class="dv">1</span>]<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb15-103"><a href="#cb15-103" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Outcome  : </span><span class="sc">{</span>y_col<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb15-104"><a href="#cb15-104" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Drivers  : </span><span class="sc">{</span>x_cols<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb15-105"><a href="#cb15-105" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Satisfaction range: </span><span class="sc">{</span>df[y_col]<span class="sc">.</span><span class="bu">min</span>()<span class="sc">}</span><span class="ss">–</span><span class="sc">{</span>df[y_col]<span class="sc">.</span><span class="bu">max</span>()<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb15-106"><a href="#cb15-106" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Driver variables  : binary (0/1) except satisfaction (1–5 scale)"</span>)</span>
<span id="cb15-107"><a href="#cb15-107" aria-hidden="true" tabindex="-1"></a>df[x_cols <span class="op">+</span> [y_col]].describe().<span class="bu">round</span>(<span class="dv">3</span>)</span>
<span id="cb15-108"><a href="#cb15-108" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-109"><a href="#cb15-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-110"><a href="#cb15-110" aria-hidden="true" tabindex="-1"></a>The outcome variable <span class="in">`satisfaction`</span> is measured on a 1–5 scale. The nine driver variables are all binary (0 = no, 1 = yes), capturing whether each respondent agreed with statements about the brand across dimensions like trust, build quality, differentiation, ease of use, appeal, and so on.</span>
<span id="cb15-111"><a href="#cb15-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-114"><a href="#cb15-114" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb15-115"><a href="#cb15-115" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb15-116"><a href="#cb15-116" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-corr-matrix</span></span>
<span id="cb15-117"><a href="#cb15-117" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Correlation matrix of all variables. Drivers are moderately inter-correlated (0.2–0.5), making raw correlations with satisfaction potentially misleading — which motivates the need for methods that account for multicollinearity."</span></span>
<span id="cb15-118"><a href="#cb15-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-119"><a href="#cb15-119" aria-hidden="true" tabindex="-1"></a>corr <span class="op">=</span> df[x_cols <span class="op">+</span> [y_col]].corr()</span>
<span id="cb15-120"><a href="#cb15-120" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="dv">7</span>))</span>
<span id="cb15-121"><a href="#cb15-121" aria-hidden="true" tabindex="-1"></a>im <span class="op">=</span> ax.imshow(corr.values, cmap<span class="op">=</span><span class="st">"RdBu_r"</span>, vmin<span class="op">=-</span><span class="fl">0.6</span>, vmax<span class="op">=</span><span class="fl">0.6</span>)</span>
<span id="cb15-122"><a href="#cb15-122" aria-hidden="true" tabindex="-1"></a>ax.set_xticks(<span class="bu">range</span>(<span class="bu">len</span>(corr.columns)))</span>
<span id="cb15-123"><a href="#cb15-123" aria-hidden="true" tabindex="-1"></a>ax.set_yticks(<span class="bu">range</span>(<span class="bu">len</span>(corr.columns)))</span>
<span id="cb15-124"><a href="#cb15-124" aria-hidden="true" tabindex="-1"></a>ax.set_xticklabels(corr.columns, rotation<span class="op">=</span><span class="dv">40</span>, ha<span class="op">=</span><span class="st">"right"</span>, fontsize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb15-125"><a href="#cb15-125" aria-hidden="true" tabindex="-1"></a>ax.set_yticklabels(corr.columns, fontsize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb15-126"><a href="#cb15-126" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(corr)):</span>
<span id="cb15-127"><a href="#cb15-127" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(corr)):</span>
<span id="cb15-128"><a href="#cb15-128" aria-hidden="true" tabindex="-1"></a>        ax.text(j, i, <span class="ss">f"</span><span class="sc">{</span>corr<span class="sc">.</span>values[i,j]<span class="sc">:.2f}</span><span class="ss">"</span>, ha<span class="op">=</span><span class="st">"center"</span>, va<span class="op">=</span><span class="st">"center"</span>,</span>
<span id="cb15-129"><a href="#cb15-129" aria-hidden="true" tabindex="-1"></a>                fontsize<span class="op">=</span><span class="dv">8</span>, color<span class="op">=</span><span class="st">"white"</span> <span class="cf">if</span> <span class="bu">abs</span>(corr.values[i,j]) <span class="op">&gt;</span> <span class="fl">0.35</span> <span class="cf">else</span> <span class="st">"black"</span>)</span>
<span id="cb15-130"><a href="#cb15-130" aria-hidden="true" tabindex="-1"></a>plt.colorbar(im, ax<span class="op">=</span>ax, fraction<span class="op">=</span><span class="fl">0.03</span>)</span>
<span id="cb15-131"><a href="#cb15-131" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Correlation Matrix — All Variables"</span>)</span>
<span id="cb15-132"><a href="#cb15-132" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb15-133"><a href="#cb15-133" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb15-134"><a href="#cb15-134" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-135"><a href="#cb15-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-136"><a href="#cb15-136" aria-hidden="true" tabindex="-1"></a>The drivers are moderately inter-correlated (typical for survey data), which means the choice of importance method matters: raw correlations will overstate the importance of variables that happen to correlate with other important drivers, while regression coefficients can understate the importance of variables that share variance with other predictors.</span>
<span id="cb15-137"><a href="#cb15-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-138"><a href="#cb15-138" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb15-139"><a href="#cb15-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-140"><a href="#cb15-140" aria-hidden="true" tabindex="-1"></a><span class="fu">## Method 1: Pearson Correlations</span></span>
<span id="cb15-141"><a href="#cb15-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-142"><a href="#cb15-142" aria-hidden="true" tabindex="-1"></a>The simplest measure of importance: the bivariate correlation between each driver and satisfaction.</span>
<span id="cb15-143"><a href="#cb15-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-144"><a href="#cb15-144" aria-hidden="true" tabindex="-1"></a>$$r_{X_j, Y} = \frac{\sum_i (X_{ij} - \bar{X}_j)(Y_i - \bar{Y})}{\sqrt{\sum_i (X_{ij} - \bar{X}_j)^2 \cdot \sum_i (Y_i - \bar{Y})^2}}$$</span>
<span id="cb15-145"><a href="#cb15-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-146"><a href="#cb15-146" aria-hidden="true" tabindex="-1"></a>**Interpretation:** $r$ ranges from −1 to +1. A larger positive value means the driver has a stronger raw association with satisfaction. The key limitation is that correlations do not control for other drivers — a driver can appear important simply because it correlates with a truly important driver.</span>
<span id="cb15-147"><a href="#cb15-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-150"><a href="#cb15-150" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb15-151"><a href="#cb15-151" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb15-152"><a href="#cb15-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-153"><a href="#cb15-153" aria-hidden="true" tabindex="-1"></a>pearson <span class="op">=</span> {}</span>
<span id="cb15-154"><a href="#cb15-154" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> j, col <span class="kw">in</span> <span class="bu">enumerate</span>(x_cols):</span>
<span id="cb15-155"><a href="#cb15-155" aria-hidden="true" tabindex="-1"></a>    r, p <span class="op">=</span> stats.pearsonr(df[col], df[y_col])</span>
<span id="cb15-156"><a href="#cb15-156" aria-hidden="true" tabindex="-1"></a>    pearson[col] <span class="op">=</span> {<span class="st">"r"</span>: r, <span class="st">"p"</span>: p}</span>
<span id="cb15-157"><a href="#cb15-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-158"><a href="#cb15-158" aria-hidden="true" tabindex="-1"></a>pearson_df <span class="op">=</span> pd.DataFrame(pearson).T.sort_values(<span class="st">"r"</span>, ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb15-159"><a href="#cb15-159" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(pearson_df.<span class="bu">round</span>(<span class="dv">4</span>))</span>
<span id="cb15-160"><a href="#cb15-160" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-161"><a href="#cb15-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-162"><a href="#cb15-162" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb15-163"><a href="#cb15-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-164"><a href="#cb15-164" aria-hidden="true" tabindex="-1"></a><span class="fu">## Method 2: Standardized Regression Coefficients</span></span>
<span id="cb15-165"><a href="#cb15-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-166"><a href="#cb15-166" aria-hidden="true" tabindex="-1"></a>We regress satisfaction on all nine drivers simultaneously, after standardizing both the predictors and outcome to have mean 0 and standard deviation 1. This gives **partial effects** — the association between each driver and satisfaction *holding all other drivers constant*.</span>
<span id="cb15-167"><a href="#cb15-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-168"><a href="#cb15-168" aria-hidden="true" tabindex="-1"></a>$$\hat{Y}^* = \beta_1 X_1^* + \beta_2 X_2^* + \cdots + \beta_p X_p^*$$</span>
<span id="cb15-169"><a href="#cb15-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-170"><a href="#cb15-170" aria-hidden="true" tabindex="-1"></a>where $^*$ denotes standardization. Because all variables are on the same scale, $|\beta_j|$ is directly comparable across drivers.</span>
<span id="cb15-171"><a href="#cb15-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-172"><a href="#cb15-172" aria-hidden="true" tabindex="-1"></a>**Limitation:** When predictors are correlated, variance shared between them is not allocated to any single predictor — it simply "disappears" from individual coefficients. This leads to underestimation of important-but-correlated drivers.</span>
<span id="cb15-173"><a href="#cb15-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-176"><a href="#cb15-176" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb15-177"><a href="#cb15-177" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb15-178"><a href="#cb15-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-179"><a href="#cb15-179" aria-hidden="true" tabindex="-1"></a>lr_full <span class="op">=</span> LinearRegression().fit(X_sc, y_sc)</span>
<span id="cb15-180"><a href="#cb15-180" aria-hidden="true" tabindex="-1"></a>std_coef <span class="op">=</span> <span class="bu">dict</span>(<span class="bu">zip</span>(x_cols, lr_full.coef_))</span>
<span id="cb15-181"><a href="#cb15-181" aria-hidden="true" tabindex="-1"></a>r2_full  <span class="op">=</span> lr_full.score(X_sc, y_sc)</span>
<span id="cb15-182"><a href="#cb15-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-183"><a href="#cb15-183" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Full model R² = </span><span class="sc">{</span>r2_full<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb15-184"><a href="#cb15-184" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb15-185"><a href="#cb15-185" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> k, v <span class="kw">in</span> <span class="bu">sorted</span>(std_coef.items(), key<span class="op">=</span><span class="kw">lambda</span> x: <span class="op">-</span><span class="bu">abs</span>(x[<span class="dv">1</span>])):</span>
<span id="cb15-186"><a href="#cb15-186" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>k<span class="sc">:&lt;12}</span><span class="ss">: </span><span class="sc">{</span>v<span class="sc">:+.4f}</span><span class="ss">"</span>)</span>
<span id="cb15-187"><a href="#cb15-187" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-188"><a href="#cb15-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-189"><a href="#cb15-189" aria-hidden="true" tabindex="-1"></a>The full model R² = **`{python} f"{r2_full:.3f}"`** — meaning the nine drivers together explain about 10.9% of the variance in satisfaction. Notice that several coefficients are near zero: this reflects suppression from multicollinearity, not genuine unimportance.</span>
<span id="cb15-190"><a href="#cb15-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-191"><a href="#cb15-191" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb15-192"><a href="#cb15-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-193"><a href="#cb15-193" aria-hidden="true" tabindex="-1"></a><span class="fu">## Method 3: Drop-One Usefulness</span></span>
<span id="cb15-194"><a href="#cb15-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-195"><a href="#cb15-195" aria-hidden="true" tabindex="-1"></a>For each driver, we ask: *how much does R² drop if we remove this driver from the full model?*</span>
<span id="cb15-196"><a href="#cb15-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-197"><a href="#cb15-197" aria-hidden="true" tabindex="-1"></a>$$\text{Usefulness}_j = R^2_{\text{full}} - R^2_{-j}$$</span>
<span id="cb15-198"><a href="#cb15-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-199"><a href="#cb15-199" aria-hidden="true" tabindex="-1"></a>where $R^2_{-j}$ is the R² of the model with driver $j$ removed. This measures the **unique** contribution of each driver — the variance it explains that no other driver can account for.</span>
<span id="cb15-200"><a href="#cb15-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-201"><a href="#cb15-201" aria-hidden="true" tabindex="-1"></a>**Advantage over coefficients:** Usefulness is always non-negative and directly interpretable as variance explained. **Limitation:** It ignores shared variance (variance that could be explained by multiple drivers).</span>
<span id="cb15-202"><a href="#cb15-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-205"><a href="#cb15-205" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb15-206"><a href="#cb15-206" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb15-207"><a href="#cb15-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-208"><a href="#cb15-208" aria-hidden="true" tabindex="-1"></a>usefulness <span class="op">=</span> {}</span>
<span id="cb15-209"><a href="#cb15-209" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> j, col <span class="kw">in</span> <span class="bu">enumerate</span>(x_cols):</span>
<span id="cb15-210"><a href="#cb15-210" aria-hidden="true" tabindex="-1"></a>    X_drop   <span class="op">=</span> np.delete(X_sc, j, axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb15-211"><a href="#cb15-211" aria-hidden="true" tabindex="-1"></a>    r2_drop  <span class="op">=</span> LinearRegression().fit(X_drop, y_sc).score(X_drop, y_sc)</span>
<span id="cb15-212"><a href="#cb15-212" aria-hidden="true" tabindex="-1"></a>    usefulness[col] <span class="op">=</span> r2_full <span class="op">-</span> r2_drop</span>
<span id="cb15-213"><a href="#cb15-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-214"><a href="#cb15-214" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Full R² = </span><span class="sc">{</span>r2_full<span class="sc">:.4f}</span><span class="ss">   |   Sum of usefulness = </span><span class="sc">{</span><span class="bu">sum</span>(usefulness.values())<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb15-215"><a href="#cb15-215" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb15-216"><a href="#cb15-216" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> k, v <span class="kw">in</span> <span class="bu">sorted</span>(usefulness.items(), key<span class="op">=</span><span class="kw">lambda</span> x: <span class="op">-</span>x[<span class="dv">1</span>]):</span>
<span id="cb15-217"><a href="#cb15-217" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>k<span class="sc">:&lt;12}</span><span class="ss">: </span><span class="sc">{</span>v<span class="sc">:.4f}</span><span class="ss">  (</span><span class="sc">{</span>v<span class="op">/</span>r2_full<span class="op">*</span><span class="dv">100</span><span class="sc">:.1f}</span><span class="ss">% of R²)"</span>)</span>
<span id="cb15-218"><a href="#cb15-218" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-219"><a href="#cb15-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-220"><a href="#cb15-220" aria-hidden="true" tabindex="-1"></a>Note that the sum of usefulnesses is much less than R² — the remainder is **shared variance** that multiple drivers can explain, and drop-one doesn't allocate it to anyone.</span>
<span id="cb15-221"><a href="#cb15-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-222"><a href="#cb15-222" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb15-223"><a href="#cb15-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-224"><a href="#cb15-224" aria-hidden="true" tabindex="-1"></a><span class="fu">## Method 4: Shapley Values (Own Implementation)</span></span>
<span id="cb15-225"><a href="#cb15-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-226"><a href="#cb15-226" aria-hidden="true" tabindex="-1"></a>Shapley values come from cooperative game theory. The idea: treat each driver as a "player" and R² as the "prize." For each possible **coalition** (subset) of drivers, compute R². Then each driver's Shapley value is its **average marginal contribution** across all possible orderings of players entering the coalition.</span>
<span id="cb15-227"><a href="#cb15-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-228"><a href="#cb15-228" aria-hidden="true" tabindex="-1"></a>$$\phi_j = \sum_{S \subseteq N \setminus <span class="sc">\{</span>j<span class="sc">\}</span>} \frac{|S|!\,(|N|-|S|-1)!}{|N|!} \left<span class="co">[</span><span class="ot"> R^2(S \cup \{j\}) - R^2(S) \right</span><span class="co">]</span>$$</span>
<span id="cb15-229"><a href="#cb15-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-230"><a href="#cb15-230" aria-hidden="true" tabindex="-1"></a>**Key property:** Shapley values are the *unique* method that simultaneously satisfies:</span>
<span id="cb15-231"><a href="#cb15-231" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Efficiency:** values sum to R²</span>
<span id="cb15-232"><a href="#cb15-232" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Symmetry:** equally contributing drivers get equal values</span>
<span id="cb15-233"><a href="#cb15-233" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Dummy:** a useless driver gets zero</span>
<span id="cb15-234"><a href="#cb15-234" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Additivity:** consistent decomposition</span>
<span id="cb15-235"><a href="#cb15-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-236"><a href="#cb15-236" aria-hidden="true" tabindex="-1"></a>This is the **"fairest"** allocation of R² across correlated predictors.</span>
<span id="cb15-237"><a href="#cb15-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-240"><a href="#cb15-240" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb15-241"><a href="#cb15-241" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb15-242"><a href="#cb15-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-243"><a href="#cb15-243" aria-hidden="true" tabindex="-1"></a><span class="co"># Precompute R² for all 2^9 = 512 subsets</span></span>
<span id="cb15-244"><a href="#cb15-244" aria-hidden="true" tabindex="-1"></a>n_feat <span class="op">=</span> <span class="bu">len</span>(x_cols)</span>
<span id="cb15-245"><a href="#cb15-245" aria-hidden="true" tabindex="-1"></a>all_r2  <span class="op">=</span> {}</span>
<span id="cb15-246"><a href="#cb15-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-247"><a href="#cb15-247" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> r2_subset(indices):</span>
<span id="cb15-248"><a href="#cb15-248" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">len</span>(indices) <span class="op">==</span> <span class="dv">0</span>:</span>
<span id="cb15-249"><a href="#cb15-249" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="fl">0.0</span></span>
<span id="cb15-250"><a href="#cb15-250" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> LinearRegression().fit(X_sc[:, <span class="bu">list</span>(indices)], y_sc).score(</span>
<span id="cb15-251"><a href="#cb15-251" aria-hidden="true" tabindex="-1"></a>           X_sc[:, <span class="bu">list</span>(indices)], y_sc)</span>
<span id="cb15-252"><a href="#cb15-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-253"><a href="#cb15-253" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Precomputing R² for all 512 subsets..."</span>)</span>
<span id="cb15-254"><a href="#cb15-254" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> r <span class="kw">in</span> <span class="bu">range</span>(n_feat <span class="op">+</span> <span class="dv">1</span>):</span>
<span id="cb15-255"><a href="#cb15-255" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> subset <span class="kw">in</span> itertools.combinations(<span class="bu">range</span>(n_feat), r):</span>
<span id="cb15-256"><a href="#cb15-256" aria-hidden="true" tabindex="-1"></a>        all_r2[subset] <span class="op">=</span> r2_subset(subset)</span>
<span id="cb15-257"><a href="#cb15-257" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-258"><a href="#cb15-258" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute Shapley value for each driver</span></span>
<span id="cb15-259"><a href="#cb15-259" aria-hidden="true" tabindex="-1"></a>shapley <span class="op">=</span> {}</span>
<span id="cb15-260"><a href="#cb15-260" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(n_feat):</span>
<span id="cb15-261"><a href="#cb15-261" aria-hidden="true" tabindex="-1"></a>    sv      <span class="op">=</span> <span class="fl">0.0</span></span>
<span id="cb15-262"><a href="#cb15-262" aria-hidden="true" tabindex="-1"></a>    others  <span class="op">=</span> [i <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(n_feat) <span class="cf">if</span> i <span class="op">!=</span> j]</span>
<span id="cb15-263"><a href="#cb15-263" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> r <span class="kw">in</span> <span class="bu">range</span>(n_feat):</span>
<span id="cb15-264"><a href="#cb15-264" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> subset <span class="kw">in</span> itertools.combinations(others, r):</span>
<span id="cb15-265"><a href="#cb15-265" aria-hidden="true" tabindex="-1"></a>            s      <span class="op">=</span> <span class="bu">len</span>(subset)</span>
<span id="cb15-266"><a href="#cb15-266" aria-hidden="true" tabindex="-1"></a>            weight <span class="op">=</span> math.factorial(s) <span class="op">*</span> math.factorial(n_feat <span class="op">-</span> s <span class="op">-</span> <span class="dv">1</span>) <span class="op">/</span> math.factorial(n_feat)</span>
<span id="cb15-267"><a href="#cb15-267" aria-hidden="true" tabindex="-1"></a>            r2_with    <span class="op">=</span> all_r2[<span class="bu">tuple</span>(<span class="bu">sorted</span>(<span class="bu">list</span>(subset) <span class="op">+</span> [j]))]</span>
<span id="cb15-268"><a href="#cb15-268" aria-hidden="true" tabindex="-1"></a>            r2_without <span class="op">=</span> all_r2[<span class="bu">tuple</span>(<span class="bu">sorted</span>(<span class="bu">list</span>(subset)))]</span>
<span id="cb15-269"><a href="#cb15-269" aria-hidden="true" tabindex="-1"></a>            sv <span class="op">+=</span> weight <span class="op">*</span> (r2_with <span class="op">-</span> r2_without)</span>
<span id="cb15-270"><a href="#cb15-270" aria-hidden="true" tabindex="-1"></a>    shapley[x_cols[j]] <span class="op">=</span> sv</span>
<span id="cb15-271"><a href="#cb15-271" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-272"><a href="#cb15-272" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Shapley values sum = </span><span class="sc">{</span><span class="bu">sum</span>(shapley.values())<span class="sc">:.4f}</span><span class="ss">  (R² = </span><span class="sc">{</span>r2_full<span class="sc">:.4f}</span><span class="ss">  ✓)"</span>)</span>
<span id="cb15-273"><a href="#cb15-273" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> k, v <span class="kw">in</span> <span class="bu">sorted</span>(shapley.items(), key<span class="op">=</span><span class="kw">lambda</span> x: <span class="op">-</span>x[<span class="dv">1</span>]):</span>
<span id="cb15-274"><a href="#cb15-274" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>k<span class="sc">:&lt;12}</span><span class="ss">: </span><span class="sc">{</span>v<span class="sc">:.4f}</span><span class="ss">  (</span><span class="sc">{</span>v<span class="op">/</span>r2_full<span class="op">*</span><span class="dv">100</span><span class="sc">:.1f}</span><span class="ss">% of R²)"</span>)</span>
<span id="cb15-275"><a href="#cb15-275" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-276"><a href="#cb15-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-277"><a href="#cb15-277" aria-hidden="true" tabindex="-1"></a>Shapley values distribute the *entire* R² (including shared variance) fairly across all drivers. Unlike usefulness, every driver gets credit for the variance it could explain, even if other drivers can explain it too.</span>
<span id="cb15-278"><a href="#cb15-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-279"><a href="#cb15-279" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb15-280"><a href="#cb15-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-281"><a href="#cb15-281" aria-hidden="true" tabindex="-1"></a><span class="fu">## Method 5: Johnson's Relative Weights</span></span>
<span id="cb15-282"><a href="#cb15-282" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-283"><a href="#cb15-283" aria-hidden="true" tabindex="-1"></a>Johnson's (2000) method orthogonalizes the predictors via eigendecomposition of the predictor correlation matrix, regresses the outcome on the orthogonal factors, then maps the variance back to the original predictors.</span>
<span id="cb15-284"><a href="#cb15-284" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-285"><a href="#cb15-285" aria-hidden="true" tabindex="-1"></a>**Steps:**</span>
<span id="cb15-286"><a href="#cb15-286" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Eigendecompose $\mathbf{R}_{XX} = \mathbf{V} \boldsymbol{\Lambda} \mathbf{V}^\top$</span>
<span id="cb15-287"><a href="#cb15-287" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Form orthogonal predictors $\mathbf{Z} = \mathbf{X}^* \mathbf{V}$</span>
<span id="cb15-288"><a href="#cb15-288" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Regress $Y^*$ on $\mathbf{Z}$ to get coefficients $\hat{\boldsymbol{\beta}}_Z$</span>
<span id="cb15-289"><a href="#cb15-289" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>Compute relative weight: $\text{RW}_j = \sum_k \left(V_{jk} \sqrt{\lambda_k} \,\hat\beta_{Z_k}\right)^2$</span>
<span id="cb15-290"><a href="#cb15-290" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-291"><a href="#cb15-291" aria-hidden="true" tabindex="-1"></a>**Key property:** Like Shapley, relative weights sum exactly to R². Unlike Shapley, they are computationally fast (no $2^p$ subsets needed).</span>
<span id="cb15-292"><a href="#cb15-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-295"><a href="#cb15-295" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb15-296"><a href="#cb15-296" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb15-297"><a href="#cb15-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-298"><a href="#cb15-298" aria-hidden="true" tabindex="-1"></a>Rxx           <span class="op">=</span> np.corrcoef(X_sc.T)</span>
<span id="cb15-299"><a href="#cb15-299" aria-hidden="true" tabindex="-1"></a>eigvals, eigvecs <span class="op">=</span> np.linalg.eigh(Rxx)</span>
<span id="cb15-300"><a href="#cb15-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-301"><a href="#cb15-301" aria-hidden="true" tabindex="-1"></a><span class="co"># Orthogonal factor scores</span></span>
<span id="cb15-302"><a href="#cb15-302" aria-hidden="true" tabindex="-1"></a>Z      <span class="op">=</span> X_sc <span class="op">@</span> eigvecs                                    <span class="co"># (n × p)</span></span>
<span id="cb15-303"><a href="#cb15-303" aria-hidden="true" tabindex="-1"></a>lr_z   <span class="op">=</span> LinearRegression(fit_intercept<span class="op">=</span><span class="va">False</span>).fit(Z, y_sc)</span>
<span id="cb15-304"><a href="#cb15-304" aria-hidden="true" tabindex="-1"></a>beta_z <span class="op">=</span> lr_z.coef_                                        <span class="co"># (p,)</span></span>
<span id="cb15-305"><a href="#cb15-305" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-306"><a href="#cb15-306" aria-hidden="true" tabindex="-1"></a><span class="co"># Relative weight for predictor j</span></span>
<span id="cb15-307"><a href="#cb15-307" aria-hidden="true" tabindex="-1"></a>rw_raw <span class="op">=</span> np.zeros(n_feat)</span>
<span id="cb15-308"><a href="#cb15-308" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(n_feat):</span>
<span id="cb15-309"><a href="#cb15-309" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> k <span class="kw">in</span> <span class="bu">range</span>(n_feat):</span>
<span id="cb15-310"><a href="#cb15-310" aria-hidden="true" tabindex="-1"></a>        rw_raw[j] <span class="op">+=</span> (eigvecs[j, k] <span class="op">*</span> np.sqrt(eigvals[k]) <span class="op">*</span> beta_z[k])<span class="op">**</span><span class="dv">2</span></span>
<span id="cb15-311"><a href="#cb15-311" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-312"><a href="#cb15-312" aria-hidden="true" tabindex="-1"></a>johnson_rw <span class="op">=</span> <span class="bu">dict</span>(<span class="bu">zip</span>(x_cols, rw_raw))</span>
<span id="cb15-313"><a href="#cb15-313" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Relative weights sum = </span><span class="sc">{</span>rw_raw<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">:.4f}</span><span class="ss">  (R² = </span><span class="sc">{</span>r2_full<span class="sc">:.4f}</span><span class="ss">  ✓)"</span>)</span>
<span id="cb15-314"><a href="#cb15-314" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> k, v <span class="kw">in</span> <span class="bu">sorted</span>(johnson_rw.items(), key<span class="op">=</span><span class="kw">lambda</span> x: <span class="op">-</span>x[<span class="dv">1</span>]):</span>
<span id="cb15-315"><a href="#cb15-315" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>k<span class="sc">:&lt;12}</span><span class="ss">: </span><span class="sc">{</span>v<span class="sc">:.4f}</span><span class="ss">  (</span><span class="sc">{</span>v<span class="op">/</span>r2_full<span class="op">*</span><span class="dv">100</span><span class="sc">:.1f}</span><span class="ss">% of R²)"</span>)</span>
<span id="cb15-316"><a href="#cb15-316" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-317"><a href="#cb15-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-318"><a href="#cb15-318" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb15-319"><a href="#cb15-319" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-320"><a href="#cb15-320" aria-hidden="true" tabindex="-1"></a><span class="fu">## Method 6: Random Forest Gini Importance</span></span>
<span id="cb15-321"><a href="#cb15-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-322"><a href="#cb15-322" aria-hidden="true" tabindex="-1"></a>Random forests build an ensemble of decision trees on bootstrap samples. At each split, the algorithm selects the feature that most reduces **node impurity** (measured by Gini for classification, MSE for regression). **Mean decrease in impurity** sums this reduction across all trees, normalized to sum to 1.</span>
<span id="cb15-323"><a href="#cb15-323" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-324"><a href="#cb15-324" aria-hidden="true" tabindex="-1"></a>**Advantages over regression-based methods:**</span>
<span id="cb15-325"><a href="#cb15-325" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Captures **nonlinear** relationships and interactions</span>
<span id="cb15-326"><a href="#cb15-326" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>No assumption of linearity or additivity</span>
<span id="cb15-327"><a href="#cb15-327" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Naturally handles correlated predictors through random feature subsampling</span>
<span id="cb15-328"><a href="#cb15-328" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-329"><a href="#cb15-329" aria-hidden="true" tabindex="-1"></a>**Limitation:** Gini importance is on a different scale (sums to 1, not R²), so it's a relative ranking rather than a variance decomposition.</span>
<span id="cb15-330"><a href="#cb15-330" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-333"><a href="#cb15-333" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb15-334"><a href="#cb15-334" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb15-335"><a href="#cb15-335" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-336"><a href="#cb15-336" aria-hidden="true" tabindex="-1"></a>rf <span class="op">=</span> RandomForestRegressor(n_estimators<span class="op">=</span><span class="dv">500</span>, random_state<span class="op">=</span><span class="dv">42</span>, n_jobs<span class="op">=-</span><span class="dv">1</span>)</span>
<span id="cb15-337"><a href="#cb15-337" aria-hidden="true" tabindex="-1"></a>rf.fit(X, y)</span>
<span id="cb15-338"><a href="#cb15-338" aria-hidden="true" tabindex="-1"></a>gini_imp <span class="op">=</span> <span class="bu">dict</span>(<span class="bu">zip</span>(x_cols, rf.feature_importances_))</span>
<span id="cb15-339"><a href="#cb15-339" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-340"><a href="#cb15-340" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Random Forest Gini Importance (sums to 1.0):"</span>)</span>
<span id="cb15-341"><a href="#cb15-341" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> k, v <span class="kw">in</span> <span class="bu">sorted</span>(gini_imp.items(), key<span class="op">=</span><span class="kw">lambda</span> x: <span class="op">-</span>x[<span class="dv">1</span>]):</span>
<span id="cb15-342"><a href="#cb15-342" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>k<span class="sc">:&lt;12}</span><span class="ss">: </span><span class="sc">{</span>v<span class="sc">:.4f}</span><span class="ss">  (</span><span class="sc">{</span>v<span class="op">*</span><span class="dv">100</span><span class="sc">:.1f}</span><span class="ss">%)"</span>)</span>
<span id="cb15-343"><a href="#cb15-343" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-344"><a href="#cb15-344" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-345"><a href="#cb15-345" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb15-346"><a href="#cb15-346" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-347"><a href="#cb15-347" aria-hidden="true" tabindex="-1"></a><span class="fu">## The Full Comparison Table</span></span>
<span id="cb15-348"><a href="#cb15-348" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-351"><a href="#cb15-351" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb15-352"><a href="#cb15-352" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb15-353"><a href="#cb15-353" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-354"><a href="#cb15-354" aria-hidden="true" tabindex="-1"></a><span class="co"># Build summary table</span></span>
<span id="cb15-355"><a href="#cb15-355" aria-hidden="true" tabindex="-1"></a>rows <span class="op">=</span> []</span>
<span id="cb15-356"><a href="#cb15-356" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col <span class="kw">in</span> x_cols:</span>
<span id="cb15-357"><a href="#cb15-357" aria-hidden="true" tabindex="-1"></a>    rows.append({</span>
<span id="cb15-358"><a href="#cb15-358" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Driver"</span>:        col.capitalize(),</span>
<span id="cb15-359"><a href="#cb15-359" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Pearson r"</span>:     pearson[col][<span class="st">"r"</span>],</span>
<span id="cb15-360"><a href="#cb15-360" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Std. Coef."</span>:    std_coef[col],</span>
<span id="cb15-361"><a href="#cb15-361" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Usefulness"</span>:    usefulness[col],</span>
<span id="cb15-362"><a href="#cb15-362" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Shapley"</span>:       shapley[col],</span>
<span id="cb15-363"><a href="#cb15-363" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Johnson RW"</span>:    johnson_rw[col],</span>
<span id="cb15-364"><a href="#cb15-364" aria-hidden="true" tabindex="-1"></a>        <span class="st">"RF Gini"</span>:       gini_imp[col],</span>
<span id="cb15-365"><a href="#cb15-365" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb15-366"><a href="#cb15-366" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-367"><a href="#cb15-367" aria-hidden="true" tabindex="-1"></a>tbl <span class="op">=</span> pd.DataFrame(rows).sort_values(<span class="st">"Shapley"</span>, ascending<span class="op">=</span><span class="va">False</span>).reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb15-368"><a href="#cb15-368" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-369"><a href="#cb15-369" aria-hidden="true" tabindex="-1"></a><span class="co"># Rank each method (1 = most important)</span></span>
<span id="cb15-370"><a href="#cb15-370" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> method <span class="kw">in</span> [<span class="st">"Pearson r"</span>, <span class="st">"Std. Coef."</span>, <span class="st">"Usefulness"</span>, <span class="st">"Shapley"</span>, <span class="st">"Johnson RW"</span>, <span class="st">"RF Gini"</span>]:</span>
<span id="cb15-371"><a href="#cb15-371" aria-hidden="true" tabindex="-1"></a>    tbl[<span class="ss">f"Rank_</span><span class="sc">{</span>method<span class="sc">}</span><span class="ss">"</span>] <span class="op">=</span> tbl[method].rank(ascending<span class="op">=</span><span class="va">False</span>).astype(<span class="bu">int</span>)</span>
<span id="cb15-372"><a href="#cb15-372" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-373"><a href="#cb15-373" aria-hidden="true" tabindex="-1"></a><span class="co"># HTML table</span></span>
<span id="cb15-374"><a href="#cb15-374" aria-hidden="true" tabindex="-1"></a>html <span class="op">=</span> <span class="st">"""</span></span>
<span id="cb15-375"><a href="#cb15-375" aria-hidden="true" tabindex="-1"></a><span class="st">&lt;style&gt;</span></span>
<span id="cb15-376"><a href="#cb15-376" aria-hidden="true" tabindex="-1"></a><span class="st">.kt { border-collapse: collapse; font-size: 13px; font-family: sans-serif; width: 100%; }</span></span>
<span id="cb15-377"><a href="#cb15-377" aria-hidden="true" tabindex="-1"></a><span class="st">.kt th { background: #3A7EC6; color: white; padding: 9px 12px; text-align: center; }</span></span>
<span id="cb15-378"><a href="#cb15-378" aria-hidden="true" tabindex="-1"></a><span class="st">.kt td { padding: 7px 12px; text-align: center; border-bottom: 1px solid #eee; }</span></span>
<span id="cb15-379"><a href="#cb15-379" aria-hidden="true" tabindex="-1"></a><span class="st">.kt tr:nth-child(even) { background: #f5f8fc; }</span></span>
<span id="cb15-380"><a href="#cb15-380" aria-hidden="true" tabindex="-1"></a><span class="st">.kt tr.top { background: #d4edda !important; font-weight: bold; }</span></span>
<span id="cb15-381"><a href="#cb15-381" aria-hidden="true" tabindex="-1"></a><span class="st">.kt tr.bot { background: #fde8e4 !important; }</span></span>
<span id="cb15-382"><a href="#cb15-382" aria-hidden="true" tabindex="-1"></a><span class="st">&lt;/style&gt;</span></span>
<span id="cb15-383"><a href="#cb15-383" aria-hidden="true" tabindex="-1"></a><span class="st">&lt;table class="kt"&gt;</span></span>
<span id="cb15-384"><a href="#cb15-384" aria-hidden="true" tabindex="-1"></a><span class="st">&lt;thead&gt;&lt;tr&gt;</span></span>
<span id="cb15-385"><a href="#cb15-385" aria-hidden="true" tabindex="-1"></a><span class="st">  &lt;th&gt;Driver&lt;/th&gt;</span></span>
<span id="cb15-386"><a href="#cb15-386" aria-hidden="true" tabindex="-1"></a><span class="st">  &lt;th&gt;Pearson r&lt;/th&gt;</span></span>
<span id="cb15-387"><a href="#cb15-387" aria-hidden="true" tabindex="-1"></a><span class="st">  &lt;th&gt;Std. Coef.&lt;/th&gt;</span></span>
<span id="cb15-388"><a href="#cb15-388" aria-hidden="true" tabindex="-1"></a><span class="st">  &lt;th&gt;Usefulness&lt;/th&gt;</span></span>
<span id="cb15-389"><a href="#cb15-389" aria-hidden="true" tabindex="-1"></a><span class="st">  &lt;th&gt;Shapley&lt;/th&gt;</span></span>
<span id="cb15-390"><a href="#cb15-390" aria-hidden="true" tabindex="-1"></a><span class="st">  &lt;th&gt;Johnson RW&lt;/th&gt;</span></span>
<span id="cb15-391"><a href="#cb15-391" aria-hidden="true" tabindex="-1"></a><span class="st">  &lt;th&gt;RF Gini&lt;/th&gt;</span></span>
<span id="cb15-392"><a href="#cb15-392" aria-hidden="true" tabindex="-1"></a><span class="st">&lt;/tr&gt;&lt;/thead&gt;&lt;tbody&gt;</span></span>
<span id="cb15-393"><a href="#cb15-393" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span></span>
<span id="cb15-394"><a href="#cb15-394" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> _, row <span class="kw">in</span> tbl.iterrows():</span>
<span id="cb15-395"><a href="#cb15-395" aria-hidden="true" tabindex="-1"></a>    top <span class="op">=</span> row[<span class="st">"Driver"</span>] <span class="kw">in</span> [<span class="st">"Impact"</span>, <span class="st">"Trust"</span>]</span>
<span id="cb15-396"><a href="#cb15-396" aria-hidden="true" tabindex="-1"></a>    bot <span class="op">=</span> row[<span class="st">"Driver"</span>] <span class="kw">in</span> [<span class="st">"Popular"</span>, <span class="st">"Rewarding"</span>]</span>
<span id="cb15-397"><a href="#cb15-397" aria-hidden="true" tabindex="-1"></a>    tr_cls <span class="op">=</span> <span class="st">' class="top"'</span> <span class="cf">if</span> top <span class="cf">else</span> (<span class="st">' class="bot"'</span> <span class="cf">if</span> bot <span class="cf">else</span> <span class="st">""</span>)</span>
<span id="cb15-398"><a href="#cb15-398" aria-hidden="true" tabindex="-1"></a>    html <span class="op">+=</span> <span class="ss">f"""&lt;tr</span><span class="sc">{</span>tr_cls<span class="sc">}</span><span class="ss">&gt;</span></span>
<span id="cb15-399"><a href="#cb15-399" aria-hidden="true" tabindex="-1"></a><span class="ss">  &lt;td&gt;&lt;strong&gt;</span><span class="sc">{</span>row[<span class="st">'Driver'</span>]<span class="sc">}</span><span class="ss">&lt;/strong&gt;&lt;/td&gt;</span></span>
<span id="cb15-400"><a href="#cb15-400" aria-hidden="true" tabindex="-1"></a><span class="ss">  &lt;td&gt;</span><span class="sc">{</span>row[<span class="st">'Pearson r'</span>]<span class="sc">:+.4f}</span><span class="ss">&lt;/td&gt;</span></span>
<span id="cb15-401"><a href="#cb15-401" aria-hidden="true" tabindex="-1"></a><span class="ss">  &lt;td&gt;</span><span class="sc">{</span>row[<span class="st">'Std. Coef.'</span>]<span class="sc">:+.4f}</span><span class="ss">&lt;/td&gt;</span></span>
<span id="cb15-402"><a href="#cb15-402" aria-hidden="true" tabindex="-1"></a><span class="ss">  &lt;td&gt;</span><span class="sc">{</span>row[<span class="st">'Usefulness'</span>]<span class="sc">:.4f}</span><span class="ss">&lt;/td&gt;</span></span>
<span id="cb15-403"><a href="#cb15-403" aria-hidden="true" tabindex="-1"></a><span class="ss">  &lt;td&gt;</span><span class="sc">{</span>row[<span class="st">'Shapley'</span>]<span class="sc">:.4f}</span><span class="ss">&lt;/td&gt;</span></span>
<span id="cb15-404"><a href="#cb15-404" aria-hidden="true" tabindex="-1"></a><span class="ss">  &lt;td&gt;</span><span class="sc">{</span>row[<span class="st">'Johnson RW'</span>]<span class="sc">:.4f}</span><span class="ss">&lt;/td&gt;</span></span>
<span id="cb15-405"><a href="#cb15-405" aria-hidden="true" tabindex="-1"></a><span class="ss">  &lt;td&gt;</span><span class="sc">{</span>row[<span class="st">'RF Gini'</span>]<span class="sc">:.4f}</span><span class="ss">&lt;/td&gt;</span></span>
<span id="cb15-406"><a href="#cb15-406" aria-hidden="true" tabindex="-1"></a><span class="ss">&lt;/tr&gt;"""</span></span>
<span id="cb15-407"><a href="#cb15-407" aria-hidden="true" tabindex="-1"></a>html <span class="op">+=</span> <span class="ss">f"""&lt;/tbody&gt;&lt;/table&gt;</span></span>
<span id="cb15-408"><a href="#cb15-408" aria-hidden="true" tabindex="-1"></a><span class="ss">&lt;p style='font-size:11px;color:#666;margin-top:8px'&gt;</span></span>
<span id="cb15-409"><a href="#cb15-409" aria-hidden="true" tabindex="-1"></a><span class="ss">Sorted by Shapley value. Green = top 2 drivers. Red = bottom 2 drivers.</span></span>
<span id="cb15-410"><a href="#cb15-410" aria-hidden="true" tabindex="-1"></a><span class="ss">Full model R² = </span><span class="sc">{</span>r2_full<span class="sc">:.4f}</span><span class="ss">. Pearson r and RF Gini are on different scales (not directly comparable to R²-based methods).</span></span>
<span id="cb15-411"><a href="#cb15-411" aria-hidden="true" tabindex="-1"></a><span class="ss">&lt;/p&gt;"""</span></span>
<span id="cb15-412"><a href="#cb15-412" aria-hidden="true" tabindex="-1"></a>display(HTML(html))</span>
<span id="cb15-413"><a href="#cb15-413" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-414"><a href="#cb15-414" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-417"><a href="#cb15-417" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb15-418"><a href="#cb15-418" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb15-419"><a href="#cb15-419" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-comparison</span></span>
<span id="cb15-420"><a href="#cb15-420" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Side-by-side comparison of all six importance methods. Items are ordered by Shapley rank in all panels. Impact and Trust consistently emerge as the top two drivers across all methods."</span></span>
<span id="cb15-421"><a href="#cb15-421" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-422"><a href="#cb15-422" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">15</span>, <span class="fl">5.5</span>), sharey<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb15-423"><a href="#cb15-423" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-424"><a href="#cb15-424" aria-hidden="true" tabindex="-1"></a>order    <span class="op">=</span> tbl[<span class="st">"Driver"</span>].tolist()[::<span class="op">-</span><span class="dv">1</span>]   <span class="co"># bottom to top = least to most important</span></span>
<span id="cb15-425"><a href="#cb15-425" aria-hidden="true" tabindex="-1"></a>y_pos    <span class="op">=</span> np.arange(<span class="bu">len</span>(order))</span>
<span id="cb15-426"><a href="#cb15-426" aria-hidden="true" tabindex="-1"></a>colors_g <span class="op">=</span> [GREEN <span class="cf">if</span> d <span class="kw">in</span> [<span class="st">"Impact"</span>, <span class="st">"Trust"</span>] <span class="cf">else</span></span>
<span id="cb15-427"><a href="#cb15-427" aria-hidden="true" tabindex="-1"></a>            RED   <span class="cf">if</span> d <span class="kw">in</span> [<span class="st">"Popular"</span>, <span class="st">"Rewarding"</span>] <span class="cf">else</span> GRAY <span class="cf">for</span> d <span class="kw">in</span> order]</span>
<span id="cb15-428"><a href="#cb15-428" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-429"><a href="#cb15-429" aria-hidden="true" tabindex="-1"></a><span class="co"># Panel 1: Pearson vs Std Coef</span></span>
<span id="cb15-430"><a href="#cb15-430" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> axes[<span class="dv">0</span>]</span>
<span id="cb15-431"><a href="#cb15-431" aria-hidden="true" tabindex="-1"></a>vals_p <span class="op">=</span> [tbl.loc[tbl[<span class="st">"Driver"</span>]<span class="op">==</span>d, <span class="st">"Pearson r"</span>].values[<span class="dv">0</span>] <span class="cf">for</span> d <span class="kw">in</span> order]</span>
<span id="cb15-432"><a href="#cb15-432" aria-hidden="true" tabindex="-1"></a>vals_b <span class="op">=</span> [tbl.loc[tbl[<span class="st">"Driver"</span>]<span class="op">==</span>d, <span class="st">"Std. Coef."</span>].values[<span class="dv">0</span>] <span class="cf">for</span> d <span class="kw">in</span> order]</span>
<span id="cb15-433"><a href="#cb15-433" aria-hidden="true" tabindex="-1"></a>ax.barh(y_pos <span class="op">-</span> <span class="fl">0.2</span>, vals_p, <span class="fl">0.38</span>, color<span class="op">=</span>BLUE,   alpha<span class="op">=</span><span class="fl">0.75</span>, label<span class="op">=</span><span class="st">"Pearson r"</span>)</span>
<span id="cb15-434"><a href="#cb15-434" aria-hidden="true" tabindex="-1"></a>ax.barh(y_pos <span class="op">+</span> <span class="fl">0.2</span>, vals_b, <span class="fl">0.38</span>, color<span class="op">=</span>ORANGE, alpha<span class="op">=</span><span class="fl">0.75</span>, label<span class="op">=</span><span class="st">"Std. Coef."</span>)</span>
<span id="cb15-435"><a href="#cb15-435" aria-hidden="true" tabindex="-1"></a>ax.axvline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">"black"</span>, lw<span class="op">=</span><span class="dv">1</span>, ls<span class="op">=</span><span class="st">"--"</span>, alpha<span class="op">=</span><span class="fl">0.4</span>)</span>
<span id="cb15-436"><a href="#cb15-436" aria-hidden="true" tabindex="-1"></a>ax.set_yticks(y_pos)<span class="op">;</span> ax.set_yticklabels(order, fontsize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb15-437"><a href="#cb15-437" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Pearson r  vs  Std. Coef."</span>, color<span class="op">=</span>BLUE, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb15-438"><a href="#cb15-438" aria-hidden="true" tabindex="-1"></a>ax.legend(frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb15-439"><a href="#cb15-439" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-440"><a href="#cb15-440" aria-hidden="true" tabindex="-1"></a><span class="co"># Panel 2: Usefulness vs Shapley</span></span>
<span id="cb15-441"><a href="#cb15-441" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> axes[<span class="dv">1</span>]</span>
<span id="cb15-442"><a href="#cb15-442" aria-hidden="true" tabindex="-1"></a>vals_u <span class="op">=</span> [tbl.loc[tbl[<span class="st">"Driver"</span>]<span class="op">==</span>d, <span class="st">"Usefulness"</span>].values[<span class="dv">0</span>] <span class="cf">for</span> d <span class="kw">in</span> order]</span>
<span id="cb15-443"><a href="#cb15-443" aria-hidden="true" tabindex="-1"></a>vals_s <span class="op">=</span> [tbl.loc[tbl[<span class="st">"Driver"</span>]<span class="op">==</span>d, <span class="st">"Shapley"</span>].values[<span class="dv">0</span>] <span class="cf">for</span> d <span class="kw">in</span> order]</span>
<span id="cb15-444"><a href="#cb15-444" aria-hidden="true" tabindex="-1"></a>ax.barh(y_pos <span class="op">-</span> <span class="fl">0.2</span>, vals_u, <span class="fl">0.38</span>, color<span class="op">=</span>PURPLE, alpha<span class="op">=</span><span class="fl">0.75</span>, label<span class="op">=</span><span class="st">"Usefulness"</span>)</span>
<span id="cb15-445"><a href="#cb15-445" aria-hidden="true" tabindex="-1"></a>ax.barh(y_pos <span class="op">+</span> <span class="fl">0.2</span>, vals_s, <span class="fl">0.38</span>, color<span class="op">=</span>GREEN,  alpha<span class="op">=</span><span class="fl">0.75</span>, label<span class="op">=</span><span class="st">"Shapley"</span>)</span>
<span id="cb15-446"><a href="#cb15-446" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Usefulness  vs  Shapley"</span>, color<span class="op">=</span>PURPLE, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb15-447"><a href="#cb15-447" aria-hidden="true" tabindex="-1"></a>ax.legend(frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb15-448"><a href="#cb15-448" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-449"><a href="#cb15-449" aria-hidden="true" tabindex="-1"></a><span class="co"># Panel 3: Johnson vs RF Gini</span></span>
<span id="cb15-450"><a href="#cb15-450" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> axes[<span class="dv">2</span>]</span>
<span id="cb15-451"><a href="#cb15-451" aria-hidden="true" tabindex="-1"></a>vals_j  <span class="op">=</span> [tbl.loc[tbl[<span class="st">"Driver"</span>]<span class="op">==</span>d, <span class="st">"Johnson RW"</span>].values[<span class="dv">0</span>] <span class="cf">for</span> d <span class="kw">in</span> order]</span>
<span id="cb15-452"><a href="#cb15-452" aria-hidden="true" tabindex="-1"></a>vals_rf <span class="op">=</span> [tbl.loc[tbl[<span class="st">"Driver"</span>]<span class="op">==</span>d, <span class="st">"RF Gini"</span>].values[<span class="dv">0</span>] <span class="op">/</span> <span class="dv">10</span> <span class="cf">for</span> d <span class="kw">in</span> order]  <span class="co"># rescale for viz</span></span>
<span id="cb15-453"><a href="#cb15-453" aria-hidden="true" tabindex="-1"></a>ax.barh(y_pos <span class="op">-</span> <span class="fl">0.2</span>, vals_j,  <span class="fl">0.38</span>, color<span class="op">=</span>ORANGE, alpha<span class="op">=</span><span class="fl">0.75</span>, label<span class="op">=</span><span class="st">"Johnson RW"</span>)</span>
<span id="cb15-454"><a href="#cb15-454" aria-hidden="true" tabindex="-1"></a>ax.barh(y_pos <span class="op">+</span> <span class="fl">0.2</span>, vals_rf, <span class="fl">0.38</span>, color<span class="op">=</span>RED,    alpha<span class="op">=</span><span class="fl">0.75</span>, label<span class="op">=</span><span class="st">"RF Gini ÷10"</span>)</span>
<span id="cb15-455"><a href="#cb15-455" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Johnson RW  vs  RF Gini (÷10)"</span>, color<span class="op">=</span>ORANGE, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb15-456"><a href="#cb15-456" aria-hidden="true" tabindex="-1"></a>ax.legend(frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb15-457"><a href="#cb15-457" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-458"><a href="#cb15-458" aria-hidden="true" tabindex="-1"></a>plt.suptitle(<span class="st">"Six Variable Importance Methods — Side-by-Side Comparison</span><span class="ch">\n</span><span class="st">(sorted by Shapley rank)"</span>,</span>
<span id="cb15-459"><a href="#cb15-459" aria-hidden="true" tabindex="-1"></a>             fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>, y<span class="op">=</span><span class="fl">1.02</span>)</span>
<span id="cb15-460"><a href="#cb15-460" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb15-461"><a href="#cb15-461" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb15-462"><a href="#cb15-462" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-463"><a href="#cb15-463" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-464"><a href="#cb15-464" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb15-465"><a href="#cb15-465" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-466"><a href="#cb15-466" aria-hidden="true" tabindex="-1"></a><span class="fu">## Discussion</span></span>
<span id="cb15-467"><a href="#cb15-467" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-468"><a href="#cb15-468" aria-hidden="true" tabindex="-1"></a><span class="fu">### What the Methods Agree On</span></span>
<span id="cb15-469"><a href="#cb15-469" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-470"><a href="#cb15-470" aria-hidden="true" tabindex="-1"></a>All six methods consistently identify **Impact** and **Trust** as the top two drivers of customer satisfaction, and **Popular** and **Rewarding** as the least important. This consensus across methodologically diverse approaches provides high confidence in the ranking at the extremes.</span>
<span id="cb15-471"><a href="#cb15-471" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-472"><a href="#cb15-472" aria-hidden="true" tabindex="-1"></a><span class="fu">### Where the Methods Disagree — and Why</span></span>
<span id="cb15-473"><a href="#cb15-473" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-474"><a href="#cb15-474" aria-hidden="true" tabindex="-1"></a>The middle tier (Build, Differs, Easy, Appealing, Service) shows more variation across methods. This is expected: these drivers are more correlated with each other and with the top drivers, so the choice of how to allocate shared variance matters.</span>
<span id="cb15-475"><a href="#cb15-475" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-476"><a href="#cb15-476" aria-hidden="true" tabindex="-1"></a>**Pearson correlations** are highest for Trust (0.256), Service (0.251), and Impact (0.255) — all nearly tied. This masks the fact that Impact has a much larger *partial* effect once other drivers are controlled for.</span>
<span id="cb15-477"><a href="#cb15-477" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-478"><a href="#cb15-478" aria-hidden="true" tabindex="-1"></a>**Standardized coefficients** for Impact (0.128) and Trust (0.116) are far larger than for any other driver. But Build (0.020) and Easy (0.022) look nearly irrelevant — likely because their variance is shared with Trust and Impact, which dominate the regression.</span>
<span id="cb15-479"><a href="#cb15-479" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-480"><a href="#cb15-480" aria-hidden="true" tabindex="-1"></a>**Drop-one usefulness** tells a similar story but is even more extreme: Impact (0.011) and Trust (0.008) account for nearly all unique variance, while most other drivers contribute almost nothing uniquely. This reflects multicollinearity — when important drivers are in the model, correlated lesser drivers add little.</span>
<span id="cb15-481"><a href="#cb15-481" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-482"><a href="#cb15-482" aria-hidden="true" tabindex="-1"></a>**Shapley values** provide the most balanced picture. By averaging over all possible orderings, they allocate shared variance proportionally. Trust (0.022) and Impact (0.024) still lead, but Service (0.018) gets more credit than in the regression or usefulness approaches, because it can explain variance that builds or differs cannot.</span>
<span id="cb15-483"><a href="#cb15-483" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-484"><a href="#cb15-484" aria-hidden="true" tabindex="-1"></a>**Johnson's relative weights** are notably more even across drivers than the other R²-based methods. This is a known property: the orthogonalization step distributes shared variance more aggressively. In highly correlated survey data like this, this can either be a feature (guards against undervaluing correlated drivers) or a limitation (may overstate the importance of drivers that are only important because they correlate with truly important ones).</span>
<span id="cb15-485"><a href="#cb15-485" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-486"><a href="#cb15-486" aria-hidden="true" tabindex="-1"></a>**Random forest Gini** picks up Impact (0.140) and Trust (0.152) as top drivers — consistent with all other methods — and identifies Service (0.136) as important, likely because its relationship with satisfaction involves nonlinear patterns that the linear models underweight.</span>
<span id="cb15-487"><a href="#cb15-487" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-488"><a href="#cb15-488" aria-hidden="true" tabindex="-1"></a><span class="fu">### Which Method Should You Use?</span></span>
<span id="cb15-489"><a href="#cb15-489" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-490"><a href="#cb15-490" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Goal <span class="pp">|</span> Recommended Method <span class="pp">|</span></span>
<span id="cb15-491"><a href="#cb15-491" aria-hidden="true" tabindex="-1"></a><span class="pp">|------|-------------------|</span></span>
<span id="cb15-492"><a href="#cb15-492" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Quick sanity check <span class="pp">|</span> Pearson r <span class="pp">|</span></span>
<span id="cb15-493"><a href="#cb15-493" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Partial effects, statistical inference <span class="pp">|</span> Std. Coef. <span class="pp">|</span></span>
<span id="cb15-494"><a href="#cb15-494" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Unique contribution only <span class="pp">|</span> Usefulness <span class="pp">|</span></span>
<span id="cb15-495"><a href="#cb15-495" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Fair allocation of all variance <span class="pp">|</span> Shapley <span class="pp">|</span></span>
<span id="cb15-496"><a href="#cb15-496" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Fast approximation to Shapley <span class="pp">|</span> Johnson RW <span class="pp">|</span></span>
<span id="cb15-497"><a href="#cb15-497" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Nonlinear, interaction-aware <span class="pp">|</span> RF Gini <span class="pp">|</span></span>
<span id="cb15-498"><a href="#cb15-498" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-499"><a href="#cb15-499" aria-hidden="true" tabindex="-1"></a>For a business audience, **Shapley values** are the most defensible single method: they have a clear theoretical justification (fair allocation), always sum to R², and avoid both the underestimation problem of regression coefficients and the overestimation problem of raw correlations. For exploratory work or when computational cost matters, **Johnson's relative weights** are an excellent approximation.</span>
<span id="cb15-500"><a href="#cb15-500" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-501"><a href="#cb15-501" aria-hidden="true" tabindex="-1"></a><span class="fu">### Business Recommendation</span></span>
<span id="cb15-502"><a href="#cb15-502" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-503"><a href="#cb15-503" aria-hidden="true" tabindex="-1"></a>Based on the convergent evidence across all six methods, the clearest recommendation is: **prioritize improving Impact and Trust**. These two drivers consistently rank #1 and #2 regardless of method, and together account for roughly 44% of the explained variance (by Shapley). Service is a secondary priority — it consistently ranks 3rd or 4th and appears to have nonlinear effects captured by the random forest. The bottom three drivers (Popular, Rewarding, Build) show weak and inconsistent importance across methods; resources invested here are unlikely to move the satisfaction needle.</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>